### ISSUE TITLE
Scheduler starts at wrong time

### ISSUE THREAD

**Issue by giociampa** [d4rken-org/sdmaid-se#101]
I have set up the scheduler to run daily at 1am (UK time), but the App Cleaner runs at some unrelated time in the evening - see screenshot - and has done on several occasions, all without any prompting. The time it runs is roughly the same on each occasion.

Will try to catch it in the act, and provide a logcat.

![Screenshot_20230404-195637_Trebuchet](https://user-images.githubusercontent.com/82525867/229894453-de1d025c-b93a-425f-930a-64967ed52b70.png)

**Comment by d4rken** [comment]
What is the phone doing at the time it executes and at the time it should execute?

There is a healthy amount of delay Android adds to save battery if the phone is at sleep at the scheduled time.

I'm using `setInexactRepeating`: 
https://developer.android.com/reference/android/app/AlarmManager#setInexactRepeating(int,%20long,%20long,%20android.app.PendingIntent)

**Comment by giociampa** [comment]
At the time it should execute, it's plugged in next to my bed (I will usually be asleep by then)

At the time it does execute, it's usually locked as that's about the time I'm eating  my evening meal.

I will check in the morning whether it has run overnight, and report back.

**Comment by giociampa** [comment]
Quick update - it didn't run at 1am this morning :(

![Screenshot_20230405-064734_SD Maid SE~2](https://user-images.githubusercontent.com/82525867/230026322-986f7305-b7b2-4e98-97b9-17f1ca524205.png)

I'll try to remember to start the debug logging before this evening, given that it will presumably run at a similar time to last night. I'll post that here later.

The thought occurs that some more detail relating to the phone might be useful:

Phone: Motorola moto g 5G plus
OS: Android 13 (Lineage 20, 29/03/2023 nightly build)
Magisk: 25.2.11 Canary build (69529ac5)

**Comment by giociampa** [comment]
Apologies for the lack of updates/detail recently - the time at which the schedule is executed has changed to 9.45 am (since the app updated a few days ago it seems) so I've waited to ensure that it was being consistent.

Back to first principles therefore - I have turned on trace mode and logging for just the period in which I change the scheduled time (from 1am to 2am in this case). The resulting file is attached - hopefully it will help determine whether it is the LineageOS build's implementation of setInexactRepeating that is the issue, or whether it's one of the parameters being passed to it.

[eu.darken.sdmse_logfile_1680947940375.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11182953/eu.darken.sdmse_logfile_1680947940375.log.zip)

**Comment by d4rken** [comment]
SD Maid isn't asking for it, but can you manually disable "Battery optimizations" and see if it affects the timing?

**Comment by giociampa** [comment]
Will do - this morning it ran at 2.09am, so will see if that makes things more consistent 👍

**Comment by giociampa** [comment]
It ran again just before 10pm. 😕

What I'll do therefore is close this as non-reproducable until such time as I can establish something more useful for you to look at.

**Comment by d4rken** [comment]
So battery optimization deactivated didn't help?

**Comment by giociampa** [comment]
It would appear not to be the case, but I will carry on looking at this.
