### ISSUE TITLE
AppCleaner deletion slow 0.20.beta / root

### ISSUE THREAD

**Issue by DB9-max** [d4rken-org/sdmaid-se#1012]
AppCleaner results deletion slow 0.20.beta / root. Few previous versions were slow too.

With shizuku is faster, but using root method as so many other apps doesn't use shizuku.

**Smartphone (please complete the following information):**
 - Device: Oneplus Nord 
 - OS: A11
 - Root status: Rooted, Kitsune Mask (Magisk) 26.4
 - SD Maid 2/SE version: 0.20.beta

**Comment by d4rken** [comment]
Please provide a debug log, 🙏

**Comment by aadithya96** [comment]
I'm also facing the same issue with the last 2 builds. The same apps also keeps popping up during deletion and once it completes and if i scan again, the same size is shown. I'm using a oneplus 11.
Maybe an issue with oneplus devices?
Will try to add logs.

**Comment by G-D-B-9-9** [comment]
For me it's just a minute or two longer, and that is significantly slower than what it used to. Appcleaner usually finds some 2-3 GB for deletion.

In SD Maid SE almost all cleaning options are selected in the 3 main cleaners.

**Comment by d4rken** [comment]
@aadithya96 Your device is not rooted and your issue is with the accessibility service. Moved here #1016

@G-D-B-9-9 Has a rooted device and does not need the accessibility service.

It's two different issues.

**Comment by G-D-B-9-9** [comment]
Log here. Maybe it's not a big issue but apps behaviour changed like described. And I didn't see same kind of speed with shizuku as before. Since I've saterted using Sui as shizuku control. I don't if SD Maid SE uses it or not but granted in Sui anyhow.

[eu.darken.sdmse_logfile_1708178085684.zip](https://github.com/d4rken-org/sdmaid-se/files/14319027/eu.darken.sdmse_logfile_1708178085684.zip)

**Comment by G-D-B-9-9** [comment]
Sui https://github.com/RikkaApps/Sui

**Comment by d4rken** [comment]
Thanks for the log, I don't see a "bug", but I'm working through the log to see if there are any bottlenecks where I could improve performance.

**Comment by d4rken** [comment]
Is this still an issue? Has performance improved over the months?

**Comment by d4rken** [comment]
> No really. Though I think I have accessibility service enabled. And Shizuku/Sui as alternative but I guess it uses root...

Ok I'll close the ticket. If specific issues come up, I'm sure I'll look into further performance improvements.

> Corpse finder fast

> System cleaner about fast

> App cleaner slowish

AppCleaner is the most complex tool (except for SystemCleaner with many custom filters).

> But compared to such as App Manager's 1 click cache cleaner it's 2 seconds and done. But SDM2 every_time searches paths, files, names, sizes, times(?) and presents it to user.

If we would restrict deletion to just default caches then it could be this fast too, but SD Maid isn't happy with 90% of the way, we want 99,99% thoroughness :grin: .

> Now that I think of it app cleaner deletion is quite somewhat fast - it's ok - but the indexing seems to take afully time.

If you know a specific case, or app, that is processed much more slowly, feel free to open a new ticket (include a debug log).

> Feedback: History section if that could be turned off from settings?

If you set the retention to 0 days, it should basically be "off".

> Feedback2: If you leave SDM2 into background (searching) and go to another app - SDM2 often gets stopped and returns to the start page without results and have to press cleaner/s running again. I don't get it its lightweight but doesn't then feel like it. Maybe it's A11 there's no Material/you whatever.

That's up to the system unfortunately. It is lightweight, but depending on how many results there are, quite some memory is consumed, but this really depends on the ROM and RAM of a device.
