### ISSUE TITLE
Adb support without Shizuku

### ISSUE THREAD

**Issue by edwyn-amador** [d4rken-org/sdmaid-se#1013]
I just purchased SD Maide SE to support you on the development of the app, but there's something that really frustrates me, currently the only way to give more permissions on my  non-rooted device is by having my phone connected to my computer and I have to do this every single time..this is annoying, please add support to simply provide adb permissions one time only without even needing Shizuku, this would be great for me ane I will greatly appreciate it.

**Comment by d4rken** [comment]
> please add support to simply provide adb permissions one time only without even needing Shizuku, this would be great for me ane I will greatly appreciate it.

That's not possible.

Here are one-time ADB commands that you can use for some things:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-troubleshooting

**Comment by edwyn-amador** [comment]
It seems those things are not enough and will continue asking me to keep my phone connected to my computer using Shizuku to have a more deep cleaning..

May I know if not implementing this is a personal choice of you, or a technical limitation from recent Android versions/policies updates?

**Comment by d4rken** [comment]
This is a technical limitation, if it were possible without Shizuku, then Shizuku wouldn't exist :wink:. It's all workarounds due to not being able to grant broader file access in newer Android versions.

**Comment by edwyn-amador** [comment]
I see, thanks for claryfing @d4rken,

> This is a technical limitation, if it were possible without Shizuku, then Shizuku wouldn't exist 😉.

Just regarding that, I wanted a confirmation if it was a technical limitation or not since that statement above is not really accurate, a lot of things exist as an alternative to other similar but not exact same things, so that's why I asked.

In the given case it could be supported for older Android versions and would work perfectly fine on those cases but I understand if you are not covinced on putting more effort on device-specific implementations of this kind.

Unfortunately in order to fully take advantage from Shizuku on non-rooted devices it would require having ADB wireless debugging support which sadly it isn't supported on my current phone.

Anyway, thanks for answering my question @d4rken, I appreciate it.
