### ISSUE TITLE
Место хранения debug log

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#102]
Возможно debug log лучше хранить в Android/data 🤔 Тогда его можно будет повторно использовать.

**Comment by d4rken** [comment]
Can you explain? I'm not sure what you mean.

**Comment by Ingood5** [comment]
В SD Maid 1 debug log сохраняется в Android/data/..... Если после создания лога я сразу не нажму кнопку отправить, то все равно могу получить доступ к логу в Android/data/... В SD Maid 2 лог сохраняется в data/user/.... К этой папке у меня нет доступа. Если сразу после отправки лога я не нажму "отправить" то уже не смогу другим способом отправить этот лог.

**Comment by d4rken** [comment]
Why is Android/data better?

**Comment by Ingood5** [comment]
Потому что к Android/data у меня есть доступ. На моём устройстве я не могу открыть папку data/user, чтобы скопировать из нее лог.

**Comment by d4rken** [comment]
Hm I'll look into it. I think there were some concerns about permissions, but if this worked in SD Maid 1 it should be no problem in SD Maid 2.
