### ISSUE TITLE
Permission inability/delay on SD card folders

### ISSUE THREAD

**Issue by kgursu** [d4rken-org/sdmaid-se#1027]
**Describe the bug**
During initial setup, I cannot give access permission to Android/data and Android/obb folders, maybe because these folders were created before latest device reset.

**To Reproduce**
1. On startup, try to complete these fields by clicking on them.
2. No success without showing an error.

**Expected behavior**
I expected them to complete like the internal storage ones.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S7+ (SM-T970, gts7xlwifi)
 - OS: Android 11
 - Root status Rooted - Magisk Delta - Kitsune v.27.001 (Debug version, R65C33E4F)
 - SD Maid 2/SE version:  v0.20.0-beta0

**Debug log**
[eu.darken.sdmse_logfile_1708641491898.log](https://github.com/d4rken-org/sdmaid-se/files/14397881/eu.darken.sdmse_logfile_1708641491898.log)
[eu.darken.sdmse_logfile_1708641491898_shizuku.log](https://github.com/d4rken-org/sdmaid-se/files/14397882/eu.darken.sdmse_logfile_1708641491898_shizuku.log)
[eu.darken.sdmse_logfile_1708641491898_root.log](https://github.com/d4rken-org/sdmaid-se/files/14397883/eu.darken.sdmse_logfile_1708641491898_root.log)

**Screenshots/Videos
![Screenshot_2024-02-23_014933.png](https://github.com/d4rken-org/sdmaid-se/assets/35314872/b3ca0c03-c4c8-4978-91d4-a686f7b56e51)

![Screenshot_2024-02-23_014941.png](https://github.com/d4rken-org/sdmaid-se/assets/35314872/467cba84-2ab2-4ed2-bc8e-de810319985b)

![Screenshot_2024-02-23_014922.png](https://github.com/d4rken-org/sdmaid-se/assets/35314872/4d9385fb-a16f-47e7-8ed7-728101a02f0f)

**Additional context**
On the latest attempt, it became successful. It took some time, while accepting these.

**Comment by d4rken** [comment]
Can you provide a debug log of this?
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by kgursu** [comment]
> Can you provide a debug log of this? https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log
Already on the OP:
https://github.com/d4rken-org/sdmaid-se/files/14380030/dumpstate-stats.txt

**Comment by d4rken** [comment]
That's not a debug log, just a text file with a single number in it.

Please read the linked documentation.

**Comment by d4rken** [comment]
> Switched from this older A11 stock firmware to a A13 custom ROM. Would you still need more info?

Only if it is reproducible there too.
Feel free to re-open.
