### ISSUE TITLE
AppCleaner unable to perform operation due accessibility service unavailable 

### ISSUE THREAD

**Issue by hafix** [d4rken-org/sdmaid-se#1028]
**Describe the bug**
AppCleaner failed because Accessibility Service Unavailable 
**To Reproduce**
1. Go to AppCleaner
2. Click on Delete, and click on Delete again
3. See error
![IMG_20240223_163603](https://github.com/d4rken-org/sdmaid-se/assets/2013431/05bd1002-edbb-4448-bb97-2ecef230e256)

**Expected behavior**
Able to perform operation 

**Smartphone (please complete the following information):**
 - Device: Poco F4 GT
 - OS: HyperOS (Android 14)
 - Root status : non-root
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
The error dialog says how to resolve it, enable the accessibility service.
Is there an issue with that?

**Comment by Swift8641** [comment]
I have the same issue. When I go to enable the accessibility service the toggle won't activate. It's like Samsung's One UI doesn't like it.

**Comment by d4rken** [comment]
@Swift8641 Can you get an SD Maid debug log of this?

**Comment by Swift8641** [comment]
This is the debug log that I made. I noticed that when I click the enable accessibility mode link the app doesn't redirect me properly to the system accessibility settings for it.

**Comment by Swift8641** [comment]
Hold on I keep getting an error when I try to upload the file.

**Comment by Swift8641** [comment]
[eu.darken.sdmse_logfile_1710625362979.log](https://github.com/d4rken-org/sdmaid-se/files/14625413/eu.darken.sdmse_logfile_1710625362979.log)

**Comment by Swift8641** [comment]
Success! Apparently I needed to move the file to my computer and extract it before I was able to upload it. Maybe you could also add an option to save the file as uncompressed on the app in a specific location or the downloads folder to make bug reporting easier. On my phone the only way I could make it work was by uploading the file to google drive and then using it on my PC. You can't navigate to the directory it auto saves the files to without plugging in the phone to a computer "at least on a Samsung".

**Comment by TexTexan** [comment]
Since updating to the new 0.22 beta I'm now getting this same issue and cannot turn the service on
![Screenshot_20240319-012532](https://github.com/d4rken-org/sdmaid-se/assets/24875084/52251c9c-3c5d-4922-af36-7136c03939c9)

**Comment by d4rken** [comment]
@TexTexan That's a different issue, see: https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-appops-restrictions

If the FAQ does not help, then open a new issue ticket :+1:

**Comment by TexTexan** [comment]
> @TexTexan That's a different issue, see: https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-appops-restrictions
> 
> If the FAQ does not help, then open a new issue ticket 👍

Apologies, I thought it was the same issue, the solution you linked worked, thanks!

**Comment by FWC-9696** [comment]
> I have the same issue. When I go to enable the accessibility service the toggle won't activate. For some reason the accessibility service can't be enabled.

The service can be enabled if you enable the advanced app options from the 3 dots menu on the app's info screen (in android settings)

**Comment by d4rken** [comment]
@Swift8641 according to the log, you have not enabled the accessibility service in SD Maid's setup. Can you check?

It's not possible to enable the service in the system, if you have not told SD Maid in settings that you want to use it.

```
2024-03-16T21:43:33.781Z  D/SDMSE:Automation:Service: onCreate(application=eu.darken.sdmse.App@6b39b64)
2024-03-16T21:43:33.781Z  V/SDMSE:Debug:Bugs: Leaving crumb Automation service launched
2024-03-16T21:43:33.782Z  W/SDMSE:Debug:Bugs: Bug tracking not initialized yet.
2024-03-16T21:43:33.797Z  V/SDMSE:Automation:ScreenState: state.onStart()
2024-03-16T21:43:33.800Z  V/SDMSE:Automation:ScreenState: state.onEach(): State(isScreenOn=true, isUnlocked=true)
2024-03-16T21:43:33.801Z  V/SDMSE:Automation:Service: ControlView is null and progress is null
2024-03-16T21:43:33.810Z  D/SDMSE:Automation:Service: onServiceConnected()
2024-03-16T21:43:33.810Z  W/SDMSE:Automation:Service: Missing consent for accessibility service, stopping service.
2024-03-16T21:43:33.824Z  D/SDMSE:Automation:Service: onUnbind(intent=Intent { cmp=eu.darken.sdmse/.automation.core.AutomationService })
2024-03-16T21:43:33.825Z  D/SDMSE:Automation:Service: onDestroy()
2024-03-16T21:43:33.825Z  V/SDMSE:Debug:Bugs: Leaving crumb Automation service destroyed
2024-03-16T21:43:33.825Z  W/SDMSE:Debug:Bugs: Bug tracking not initialized yet.
```

```
E/SDMSE:Automation:Manager: serviceLauncher failed: eu.darken.sdmse.automation.core.errors.AutomationNoConsentException: Accessibility service isn't running
	at eu.darken.sdmse.automation.core.AutomationManager$serviceLauncher$1.invokeSuspend(Unknown Source:278)
```

```
core.acs.consent = false,
```

```
State(isNotRequired=false, hasConsent=false, canSelfEnable=false, isServiceEnabled=false, isServiceRunning=false, needsXiaomiAutostart=false, liftRestrictionsIntent=Intent { act=android.settings.APPLICATION_SETTINGS flg=0x10000000 }, showAppOpsRestrictionHint=false)
```

**Comment by Swift8641** [comment]
I just checked. Using the setup page works. Apparently, you need to use the setup page for it to work; you can't just go into system settings and change it. Thanks for your help!

**Comment by d4rken** [comment]
@Swift8641 Due to the sensitive nature of the accessibility service, you need to give explicit consent within SD Maid before SD Maid will use it.

Closing this ticket due to lack of infos from OP @hafix all others issues seem unrelated to the OG cause.
