### ISSUE TITLE
AppCleaner stopped functioning properly after system update

### ISSUE THREAD

**Issue by Wyzmic** [d4rken-org/sdmaid-se#1029]
On my S24 Ultra after the first major update for the month of February, this is what happens:
https://github.com/d4rken-org/sdmaid-se/assets/72083780/86ef8b2d-7de1-4bb4-afc0-cf46096a87b3

**Comment by MarkyMarkDE** [comment]
For me it's little more:
After all regularly App Updates, I need to reboot my phone, otherwise SDMaid SE do not work anymore, simply the App will not executed by unknown reasons.

**Comment by d4rken** [comment]
> On my S24 Ultra after the first major update for the month of February, this is what happens: https://github.com/d4rken-org/sdmaid-se/assets/72083780/86ef8b2d-7de1-4bb4-afc0-cf46096a87b3

This seems to be language related. SD Maid is looking for the english word "Storage" but your screen is not in english. Please provide a debug log.

> After all regularly App Updates, I need to reboot my phone, otherwise SDMaid SE do not work anymore, simply the App will not executed by unknown reasons.

"Does not work anymore" if that means a "crash", please provide the stacktrace for it in a new ticket. If you mean that the accessibility service does not turn on anymore, this is mostly a system issue. Also a new ticket please. Try if it helps if you disable the accessibility service before an update.

**Comment by Wyzmic** [comment]
Ah yes, you're right, if the language of the app doesn't match my phone's language it doesn't run. Thanks for the help man! It doesn't crash, it's all good.
