### ISSUE TITLE
Add option for removing empty directories 

### ISSUE THREAD

**Issue by hexman1999** [d4rken-org/sdmaid-se#1041]
Adding an option for removing empty directories will enhance the app functionality

But i wish to scan then choose, not to be automatic process

**Comment by d4rken** [comment]
That's already possible, isn't it?

The SystemCleaner can find empty directories and you can go into the result details and manually select folders which you want to delete.

**Comment by hexman1999** [comment]
> That's already possible, isn't it?
> 
> The SystemCleaner can find empty directories and you can go into the result details and manually select folders which you want to delete.

Ok, it may be there in systemcleaner but it takes very long because it is not only looking for empty directories

I think making a separate option will be more effective for doing this particular function

I searched for any app which does the function but all of them closed source and mostly removing directories automatically without confirmation which sometimes removing empty folders related to other apps functionality like syncthing

**Comment by hexman1999** [comment]
As it's already there in systemcleaner I suggest allow to tick what to scan before starting full scan, 

I really appreciate your great work, thanks 😁
