### ISSUE TITLE
Setting that opens system app language settings

### ISSUE THREAD

**Issue by NomarCub** [d4rken-org/sdmaid-se#1046]
App language switching on Android 13 was implemented here: https://github.com/d4rken-org/sdmaid-se/issues/378.
However, the system menu for this might be hidden on some devices (MIUI, OnePlus, see the above issue) that do have Android 13.

There's a workaround that works on my OnePlus phone in other apps, see [this comment](https://github.com/osmandapp/OsmAnd/issues/16990#issuecomment-1974810063):

> Apps from [Fossify](https://github.com/FossifyOrg) work the same - there's an entry in in-app settings that opens system app language settings, and it works without any problem on OnePlus 8.

There's another similarly worded issue in this repo, I'm not sure in what way is it related: https://github.com/d4rken-org/sdmaid-se/issues/991.

**Comment by d4rken** [comment]
Hm, can do.

Some links I found interesting:

https://xiaomi.eu/community/threads/miui-14-per-app-language-support.69022/

Fossify launches it like this:

https://github.com/FossifyOrg/Commons/blob/60ddae234ddd09a4d54276bbee95b5a3a64f3ddc/commons/src/main/kotlin/org/fossify/commons/activities/BaseSimpleActivity.kt#L677

https://github.com/FossifyOrg/Thank-You/blob/31d3aeabe811cfaa2894cbfa45f0fdc826b6bf63/app/src/main/kotlin/org/fossify/thankyou/extensions/Context.kt#L52

I wonder if that settings action is available on all ROMs, could we fall back to try and launc the activity directly? :thinking:
