### ISSUE TITLE
Root permission not working with KernelSU

### ISSUE THREAD

**Issue by erfirya** [d4rken-org/sdmaid-se#1069]
**Describe the bug**
Root permission not working.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Corpse/System/App Cleaner'
3. Scroll down to 'filter/specific filter/include other users'

**Expected behavior**
It shouldn't be grayed out and you should be able to toggle it on/off

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO X3 NFC
 - OS: crDroid 10.2 Android 14
 - Root status: Rooted - KernelSU v0.9.0
 - SD Maid 2/SE version: v0.22.0-beta0

**Debug log**
I tried to record a debug log, but after that SD Maid keeps closing and I had to reinstall it.

**Screenshots/Video**
[IMG_20240318_153039](https://github.com/d4rken-org/sdmaid-se/assets/71990871/ea0e9560-5396-4204-a9e1-c843a82ee7b7)
[IMG_20240318_153118](https://github.com/d4rken-org/sdmaid-se/assets/71990871/cf0a5747-457d-4772-9a04-a57e0ab7c776)
[IMG_20240318_153137](https://github.com/d4rken-org/sdmaid-se/assets/71990871/b0047c47-dcb3-4096-93ef-0149ae7199e0)
[IMG_20240318_153208](https://github.com/d4rken-org/sdmaid-se/assets/71990871/acc38a96-c03c-47f7-a799-a7893d87aed0)
[IMG_20240318_153242](https://github.com/d4rken-org/sdmaid-se/assets/71990871/96149df0-966f-44a6-9227-278903e6dbf6)
[IMG_20240318_153257](https://github.com/d4rken-org/sdmaid-se/assets/71990871/5d5acf6a-6f36-46a8-94dc-28f46c6ced5c)
[IMG_20240318_153317](https://github.com/d4rken-org/sdmaid-se/assets/71990871/befd938c-99a3-442d-ab49-549914b8c26f)
[IMG_20240318_153342](https://github.com/d4rken-org/sdmaid-se/assets/71990871/180f20fc-fb6e-40ea-9958-90a8f3de8035)

**Additional context**
When I tried to clean it with one-tap mode, AppCleaner used accessibility service instead of root. I'm also using Mixplorer, swift backup and termux and all these apps are working properly with root permission.

**Comment by d4rken** [comment]
Please provide a debug log from a cold-start (start log, force-stop SD Maid, re-open SD Maid, and go to setup screen).

**Comment by d4rken** [comment]
nvm, saw that you tried that.

Can you enable Debug Mode in SD Maid and grab a logcat log of this?

**Comment by erfirya** [comment]
This is what happens when I try to record a debug log

https://github.com/d4rken-org/sdmaid-se/assets/71990871/ca5400c2-22eb-45e7-8c3b-24827839d1a3

but here's the log
[eu.darken.sdmse_logfile_1710806781358.log](https://github.com/d4rken-org/sdmaid-se/files/14643728/eu.darken.sdmse_logfile_1710806781358.log)
[eu.darken.sdmse_logfile_1710806781358_shizuku.log](https://github.com/d4rken-org/sdmaid-se/files/14643729/eu.darken.sdmse_logfile_1710806781358_shizuku.log)

**Comment by d4rken** [comment]
@erfirya Thank you, this helps me fix it.
