### ISSUE TITLE
Hanging on dashboard if Shizuku is not working correctly

### ISSUE THREAD

**Issue by orlproi** [d4rken-org/sdmaid-se#1079]
After updating the new version, the application remains on the loading screen and freezes at startup.
You need to uninstall and reinstall to unlock it.
The settings remain, but the special accessibility permission must be restored.

**Comment by d4rken** [comment]
Can you get a debug log?
Force stop SD Maid before opening again so the launch is recorded too.
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by orlproi** [comment]
Now even if I reinstall again (same version) the error doesn't occur so I can't debug, I'm waiting for a new version to try.
However 'Shizuku' was enabled and indeed the freeze occurred on the 'coffee animation' screen.
Android 14
Samsung A33

**Comment by cobbAnderson108** [comment]
FWIW, I experience something similar - 'freezing' (or more just taking very long) on the dashboard loading/coffee animation screen. However, my intuition says it's something to do with Shizuku (using wireless debugging mode) and not so much SD Maid. For one, at least on my system, wireless debugging has a hard time staying on and active - I set a quick settings developer tile for it and at least initially its constantly turning off. Oddly, rapidly and repeatedly turning this tile off and on again seems to help it stay on. Similarly, I'm convinced Shizuku doesn't stay running and at best the apps that integrate it are only able to do so if they startup in the presumably brief window of time Shizuku stays running, meaning I have to open them quickly after Shizuku says it's started a session. Again, presumably those apps mostly just require a signal that Shizuku's got an active session on their startup (as in, it seems that a session can terminate without affecting the app that relied on it upon starting up). Further evidence of this being an issue with Shizuku is every time I start a session and the text window closes and returns to the main screen, I can immediately hit start again which just starts another session, ad infinitum. I've made sure I have any power saving features off (although I'm not rooted), and my VPN shouldn't be affecting wireless debugging like that. I hope I've offered anything useful beyond merely ignorant red herrings and muddying the water. I can't quite decipher logs and this is mostly an uneducated guess.

**Comment by cobbAnderson108** [comment]
I should add that the frozen or badly-delayed loading screen in SD Maid only occurs if I'm using it with Shizuku, and this doesn't happen if I just open SD Maid sans-Shizuku. Occasionally, SD Maid will startup saying that Shizuku isn't activated when it *should* be, and in both this case and in those when SD Maid simply hangs on the loading screen, naturally force-stopping SD Maid seems necessary. But again, it's messing around with Shizuku and wireless debugging itself that seems the solution and the source of the issue.

**Comment by d4rken** [comment]
I can't fix Shizuku hanging, but #1106 will change it so that SD Maid will not be stuck forever on the loading screen. A timeout will trigger after 6 seconds.

Then either fix Shizuku or disable its use in SD Maid.

**Comment by d4rken** [comment]
Reopening this because I have to revert the fix in #1106
