### ISSUE TITLE
scanning takes forever

### ISSUE THREAD

**Issue by Tanzin01** [d4rken-org/sdmaid-se#108]
**Describe the bug**
SystemCleaner & Appcleaner scans taking too much time. About 30+ min but still couldnt finish the scans of those two.

.

**Additional context**

Gave all permission including root. The only notable thing is, there is 6-7 android project folders among all files. Screen was off.

 i may attack a log later.
Edit: I forgot, my device is log free. So cant, provide log since system dont collect logs.

Irrelevent to the issue: Thats a cool name for a app! I actully downloaded the app for this solo reason. This name hit me with some memories.

**Comment by d4rken** [comment]
> i may attack a log later.
> Edit: I forgot, my device is log free. So cant, provide log since system dont collect logs.

I don't need a system log, an internal log from SD Maid is enough to see what takes up the time:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

Please state your phone, root and SD Maid version.

**Comment by Tanzin01** [comment]
The in-app logger is something!  Got ton of things....
![Screenshot_20230407-000358](https://user-images.githubusercontent.com/41266558/230460924-e47e267e-a514-40d8-98b9-83f9655b7d91.png)
![Screenshot_20230407-000431](https://user-images.githubusercontent.com/41266558/230460944-01e34db2-3d7d-4c2e-9449-1d46538bec15.png)

![Screenshot_20230407-000443](https://user-images.githubusercontent.com/41266558/230460979-77e17c32-900c-432e-a5b3-f1ac4f732cfd.png)

Files-
[eu.darken.sdmse_logfile_1680795708861.log](https://github.com/d4rken-org/sdmaid-se/files/11173402/eu.darken.sdmse_logfile_1680795708861.log)

[eu.darken.sdmse_logfile_1680800567513.log](https://github.com/d4rken-org/sdmaid-se/files/11173411/eu.darken.sdmse_logfile_1680800567513.log)

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/pull/146 should yield a 3x speed increase, please re-open if performance has not drastically improved.
