### ISSUE TITLE
Bug with AppCleaner: Error - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Git-Forked** [d4rken-org/sdmaid-se#1100]
Bug with AppCleaner: 

```
Error - ArrayIndexOutOfBoundsException
length=2; index=-1
```

**To Reproduce**
1. Click on 'AppCleaner'
2. Wait for it to run some and get stuck.
3. See error

**Expected behavior**
It runs to completion and offers to clear the cache.

**Smartphone (please complete the following information):**
 - Device: [Samsung A01]
 - OS: [Android 10]
 - Root status [non-root]
 - SD Maid 2/SE version [0.22.1-beta1] (IzzyOnDroid)

**Comment by d4rken** [comment]
Can you get a debug log of this?
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by billie80** [comment]
I experience the same issue. Please find the requested log attached. I hope it helps tracking down the issue.
[eu.darken.sdmse_logfile_1711947590562.zip](https://github.com/d4rken-org/sdmaid-se/files/14819541/eu.darken.sdmse_logfile_1711947590562.zip)

**Comment by tkoelpin** [comment]
The same exception to me. 

**Smartphone:**
 - Device: Huawei Honor 8X
 - OS: Android 10
 - Root status: Non-rooted
 - SD Maid 2/SE version: v0.23.0-beta0

**Debug log**
![eu.darken.sdmse_logfile_1711949170396.zip](https://github.com/d4rken-org/sdmaid-se/files/14819727/eu.darken.sdmse_logfile_1711949170396.zip)

**Screenshots/Video**
![Screenshot_20240320_083516_eu.darken.sdmse.jpg](https://github.com/d4rken-org/sdmaid-se/assets/8818843/af630815-0e2c-42a3-8aa1-c3b2df7e5ef2)

**Comment by KBiT7777** [comment]
Same problem.
Until 0.21.0 beta 0 the error did not appear, but from the next beta this same error began even in the latest version 0.23

Smartphone:

- Device: Huawei P30 Lite
- OS: Android 10
- Root status: Non-rooted
- SD Maid 2/SE version: v0.23.0-beta0

**Comment by d4rken** [comment]
Thanks for the logs, issue is related to manipulating paths (removing prefixes) from `SAFPath`, i.e. files found via storage access framework. Looking into it...

**Comment by tkoelpin** [comment]
Thank you so much, now it finally works smoothly. 🥰
