### ISSUE TITLE
App collapses in on samsung s23 with andr-14

### ISSUE THREAD

**Issue by asenler** [d4rken-org/sdmaid-se#1108]
[signal-2024-04-01-154654](https://github.com/d4rken-org/sdmaid-se/assets/14995466/46d94061-5c97-4a56-b95a-9bd08bc985fb)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.
[eu.darken.sdmse_logfile_1711974603978.zip](https://github.com/d4rken-org/sdmaid-se/files/14823546/eu.darken.sdmse_logfile_1711974603978.zip)

**Additional context**

**Comment by xiaolang179** [comment]
The same crash problem occurs on Android 14 OnePlus Ace2 Pro
Device: [OnePlus Ace2 Pro]
OS: [ANDROID 14]
Root status [NO]
SD Maid 2/SE version [v0.23.0 beta0]
Click setup and crash
![Screenshot_2024-04-01-23-52-22-97_b783bf344239542886fee7b48fa4b892](https://github.com/d4rken-org/sdmaid-se/assets/165686279/b4b7c7f9-5f56-443d-b704-d98a930e996e)
[eu.darken.sdmse_logfile_1711986879549.zip](https://github.com/d4rken-org/sdmaid-se/files/14826047/eu.darken.sdmse_logfile_1711986879549.zip)

**Comment by d4rken** [comment]
Thanks for the bug report, the logs show that the grid span count is being set to 0.

`getSpanCount(354.2857/720)=0`

There should have been a min check that sets it to 1 in this case, fix coming :).
