### ISSUE TITLE
Make settings unavailable for root.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#112]
Возможно надо сделать недоступными root-опции в настройках CorpseFinder, если root на устройстве нет 🤔  Как в SD Maid 1.

> It may be necessary to disable the root options in the CorpseFinder settings if there is no root on the device. As in SD Maid 1.

**Comment by d4rken** [comment]
Just because of aesthetics?

Internally the CorpseFinder will still skip them if there is no root.

It currently has two benefits:
* It feels better to un-rooted users as not everything "looks unavailable"
* Less complex code for us :smile:

**Comment by Ingood5** [comment]
👍

Разумно, неуверен только в моменте что пользователь предпочтет видеть пункты, которые на самом деле не очищаются. Если пользователь решит попробовать настроить под себя и зайдет в настройки, но не знает что такое рут, то с большой вероятностью (я так думаю) начнет искать подробности, чтобы понять включать ли ему эти настройки. Если эти настройки недоступны, возле них может быть сообщение "у вас нет рут-доступа для использования этих настроек", в этом случае гораздо больше вероятность что он не будет искать что это. Ещё есть вариант чтобы без рута эти настройки вообще исчезали. Но это все лишний код.

**Comment by d4rken** [comment]
Closing for now.
