### ISSUE TITLE
sd maid not detecting shizuku. 

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [d4rken-org/sdmaid-se#1123]
**Describe the bug**
I have shizuku installed and enabled but sd maid isn't being detected. I'll add that all my other apps are detecting SD maid. I've cleared cache and data of SD maid and redid the setup and it does the same thing. 

**To Reproduce**
1. Open SD maid se
2. Wait a few seconds and the app indicates that Shizuku is not installed or running (checked many times and it is, even reset shizuku and SD maid)
3. Even going into settings and toggling it there untoggles after a few seconds or scroll down and back to. 

**Expected behavior**
It to detect shizuku

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s10e
 - OS: [Android 12]
 - Root status [not routed]
 - SD Maid 2/SE version [e.g. v0.23.1 beta]

**Screenshots/Video**

https://github.com/d4rken-org/sdmaid-se/assets/12119604/8848c3db-dae6-41a1-9fa8-20d9d8c3f466

**Additional context**
If anything else is needed I'll try to get the info to you as soon as possible. Or if you have any suggestions to remedy this I'll try it if possible.

**Comment by d4rken** [comment]
I think this is fixed in v2.32.2: https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.23.2-beta0

It's currently not available on Google Play because of #1074
