### ISSUE TITLE
The buttons to run do not work.

### ISSUE THREAD

**Issue by jeffreyjbn** [d4rken-org/sdmaid-se#1129]
**Describe the bug**
The first time working correctly.  then when entering some time later the interface does not work well

For it to work you have to force close it and resume scanning

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Poco F2 pro 5g
 - OS: Android 12 / Miui 14
 - Root status: Not root
 - SD Maid 2/SE version v0.23.3-beta]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log of this.
