### ISSUE TITLE
AppCleaner scan stuck at 1%

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#113]
AppCleaner 13 минут остаётся на 1% на папке MIUI. Дольше ждать не стал. Проблема появилась или после обновления SD Maid, или после включения дополнительных опций.

![IMG_20230407_105857](https://user-images.githubusercontent.com/60130882/230568916-84ad3028-2c94-4f0f-ba42-fd8374208336.jpg)

[eu.darken.sdmse_logfile_1680853392828.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11177199/eu.darken.sdmse_logfile_1680853392828.log.zip)

**Comment by Ingood5** [comment]
Проверил, ошибка появляется после включения опции Include system apps.

**Comment by d4rken** [comment]
#146 should yield a 3x speed increase, please re-open if performance has not drastically improved.

**Comment by Ingood5** [comment]
Как узнать в какой версии SD Maid появятся улучшения, сделанные в этом отчёте? В SD Maid 1 в отчётах всегда была указана версия SD Maid.

**Comment by d4rken** [comment]
I might use the "milestone" system later too, but currently it's easier like this.

You can view all included changes in the release view:
https://github.com/d4rken-org/sdmaid-se/releases

Or you can check individual changes by clicking the number `5665218`:
![Screenshot from 2023-04-12 03-19-13](https://user-images.githubusercontent.com/1439229/231322788-968f6c95-d953-456e-9b46-fd729b9b926f.png)

and then seeing if it is has a tag like here:
![Screenshot from 2023-04-12 03-19-30](https://user-images.githubusercontent.com/1439229/231322882-d1585509-f362-461f-8ed1-08155058caf4.png)

It's on the `main` code branch, and it is contained the build with the tag `v0.7.1-beta0` .
