### ISSUE TITLE
Route exclusion don't work for Telegram hidden /data directory

### ISSUE THREAD

**Issue by Erz3** [d4rken-org/sdmaid-se#1135]
**Describe the bug**
Route exclusion don't work for Telegram hidden /data directory

**To Reproduce**
1. Add "/storage/emulated/0/Android/data/org.telegram.messenger.web" like excluded route.
2. Click on search duplicated files
3. It find files in the excluded route

**Smartphone (please complete the following information):**
 - Device: RealmeX2
 - OS: Android 11
 - Root status: No ROOT
 - SD Maid 2/SE version: 0.23.3-beta0

**Comment by d4rken** [comment]
Can you record a debug log of this?

**Comment by Erz3** [comment]
> Can you record a debug log of this?

Ok. Check your email.

**Comment by d4rken** [comment]
Thanks, can you show me a screenshot of the exclusions you created?

**Comment by Erz3** [comment]
> Thanks, can you show me a screenshot of the exclusions you created?


![a3a1dbe9-221b-4659-ba51-484accaae89bclean.jpg](https://github.com/d4rken-org/sdmaid-se/assets/77393537/686e24d6-285c-4d9c-a47f-96aa433778c2)

**Comment by d4rken** [comment]
SD Maid is finding these via a different path.
I think it will work if you create an exclusion for `Android/data/org.telegram.messenger.web`, can you try?

`lookupFiles(SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/7279-4FB0, segments=[Android, data, org.telegram.messenger.web]))`

**Comment by Erz3** [comment]
> I think it will work if you create an exclusion for `Android/data/org.telegram.messenger.web`, can you try?

Ok, now work.

Thanks. You are doing an amazing job with this tool.

Keep going.
