### ISSUE TITLE
Hyper OS adaptation

### ISSUE THREAD

**Issue by flairvi** [d4rken-org/sdmaid-se#1138]
Dear developer, can you adapt hyper os?

**Comment by d4rken** [comment]
Adapt what and how, please be more specific.

If you mean the accessibiltiy service and appcleaner, then please provide a debug log of it failing.

**Comment by Hazmi35** [comment]
I haven't tried SDMaid SE yet but I used SDMaid Pro. Just got my phone updated to HyperOS. 
Accesibility service is working but the AppCleaner fails to remove caches, perhaps because of the UI update? 
I believe it's the same for SDMaid SE too?

**Comment by d4rken** [comment]
@Hazmi35 possible, I need a debug logs to look into it

**Comment by Hazmi35** [comment]
> @Hazmi35 possible, I need a debug logs to look into it

The logs for SD Maid SE or the old one?

**Comment by d4rken** [comment]
New one (SD Maid SE), the old one is not expected to work with the latest OS updates from phone companies.
