### ISSUE TITLE
The software crashes in some cases

### ISSUE THREAD

**Issue by AwardedSheet865** [d4rken-org/sdmaid-se#1141]
**Describe the bug**
when software notice want to get App message.It will be broken down.

**To Reproduce**
1. Go to SD maid
2. Click on App controller
3. If you keep system default settings. It will be broken down.I  should open get App message before open the app.It will not down.

**Smartphone (please complete the following information):**
 - Device: [Samsung galaxy s22+(china)]
 - OS: [ Android 14]
 - Root status [not rooted or shizuku]
 - SD Maid 2/SE version [e.g. v0.23.3-beta0]

**Comment by d4rken** [comment]
Please provide a debug log or a stacktrace of the crash.
