### ISSUE TITLE
Add fast scrolling to tools

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#115]
В инструментах не хватает возможности быстрого скроллинга перетаскиванием ползунка справа. Когда мусора найдено много, обычным способом проматывать экран долго. 

> The tools lack the ability to quickly scroll by dragging the slider on the right. When a lot of garbage is found, the usual way is to scroll the screen for a long time.

**Comment by Shkzeen** [comment]
Honestly, why not?
I Agree 100%
