### ISSUE TITLE
Empty folder in Android/Data not cleaned with root Android 13

### ISSUE THREAD

**Issue by researchscum** [d4rken-org/sdmaid-se#1154]
**Describe the bug**
Empty folder in Android/Data not cleaned with root and all option turned on

**To Reproduce**
1. Go to 'sd maid se or sd maid'
2. Click on '1 tap button'
3. wait to finish
4. check empty folder in Android/Data/[APP package name]

**Expected behavior**
empty folder gone.

**Smartphone (please complete the following information):**
 - Device: POCO F3
 - OS: Android 13
 - Rooted - Magisk Canary 27002
 - SD Maid 2/SE version 0.23.3-beta0 and SD Maid 5.6.3

**Debug log**
impossible.

**Screenshots/Video**
impossible.

**Additional context**
i suspect because Google play system update 01 April 2024.

**Comment by d4rken** [comment]
I think the top level folders in `Android/data` are excluded at the moment. If the app is still installed, deleting it can cause issues. If the app is no longer installed, then the CorpseFinder should remove any such folders.

Is the app still installed?
