### ISSUE TITLE
Can't install the latest update

### ISSUE THREAD

**Issue by Legitti** [d4rken-org/sdmaid-se#1165]
It gives error on Google play and Play protect won't let it install as apk either

0.24.0-beta0

**Comment by d4rken** [comment]
The most common cause is trying to update the GitHub version with Google Play or vice versa.
What is the exact error message?

**Comment by Legitti** [comment]
![photo_2024-05-09_00-13-02](https://github.com/d4rken-org/sdmaid-se/assets/41343618/2b4d25ef-daa8-460a-b3a0-12f480194aa9)
Theres no way to bypass that. 
![photo_2024-05-09_00-14-24](https://github.com/d4rken-org/sdmaid-se/assets/41343618/909d529a-2267-4c52-8905-2313f3d99e44)

**Comment by Legitti** [comment]
The phone is OnePlus 9 Pro with the latest Android 14 update.

**Comment by mizzyc** [comment]
I got the same error while trying to update the GitHub version with this new GitHub release on my Samsung Galaxy S23!

**Comment by MarkyMarkDE** [comment]
Can't confirm this issue. I'm on Android 14 too with may patches on Pixel 7 and the current FOSS version, no problem to install and no warnings or something.
Try to kill the Google Play Services App and clear cache and data, the same do with the Google Playstore App and wait a few minutes before you reopen the Playstore App, maybe a strange Playstore issue.
But please make sure, that you always install SDMaid SE from the same source.
If this not help, deactivate Play Protect install the Update and activate Play Protect again.

**Comment by mizzyc** [comment]
I just tried again for the 4th time, doing nothing different than before, and for an unknown reason now it worked!
