### ISSUE TITLE
AppCleaner bug

### ISSUE THREAD

**Issue by sdpereira87** [d4rken-org/sdmaid-se#1167]
AppCleaner doesn't clean anything and is very slow when running.

**Comment by MarkyMarkDE** [comment]
Please provide much more details for this issue, maybe additional a debug log.

**Comment by sdpereira87** [comment]
> Please provide much more details for this issue, maybe additional a debug log.
> Otherwise no Dev in the world can do anything 😉. 

Sorry for that, but, i find the cause of the issue: if the system language is different of app language, the appcleaner doesn't work, it looks for the same name in the system, for example "looking for 'cache cleaner' but the system in portuguese is 'limpar chache'.

**Comment by d4rken** [comment]
> Sorry for that, but, i find the cause of the issue: if the system language is different of the app language, the appcleaner doesn't work, it looks for the same name in the system, for example "looking for 'cache cleaner'" but the system in portuguese is 'limpar cache'.

Theoretically this should work. At least I tested it with the default language override option for apps in Android 13? 14?
There was a bug though that in some cases, the system did report the wrong language codes until SD Maid was restarted once. That's a bug in Android though.
