### ISSUE TITLE
Scheduler issue 

### ISSUE THREAD

**Issue by xlakostax** [d4rken-org/sdmaid-se#1169]
Scheduler does not work. Operation fails with the
"еeu.darken.sdmse.automation.cor e.errors.ScreenUnavailableException: Screen is unavailable!"  error

 - Device: Pixel 6 Pro
 - OS: Android 14
 - Root status: Non-Rooted
 - SD Maid 2/SE version: 0.24.0-beta0

**Comment by d4rken** [comment]
You enabled this in the settings for the scheduler. The text explains that accessibility service can't be used with the screen being unavailable. If you enable it and override this behavior then you need to make sure that the screen is available when the scheduler triggers.

**Comment by d4rken** [comment]
I'm considering removing this setting again as people misunderstanding it is a common issue.  🤔

I think the only one using it correctly so far is @MarkyMarkDE who asked me to add this setting.

**Comment by MarkyMarkDE** [comment]
> I'm considering removing this setting again as people misunderstanding it is a common issue. 🤔
> 
> I think the only one using it correctly so far is @MarkyMarkDE who asked me to add this setting.

Please let this option in, maybe we can talk about to explain this more detailed in the faq or something.
