### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ValerioWasTaken** [d4rken-org/sdmaid-se#1170]
![Screenshot_2024-05-13-16-54-55-805_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/101035427/260ba158-050d-4456-90f8-f1ae6593eaf0)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log.
This is a crash of the connection between SD Maid and a service used for privilege escalation (root or ADB).
