### ISSUE TITLE
cleaning system apps slow on some apps - Samsung S23U

### ISSUE THREAD

**Issue by DetlevCM** [d4rken-org/sdmaid-se#1178]
**Describe the bug**
App cleaning is slow on some apps when including system apps. For example Bluetooth.

**To Reproduce**
Clean system apps not just user apps too.

**Expected behavior**
Same speed for all apps (unless huge cache)

**Smartphone (please complete the following information):**
 - Device: Samsung S23U
 - OS: One UI 6.1 - should be Anfroid 14
 - SD Maid 2/SE version 0.24.0-beta0

**Debug log**
If you can reproduce the bug, record the event in debug log.
See attached, maybe it helps. 
[eu.darken.sdmse_logfile_1716572656827.zip](https://github.com/d4rken-org/sdmaid-se/files/15438468/eu.darken.sdmse_logfile_1716572656827.zip)

**Comment by d4rken** [comment]
There is about half a second delay with some apps until the system provides the screen content, but that's not something I can fix and up to the OS.

The other thing i see is that some apps have the "clear cache button" is disabled and SD Maid waits a bit to see if the system will enable it again after processing something, this adds about ~1 second delay. Is this what you mean?

```
2024-05-24T17:46:10.137Z  D/SDMSE:AppCleaner:Automation:Samsung:Specs: Can't click on the clear cache button because it was disabled, but why...
2024-05-24T17:46:10.138Z  W/SDMSE:AppCleaner:Automation:Samsung:Specs: Clear cache button was disabled, but so are others, assuming size calculation going on.
2024-05-24T17:46:10.138Z  D/SDMSE:AppCleaner:Automation:Samsung:Specs: Sleeping for 1000ms to wait for calculation.
```

**Comment by d4rken** [comment]
I have tested this a bit on a Samsung tablet and the Bluetooth app always seems to be blocked, so are some other system apps.

#1183 will cause these apps to get skipped faster, you could consider to also just exclude them from the AppCleaner.

It would be cool to just exclude them by default, but I have not found a way to detect if a system app can't be cleared beforehand.

**Comment by DetlevCM** [comment]
Ah, too bad. Thanks for the follow-up.
