### ISSUE TITLE
Option to keep screen on during scan

### ISSUE THREAD

**Issue by Magneticdud** [d4rken-org/sdmaid-se#119]
The problem: the "battery saver" task killer in Huawei phones is super aggressive

I'm trying to clean the Huawei phone of my friend. It takes a lot of time to scan due to the hundreds and hundreds of fake folders with fake files used for tracking and ads purposes like .gs0

The problem is that, even if I put SD Maid SE in "whitelist" and even if the phone is charging, the SECOND the screen turns off, the "battery saver" feature IMMEDIATELY kills the app. I'm at the fifth time attempting a scan, always starting from zero, constantly keeping a finger on the screen to simulate user presence.

The solution I'd like:

* A setting to keep the screen on until the app is on foreground.

Unfortunately looks like there are no other workarounds, I whitelisted the app and "disabled" the battery saver, I "locked in memory", but nothing, the phone has 4 gigabytes of RAM but looks like it's just a number to increase the BOM, as  the "battery saver" simulates the experience of a phone with 256mb of RAM.

It also disables the accessibility service as soon as the app is killed, needing to do the setup again....

A feature like this would be useless to everyone that has a phone with a battery saver coded by someone with a brain, but unfortunately there are some people like my friend that made the mistake of buying a phone with a "simulated monotasking" version of Android that severely forbids any kind of background process (unless it's in a secret whitelist, because other invasive apps like Alipay are allowed to stay in background at all times wasting 1 gb of RAM)

Sorry for the rant, but it's the whole morning that I'm trying to complete a scan... already 45+ minutes of scan, I'm accidentally distracted for a millisecond, the screen goes off and I need to start again...

**Comment by d4rken** [comment]
Sounds reasonable. What phone and Android version do you have?

Maybe only keep screen on while there is an active task and SD Maid is in the foreground :thinking:

**Comment by Magneticdud** [comment]
It's a Huawei P30 Lite, with Android 10.

My friend is using a lot of sideloaded chinese apps that are using questionable ways to track the user, for example the /tencent folder is over 80gb of "cache". Similar story for another app called "xiaohongshu", another 16 gb of "cache" that is stored on the sdcard instead of using the system cache (from the app details, those "caches" don't show as cache, but as data, and can't be deleted)

**Comment by Magneticdud** [comment]
wow that was fast, thank you for your consideration
