### ISSUE TITLE
Pro license disappear 

### ISSUE THREAD

**Issue by githubuser013** [d4rken-org/sdmaid-se#1211]
Hi,
After today update the pro license is not loaded to the app.
Is this me only or it's a bug. sd maid se v1.0.1-rc0
![Screenshot_20240608-145007](https://github.com/d4rken-org/sdmaid-se/assets/71437659/0d80c0f6-541e-4587-bbe5-5fb0b2feb1e7)

**Comment by githubuser013** [comment]
i don't know what happened but now it's working fine.

**Comment by d4rken** [comment]
Probably an issue with the Google Play app or service.
