### ISSUE TITLE
Apps settings stay open after cleaning

### ISSUE THREAD

**Issue by RetifdelaBretonne** [d4rken-org/sdmaid-se#1212]
**Describe the bug**
After cleaning, last cleaned app's entry stays open in Settings > Apps > [App] > App info > Storage.

**To Reproduce**
1. Open SD Maid SE Pro
2. Click on '1 tap button' and confirm cleaning
3. Wait to finish
4. Last cleaned app's entry stays open.

**Expected behavior**
Some previous versions closed all apps settings.
I believe the problem started around version v0.24.0-beta0. (Maybe when string 'CANCELLA CACHE' became all written in uppercase?)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A53 5G
 - OS: Android 14, One UI 6.1, Italian language
 - Root status: no Rooted, no Brand
 - SD Maid 2/SE PRO version: v1.0.1-rc0 (Jun 6, 2024) by Google Play.

**Additional context**
Sorry but English is not my native language. I hope I was clear in my explanation.

**Comment by MarkyMarkDE** [comment]
If i'm right, then this happens when an error occurs. Please provide a debug log

**Comment by iTzJasper** [comment]
This also happens on my Samsung A52s.

**Comment by d4rken** [comment]
Can anyone record a debug log this?

You are right that the method of how the last app screen is closed has changed, but I think the current approach is better than the last one, currently we are telling the system to re-show SD Maid, while previously we simulated back-button presses.
