### ISSUE TITLE
Simplify Navigation to File Details

### ISSUE THREAD

**Issue by tEctutoRIt** [d4rken-org/sdmaid-se#1215]
Navigating to the details of files app is removing takes too many steps, making the process cumbersome for users.

![88b92d88-bdf4-4001-acf7-69b6d4fc5cfe](https://github.com/d4rken-org/sdmaid-se/assets/77356742/fe629e49-8738-4662-881d-608e5b947e79)

I would like it if the 'eye' icon could show the file details directly in one step, eliminating the need for multiple clicks.

As there is no need to show the 'confirm delete' dialogue here, as someone wanting to delete directly would have done so from the main screen, but for people wanting to see more details, it creates an extra step.

CURRENT:
1. Click on the eye icon
2. A screen with some details about type & number & size of files
3. Click on a category
4. Click Show details in 'Confirm deletion' dialogue box
5. Full details will now be displayed, along with all the information shown on the screen in step 2.

SUGGESTED: Clicking on the eye icon should take you straight to STEP 5.

**Comment by d4rken** [comment]
What action would take you to the category screen then?

**Comment by d4rken** [comment]
Clicking the green folder icon directly opens the details without confirmation.

Maybe we could change the green eye on the dashboard to open the details, while clicking the card itself opens the list view.
