### ISSUE TITLE
GitHub API call happens before onboarding is complete

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#1217]
Hello, I just checked it again since it's available on F-Droid's official repo.
Install the app > open > it shows "Welcome" screen
But here at the same time it's already connecting to `api.github.com`. Can we do such that it only works after the user goes through the "Privacy" screen i.e. don't connect to internet during on boarding process?

_Ursprünglich gepostet von @shuvashish76 in https://github.com/d4rken-org/sdmaid-se/issues/755#issuecomment-2166983075_

**Comment by shuvashish76** [comment]
Sorry for nitpicking this minor issue,  it's just that F-Droid/FOSS folks don't prefer to connect _NonFreeNet_ without their knowledge. I expected this as to be a bug, ThankYou :)

**Comment by d4rken** [comment]
It's not nitpicking, all bugs matter :heart:.

Did you install SD Maid through F-Droid when you produced this bug?

For F-Droid the update check is disabled by default through this logic:

https://github.com/d4rken-org/sdmaid-se/blob/7e725e44a5accafc2fe3731ea3d6fec65ae3a6f1/app/src/foss/java/eu/darken/sdmse/common/updater/FossUpdateChecker.kt#L97-L119

Independent of the default setting, I agree though that it would be nicer to still delay this until after the onboarding.

**Comment by shuvashish76** [comment]
> Did you install SD Maid through F-Droid when you produced this bug?

Yes, Droidify's "Session installer" i.e. the installer app is Droidify. Network logs checked using [RDNS](https://f-droid.org/packages/com.celzero.bravedns/).

> Independent of the default setting, I agree though that it would be nicer to still delay this until after the onboarding.

Perfect 👍🏿

**Comment by d4rken** [comment]
> Yes, Droidify's "Session installer" i.e. the installer app is Droidify. 

What's the packagename of this?

**Comment by shuvashish76** [comment]
`com.looker.droidify` [Droid-ify](https://f-droid.org/packages/com.looker.droidify/)

**Comment by d4rken** [comment]
And the button state for the update check is disabled initially, right?

**Comment by d4rken** [comment]
I realized that the API call, could also have been the MOTD check instead of the update check.

That should be fixed with #1225
