### ISSUE TITLE
UI elements don't react (navigation does not happen)

### ISSUE THREAD

**Issue by Sentientpotato999** [d4rken-org/sdmaid-se#1218]
**Bug the describe**

On what I'm assuming is the main screen  ![Main](https://github.com/d4rken-org/sdmaid-se/raw/main/.assets/screenshots/1.png)
Multiple elements that should do something don't. The ⚙️ | 👁️<sup>not.in.devs.img</sup> | ⭐ | and on the dialogue after tapping the 🗑️ on whatever action (not the one on the bottom of the screen) the written option to view whatever it wants to eliminate. 
Does absolutely nothing 

**To Reproduce**
1. Go to (see .img ⤴️)
2. Click on '.stuff.'
3. Scroll down to '.the place with the stuff.'
4. Witness the nothingness 

**Expected behavior**
🦗🦗 nothing 🦗🦗

**Smartphone ():**
 - Device: [Sam's hung]
 - OS: [the 14th D-roid ]
 - Root status : pretend [shizuku[v13.5]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Da bugs log**
I'm on mobile and I don't feel like doing all that rn *will add when I get on l8r*

**Comment by d4rken** [comment]
So pressing any button that should take you to a new screen, does nothing?

I have seen this before, and from what I could tell, the buttons worked, but the navigation just didn't happen.

After restarting the app, it worked again, and I was not able to reproduce this.

Is this a permanent state for you or does it work again after restarting the app?

I need a way to reliably reproduce this to further investigate the issue.
