### ISSUE TITLE
After selecting option to clean App cleaner section it does not clean

### ISSUE THREAD

**Issue by Jostian** [d4rken-org/sdmaid-se#1219]
**Describe the bug**
After doing a scan of the app cleaner section it shows the amount that is available to delete, I select clean, it goes through the cleaning process and finishes but then still shows the option to delete and it still shows the same amount available to be deleted.

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: A14
 - Root status not rooted
 - SD Maid 2/SE version v1.0.1-rc0
![Screenshot_20240615-213316](https://github.com/d4rken-org/sdmaid-se/assets/32001018/5a31077b-4d33-4e68-ac7c-b62d3f66ed90)

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log and also check if the cache can be manually cleared.
6 apps, with only 53MB look like it may just not be deletable at the moment, common with system apps from Google.
