### ISSUE TITLE
After finishing ACS Schedule don't go always to homescreen

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#1240]
In addition to #1229:

It's not the best way, to go always to Homescreen after finishing the ACS Schedule, on AndroidTV this action closes the current running TV App (in my case waipu TV) and goes to the "waipu TV Home" App.
On Android 15 it close also the last running and "active" App. 

Is it not possible only try to force close SDMaid if it was not opend before the Scheduler run?

Version 1.1.1-beta0
AndroidTV 11, Android 15

**Comment by d4rken** [comment]
There is no direct way to just close SD Maid without root or shizuku.

The previous way of pressing back button stopped working in Android 14 or 15 in my tests, which is why I changed the method of closing the last app.

:thinking: not sure at the moment on how to further improve this.

**Comment by MarkyMarkDE** [comment]
Sorry but the current solution isn't good at all. 
Please bring back the old method with pressing the back button if it is available, if not we must find another way to handle it. 
With the current solution the user can lost data while sdmaid-se kills all and always go to home. 
Example: the user writes something like email or chat (he didn't save it) and sdmaid-se runs with schedule and ACS and after finishing, it closes all previous opend apps, the text from user before is lost.

**Comment by MarkyMarkDE** [comment]
Maybe I have an idea: if the user open SDMaid and starts any action, we have nothing to close, only the working overlay.

On scheduled ACS tasks we keep all in the background and show only the working overlay, so we stay without GUI in the background, we have not to close anything, except the own overlay.

On AndroidTV we can use always the old back button method, as we are on Android 11 here and I'm pretty sure, that this will work here further.

**Comment by MarkyMarkDE** [comment]
I have tested now from the current version down to 0.23.0 and all is great again. On all my devices the "push back" method do work perfect.

AndroidTV 11 Patches from April 5th 2024
Android 14 Patches from July 5th 2024

Conclusion:
0.23.0 works as expected
0.24.0 up to 1.0.0 has open SDMaid SE UI which wasn't opened by me (should background process only) 
>= 1.0.1 goes after finishing always to home screen and closes all previous opened apps

Please check 0.23.0 too and if you are able to confirm, bring back this method from 0.23.0, maybe you had if you tested it in past and bug in your testing system, so I hope 😉

**Comment by MarkyMarkDE** [comment]
Fixed on AndroidTV only?
I Android 24 the old method do also work well

**Comment by d4rken** [comment]
As far as I understood it:
The core issue was that SD Maid pressing the home button would close a previous app that was open. In my mind, this could be common on a TV (which may be always on), but doesn't seem common to me for a phone. Which phone is always on with an app that isn't the launcher?

In my tests it only needed 1 back press on Android TV, so it's reliable here and restoring the previous behavior has no downside, but for phones this is not the case.

I changed the behavior because the back button presses have two issues:

* On some ROMs, pressing the back button via accessibility service had no reaction (I think it was Android 14 or 15, not sure which manufacturer).
* The amount of "back presses" that are needed to just close the system windows is not the same for each ROM, so I would need to make this dynamic. So sometimes it was not enough back presses and sometimes too many.

Can you elaborate your Android 15 phone use-case further?

Why do you have an unlocked Android 15 phone with another application open when the scheduler trigers?

**Comment by MarkyMarkDE** [comment]
I have a Pixel 7 with the default launcher and version 0.23.0 works here perfect (Android 14 with July 24 patches).

If Android 15 really change anything for that case, we should find a better way as close really all opened apps and go to the home screen.
I will help so good I can.
When you need more details please come back to me.
For my case, you can also restore the push back method, it really works!

**Comment by MarkyMarkDE** [comment]
Sorry deutsch:

Auf AndroidTV immer push back Methode, darüber sind wir uns ja einig.

Auf anderen ROMs versuchen wir zuerst die Push back Methode und wenn die fehlschlägt, nutzen wir die go home Methode.
Wäre das akzeptabel und möglich?

**Comment by d4rken** [comment]
> Wäre das akzeptabel und möglich?

:thinking:  possible...

> Auf anderen ROMs versuchen wir zuerst die Push back Methode und wenn die fehlschlägt, nutzen wir die go home Methode.

This would solve the issue of "back button" not working, but leave issue of needing different (1-3?) back button presses depending on the ROM. This could be fixed though if I make this a configurable action depending on the ROM type :thinking: 

I will need to test this to see if the failed back button presses can be detected.

Can you make a new ticket? This would be an enhancement to the AppCleaner's ACS feature. To improve the reliabilitly.

**Comment by MarkyMarkDE** [comment]
Please do open the ticket by self, my English is bad and maybe misunderstanding, so it is better when you wording it, at least you must understand it 😉

**Comment by MarkyMarkDE** [comment]
Which rules we need, don't know.
I thought we find a relative "Simple" way.
No, always go home isn't the method what I thinking of 😉

**Comment by MarkyMarkDE** [comment]
Übrigens wird warum auch immer und von wem auch immer, das Rollout von AndroidTV 12 immer wieder verschoben.
Was der Grund dafür ist, weiß ich nicht, hoffentlich behalte ich mit der Vermutung Recht, dass Google sowas wichtiges nicht ersatzlos streicht. Bei waipu.tv gibt es ja noch die Besonderheit, dass es hier eine klassische Fernbedienung gibt, die natürlich weiterhin funktionieren muss.
