### ISSUE TITLE
System Cleaner scan results not showing when completed in background 

### ISSUE THREAD

**Issue by SlayCorpse** [d4rken-org/sdmaid-se#1247]
**Describe the bug**

The System Clean feature takes quite a while to finish, so SD maid isn't always in the foreground when the scan finishes. When it finishes in the background, there aren't any scan reports, and Id have to redo the whole scan again if I wanted some results. This problem is not only limited to "System Clean." The same thing happens with the other scan features as well.

**To Reproduce**

1) Start System Clean scan
2) Have SD Maid run in the background 
3) Re-open SD Maid when the scan is complete.

**Expected behavior**

1) Start System Clean scan
2) Have SD Maid run in the background 
3) Re-open SD Maid when the scan is complete.
4) View System Clean scan results and continue to select and delete unwanted items.

**Smartphone (please complete the following information):**

 - Device: Huawei P20 EML-L09 
 - OS: Android Q (10)
 - Root status: Not Rooted
 - SD Maid 2/SE version: 1.1.1-beta0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

-Battery optimization is turned OFF for SD Maid
-Option to have app run in the background is ON
-App management set to MANUAL
-Sufficient RAM was available during scan
![Screenshot_20240626_092449_com cointiply earn bitcoin](https://github.com/d4rken-org/sdmaid-se/assets/96850897/82efdbb0-b668-424c-b3fc-3041df5e960f)
[eu.darken.sdmse_logfile_1719416592313.zip](https://github.com/user-attachments/files/15992312/eu.darken.sdmse_logfile_1719416592313.zip)

**Comment by d4rken** [comment]
Not sure this can be fixed in a good way.

The background operations work via Androids `WorkManager` framework.
There are ROM specific limits to the background execution through the `WorkManager`.

According to the log, the system kills and restarts the worker every ~10min

```
2024-06-26T16:02:21.231Z  V/SDMSE:TaskManager:Worker: init(): workerId=520f1d19-f633-486f-9e86-672e0f9030b2
2024-06-26T16:02:21.237Z  V/SDMSE:TaskManager:Worker: Executing Data {} now (runAttemptCount=2)
(...)
2024-06-26T16:12:21.408Z  V/SDMSE:TaskManager:Worker: init(): workerId=520f1d19-f633-486f-9e86-672e0f9030b2
2024-06-26T16:12:21.415Z  V/SDMSE:TaskManager:Worker: Executing Data {} now (runAttemptCount=3)
```

I think the foreground mechanism may not be working correctly, let me look into it.
