### ISSUE TITLE
App clean-up not clearing cache from specific application

### ISSUE THREAD

**Issue by Archie400** [d4rken-org/sdmaid-se#1304]
**Describe the bug**
When running App Clean-up against the app OSMAND+ , sdmaid attempts to locate the "storage" word but fails to four times and returns with "cleared 0 mb"

**To Reproduce**
1. Go to App Cleaner and scan
2.when scan is complete, click on the delete button or the show detail
3a. If delete button, wait for it to get to osmand+ App
3b. If show detail, select osmand+ from the list and attempt delete
4. Either way, it scans the app details screen for "storage" but doesn't seem to locate it
5. The app cycles four times and gives up.
Note. This is whether I select samsung or automatic for os selection.

**Expected behavior**
The expectation is that app cleaner will clear the cache as with other apps.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A9+
 - OS: Android 14
 - Root status . No root
 - SD Maid 2/SE version v1.1.2-rc0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).
[eu.darken.sdmse_logfile_1720588136729.zip](https://github.com/user-attachments/files/16155494/eu.darken.sdmse_logfile_1720588136729.zip)

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
The app size lookup fails for some reason:

```java
2024-07-10T05:09:09.058Z  V/SDMSE:AppCleaner:Automation:OnTheFlyLabler: Miss for [3.63 GB, 3.6 GB] on [App info] from InstallId(pkgId=net.osmand.plus, userHandle=UserHandle2(handleId=0))
2024-07-10T05:09:10.876Z  E/SDMSE:AppCleaner:Automation:OnTheFlyLabler: Unexpected error when querying app size for net.osmand.plus: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutCoroutine.run(Unknown Source:28)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(Unknown Source:2)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:158)
	at kotlinx.coroutines.DefaultExecutor.run(Unknown Source:61)
	at java.lang.Thread.run(Thread.java:1012)
```

Because the system keeps saying `Computing…` for storage size.
Not sure why that is, but SD Maid shouldn't keep retrying this and then fail completely.
Will add better handling :+1:

**Comment by Archie400** [comment]
Matthias,

 

This app uses about 3.6gb of storage as it is a mapping application.  It looks like it’s taking a few seconds to actually add up all the storage the app is using (maybe 4-5 seconds).

 

Regardless, thank you for being able to pick up the problem from my error log.

 

It is consistently reproducible so, if there’s something to test, I certainly can do you reliably.

 

Thanks and regards

**Comment by d4rken** [comment]
This should work better in the next update. If it still does not work, re-open this ticket and add a new debug log.

Thanks for the report :+1:
