### ISSUE TITLE
Try to export sommes Apk

### ISSUE THREAD

**Issue by Stashimou** [d4rken-org/sdmaid-se#1315]
[Screenshot_2024-07-14-23-37-17-96_a65106d178f5bee05a749e7f17331c4b](https://github.com/user-attachments/assets/b843bcbe-289c-4b29-9ea6-ad9d4808eb62)
[Screenshot_2024-07-14-23-37-17-96_a65106d178f5bee05a749e7f17331c4b](https://github.com/user-attachments/assets/4d6f7be6-12eb-411e-ad7f-5e17b7d1842d)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide a debug log of this
