### ISSUE TITLE
Issue on external card

### ISSUE THREAD

**Issue by antoniolievano** [d4rken-org/sdmaid-se#1319]
**Describe the bug**
Hi, I'm having a strange crash with the app, for some reason, it's telling me that it can't find the '.android_secure' folder on my external storage, I checked the folder in my file explorer on my tablet "I use MiXplorer" and sure enough, my .android_secure folder is not found. The funny thing is that if I check the files in my storage on my computer, said folder will be present there. I only use ADB privileges through Shizuku.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy  Tab A 2017 (SM-T380)
 - OS: Android Pie 9
 - Root status: null
 - SD Maid 2/SE version: 1.1.2-rc0

**Debug log**
```eu.darken.sdmse.common.files.ReadException: Does not exist or can't be read <-> /storage/{miSDCard}/.android_secure```

**Comment by d4rken** [comment]
This will likely be fixed (as in it will cause an abort) in v1.2.0.

If you have the time, it would help me if you could provide a debug log of this.
