### ISSUE TITLE
Scheduler Info

### ISSUE THREAD

**Issue by HeyItsJono** [d4rken-org/sdmaid-se#1366]
Hi, thanks for the app! Just wanted to check; does the scheduler auto-delete as well, or just run the search for the relevant tasks and allow the user to manually review & delete later?

**Comment by MarkyMarkDE** [comment]
No, there is no option for and it is little out of the sense of the app 😉

**Comment by d4rken** [comment]
> manually review & delete later

This would not work well as results are only stored in memory. If there is no active task, then SD Maid loses priority and the system is likely to kill the process, so when you would open it later, it wouldn't show the results anymore.
