### ISSUE TITLE
Schedule Pixel5

### ISSUE THREAD

**Issue by gongfish** [d4rken-org/sdmaid-se#1370]
I have a default cleaning scheduled once a week for trash, system, applications. But when it happens in the morning I see that the application is not cleaned (red icon) and I have to clean it manually.
   

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide more details. This is not enough to act upon.

Note that the accessibility service does not work while the screen is off.

**Comment by gongfish** [comment]
This error only appears during scheduled cleaning.

**Comment by d4rken** [comment]
Sorry not enough info to act upon. You didn't even provide your ROM or SD Maid version :roll_eyes:

**Comment by gongfish** [comment]
Pixel 5 on android 14.
I have the latest version purchased SD Maid SE Pro

**Comment by gongfish** [comment]
Installed v1.2.3-rc0, yes it happens when the screen is off, during
scheduled cleaning
Best Regards
Gennady

чт, 22 авг. 2024 г., 18:38 Matthias Urhahn ***@***.***>:

**Comment by gongfish** [comment]
![Screenshot_20240824-091258](https://github.com/user-attachments/assets/47d51cc4-cfdc-47e6-b6c2-f057297c5f8b)
This is after the scheduled night check.

**Comment by gongfish** [comment]
![Screenshot_20240824-091811](https://github.com/user-attachments/assets/f3b20d31-4a8b-40f3-b0a6-951023c64aca)
This is after manual cleaning.
