### ISSUE TITLE
Still not able to find empty folders inside SD Card

### ISSUE THREAD

**Issue by SirNiklaas** [d4rken-org/sdmaid-se#1385]
It appears to still not be able to find any empty folders inside my SD Card just as mentioned in #1384. At least it's the case on my 256GB card. 

I tested it on your new GitHub build since it's not yet released in the Google Play Store. Only difference is my missing pro version but that shouldn't make any difference. 

The problem you found was about the cluster size right? Is it possible that your implemented 64kb size doesn't work with my 256GB card? That'd be my only idea so far. (Still not a programmer)

If it's any necessary I created a new log with the same example folders and settings as last time. 

[eu.darken.sdmse_logfile_1725642536030.zip](https://github.com/user-attachments/files/16911096/eu.darken.sdmse_logfile_1725642536030.zip)

And well much sorry for bringing it up again after your try to fix it..

**Comment by d4rken** [comment]
> And well much sorry for bringing it up again after your try to fix it..

Sorry for not fixing it with the last change 😇

**Comment by d4rken** [comment]
I set the limit too low, it was now 64KB and you have 256KB inode/block sizes. I'll remove the limit, not sure why I added it, does not seem that useful in hindsight.
