### ISSUE TITLE
"Pause app activity if unused" gets enabled upon cleaning

### ISSUE THREAD

**Issue by Nparte777** [d4rken-org/sdmaid-se#1396]
**Describe the bug**
App works fine but how do i control this explicitly : Pause app activity if unused gets enabled upon cleaning
I do not want this to be enabled (this causes delays in notifications etc)

Can this be controlled to not pause any apps ? 

**Expected behavior**
Activity should not be paused and should remain at default state of being disabled

**Smartphone (please complete the following information):**
 - Device: POCO F6
 - OS: Android 14
 - Root status : Unrooted
 - SD Maid 2/SE version : Google Play Release

**Comment by d4rken** [comment]
This is a visual artifact of your ROM. The setting does not get changed by SD Maid, the system just takes a moment to update the button it's actual state.

**Comment by Nparte777** [comment]
> This is a visual artifact of your ROM. The setting does not get changed by SD Maid, the system just takes a moment to update the button it's actual state.

so is this because the settings app cache is also being cleared ? and you are saying if i check again it should go back to disabled ?

**Comment by d4rken** [comment]
No I'm saying that SD Maid is not changing the setting. It just looks like it.
