### ISSUE TITLE
App cleaner not working

### ISSUE THREAD

**Issue by weird-budy** [d4rken-org/sdmaid-se#1407]
![Screenshot_20240918_191823_SD Maid SE](https://github.com/user-attachments/assets/9dc525c2-8c78-43c1-afd1-ef3d3ca415d3)

**Describe the bug**
The app cleaner is not working. I have the latest version of the app. When i scane for app cleaner it shows me a error on the screenshot

**To Reproduce**
1. Click on 'scan ' on app cleaner
2.See error

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy
 - OS: android 13
 - SD Maid 2/SE version : 1.2.6-rcO

**Additional context**
It happens with or without shizuku. No root access

**Comment by MarkyMarkDE** [comment]
Do the previous version of SD-Maid SE work?

**Comment by weird-budy** [comment]
The previous version was working fine. 
So i found another person on discord with same problem. He told me to stop and restart shizuku. Now it's working fine with or without shizuku.How? No idea🤷‍♂️ 
I'm not getting any error anymore so can't provide debug log.

**Comment by d4rken** [comment]
My suspicion is that Shizuku doesn't like too frequent launches and re-launches of the processe that does the file operations.

#1417 reduces the amount of relaunches by increasing the timeout when the processes are not used.

Let me know if it still happens after the next update.
