### ISSUE TITLE
Feature request: Move Apps from internal to external RAM

### ISSUE THREAD

**Issue by Meridies76** [d4rken-org/sdmaid-se#1419]
Hi,
on phones with SD slots, some apps can be moved to external (SD) RAM to save internal RAM. This is not permanent. After updating the apps, they are stored in internal RAM again. You must move them to SD manually again. It would be very nice if SD Maid could to this, too. 
Thanks,
Stef

**Comment by d4rken** [comment]
You probably mean "storage", not RAM.

I tried this feature in SD Maid 1 and it generally didn't work well across different phone types. I have no plans to attempt this again in SD Maid 2.
