### ISSUE TITLE
Access account se maid pro on second device

### ISSUE THREAD

**Issue by Laroba12** [d4rken-org/sdmaid-se#1422]
Salve, non riesco ad effettuare l'accesso al profilo pro, dopo aver pagato la quota "una tantum", sul mio secondo dispositivo!
Ho seguito tutte le indicazioni: riavviare, cancellare la cache... Tutto, ma ancora non funziona!
Potreste aiutarmi?

**Comment by Laroba12** [comment]
Hi, I can't log in to the pro profile, after paying the "one time" fee, on my second device!
I followed all the instructions: reboot, clear cache... Everything, but it still doesn't work!
Could you help me?

**Comment by Laroba12** [comment]
> We need more information to help you, both devices use the same email address or two different addresses? Who did you pay? On the Playstore or on github? You always have to pay twice, so I know.

Thank you very much for your reply!
The payment was made on the SD maid PRO app (it was handled by Google, so I think it was done through the PlayStore) of my Samsung Tab S9 FE. It was used the same account that I also use on my Samsung Galaxy a70! However, I can't "redeem" the pro version even on my Samsung galaxy a70.
If you need any other necessary information, just ask! Unfortunately I'm not very expert!

**Comment by MeloriTensei** [comment]
> > We need more information to help you, both devices use the same email address or two different addresses? Who did you pay? On the Playstore or on github? You always have to pay twice, so I know.
> 
> Thank you very much for your reply! The payment was made on the SD maid PRO app (it was handled by Google, so I think it was done through the PlayStore) of my Samsung Tab S9 FE. It was used the same account that I also use on my Samsung Galaxy a70! However, I can't "redeem" the pro version even on my Samsung galaxy a70. If you need any other necessary information, just ask! Unfortunately I'm not very expert! Why do you say that "you always have to pay twice"? Isn't it enough to pay just once?

If you're referring to the SD Maid 1 Pro Unlocker App, please understand that SD Maid 1 and SD Maid 2/SE are two separate apps catering to two different ranges of Android versions.

**Comment by Laroba12** [comment]
The app in question is sd MAIN 2/se pro - Currently it seems to me that the registration for the pro program has also been successful on the second device. All I had to do was clear the Play Store cache a second time. I thank everyone for helping me!
