### ISSUE TITLE
Remove network permission for F-Droid build

### ISSUE THREAD

**Issue by tvnmguy** [d4rken-org/sdmaid-se#1428]
According to your privacy policy; 

Network permission are used mainly for checking new update and message of the day (MOTD) feature.

I believe MOTD is a fancy feature and that's not need necessary for this kinda app.

If I installed SDmaide SE from F-Droid and updating via F-Droid, so in that scenario F-Droid version no longer need internet permission. 

I'm not comfortable with an app that has full network access which handle all system files.

In my view, all version of this app no longer need network permission because:

If someone installed via direct github release who can track and update this app via https://github.com/ImranR98/Obtainium

**Comment by d4rken** [comment]
I'd be open to making the internet permission "optional" and granted at run-time (if a feature is used that requires it), but that is not supported by Android (as of now).

While you are right that in some cases like installing from F-Droid, the update check is not needed, there are also uses who grab releases directly from GitHub without any 3rd party app inbetween.

> I'm not comfortable with an app that has full network access which handle all system files.

SD Maid is fully open-source, feel free to check the source-code. If you don't trust the me, maybe you shouldn't use the app, there are ways to exfiltrate data even without internet permission. :shrug: 

Both the update check and MOTD are features I want to have in the app, so the internet permission has to stay (for now) :slightly_frowning_face:. Maybe a future Android version allows making it optional, then we could revisit this topic.
