### ISSUE TITLE
Please add the ability to manually enter the file size for "Minimum Size" in the Deduplicator menu.

### ISSUE THREAD

**Issue by GitGoodBhaskar** [d4rken-org/sdmaid-se#1438]
**Is your feature request related to a problem? Please describe.**
It is extremely annoying and difficult to set a minimum size less than 100kb. We should go back to how it was in the original SD Maid. It was easy and quick. I don't have to struggle to get an exact size with the slider.

**Describe the solution you'd like**
Implement an option to manually enter the minimum size like in the original SD Maid.

**Describe alternatives you've considered**
The original SD maid has the ability to manually enter the minimum file size for duplicates. Please add this option. 

**Describe why this would be in the interest of all users**
It makes the user experience much more pleasant and extremely less annoying.

**Additional context**

This is what we have now:

[Screenshot_2024_1023_071420.jpg](https://github.com/user-attachments/assets/de781100-3e5a-4a9b-a576-e206b35a65b9)

It would be better if we can add a minimum size manually. Like this:

[Screenshot_2024_1023_071619.jpg](https://github.com/user-attachments/assets/e26916b8-a844-4992-a8d9-98d59775eb2b)

**Comment by d4rken** [comment]
With the next update you can type in values manually too, e.g. `69KB`.
