### ISSUE TITLE
File Path Inclusion

### ISSUE THREAD

**Issue by Runite-Rain** [d4rken-org/sdmaid-se#1440]
**Is your feature request related to a problem? Please describe.**

There is currently only file Path _Exclusions._ I would like the option to _include_ certain file paths. This would be useful for hidden files or folders, especially for the Deduplicator Tool.

**Describe the solution you'd like**

Create File Path Inclusion option within the same menu as the File Path Exclusion.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

Currently there isn't an option to include a file Path that I can see. This feature would help those of us with hidden folders, hidden file paths, .nomedia files, etc. without having to move entire folders to visible sections of our file managers. This would be useful to those who are privacy focus or have a lot of unrelated items that we do not want popping up in the media picker menus on other apps, while wanting a convenient way to identify and delete duplicate files, especially videos, gifs, and screenshots.

**Comment by d4rken** [comment]
I agree that this would be useful. On my TODO list :coffee:.
Closing this ticket and linking yours to it as the other one is older :pray: .

Dup, see #823
