### ISSUE TITLE
Scheduled cleaning issue with Time

### ISSUE THREAD

**Issue by nightznero** [d4rken-org/sdmaid-se#1441]
Helloz,

Yesterday was changing time zone.I have setted up everyday cleaning for 18:00(6pm) but after changing time its changed into 17:00(5pm). I know that changing time zone is not a big deal bcs its a twice a year but i guess its may causing more issues with changing Time
A13,OneUI 5.1,sdm-v1.2.8
Best Regards, NIGHTZNERO.

**Comment by nightznero** [comment]
Heres screen with mentioned that sheduled is set up to 18 but was today at 17 and will continually going on 17 o.O
![Screenshot_20241027_184856_SD Maid SE](https://github.com/user-attachments/assets/ae219ce0-a775-432b-ab44-1d5e7e6b63a5)

**Comment by d4rken** [comment]
Unfortunatenly a known issue with winter/summer time zone change. Have not gotten to fixing that yet, sorry.

Closing dupe in favor of #768
