### ISSUE TITLE
About data directory access problem

### ISSUE THREAD

**Issue by ChumoerZeno** [d4rken-org/sdmaid-se#1444]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

> I consulted the relevant knowledge literature and found the Kio Universal Access File(https://github.com/limao996/Kio)

**Describe the solution you'd like**

> I hope you can check out https://github.com/limao996/Kio to make changes to your code. I successfully accessed the data directory with an Android 11 phone.

**Comment by d4rken** [comment]
Thanks, cool looking library, but I'm not sure what problem this would solve in SD Maid. SD Maid can already access `Android/data` if permission is given.

Can you elaborate?
