### ISSUE TITLE
Need edit association with files programm 

### ISSUE THREAD

**Issue by userkilled** [d4rken-org/sdmaid-se#1446]
![Screenshot_20241103-171018](https://github.com/user-attachments/assets/79e0f44c-c3dc-4adf-bd44-d39299c6ba3d)
![Screenshot_20241103-171040](https://github.com/user-attachments/assets/db1df126-772d-4fe1-86a0-00304726bc59)

Need edit association with files app.

folder tree/tencent this folder for app com.tencent.android.qqdownloader 
应用宝

**Comment by d4rken** [comment]
The `sdcard/tencent` folder is shared by multiple apps from tencent though. Each app using a different subfolder. Attributing the top-level `tencent` folder to a single app will cause problems with the CorpseFinder. 🤔

I will add an additional mapping to the clutter_db and see how that works.

Currently there is a fixed marker just for this app:

https://github.com/d4rken-org/sdmaid-se/blob/63f99877a93cfdee4683e2267857d4a799c93cc6/app/src/main/assets/clutter/db_clutter_markers.json#L890-L891

and a general marker for all tencent apps: 

https://github.com/d4rken-org/sdmaid-se/blob/63f99877a93cfdee4683e2267857d4a799c93cc6/app/src/main/assets/clutter/db_clutter_markers.json#L9768-L9775

☝️  this should map the `sdcard/tencent` folder already to the `com.tencent.android.qqdownloader` 🤔

**Comment by userkilled** [comment]
App not add this folder another app tencent
![Screenshot_20241103-204538](https://github.com/user-attachments/assets/793ec8b7-5c98-46d9-a332-5efa48a03db1)
Parser look qqmusic first, size 400mb, qqdownloader 85mb... 😅

**Comment by d4rken** [comment]
There is currently no logic to handle overlapping matches for folder ownership. I think it just uses the first match it gets. What logic could we use to solve this 🤔

**Comment by d4rken** [comment]
I've given the `tassistant` folder specificly to the qqdownloader app, see #1510 

The issue with multiple apps owning the same folder is something I need to look separately at.
