### ISSUE TITLE
Опечатка 

### ISSUE THREAD

**Issue by Serega37Rus** [d4rken-org/sdmaid-se#1463]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
Add any other context about the problem here
![Screenshot_2024-11-12-14-57-51-099_eu darken sdmse-edit](https://github.com/user-attachments/assets/27d4e5ee-d8c7-4061-b73c-c94357ab876b)
 Буква "t" лишняя, уберите пожалуйста.

**Comment by d4rken** [comment]
Thank you for the report :heart: 

Unfortunatenly, I can't read the language, so I don't know whether this is a typo.
Translations are by other community members.
Please either edit the translation yourself, or ping a proofreader if someone has marked this as "correct".

https://crowdin.com/project/sdmaid-se/ru
