### ISSUE TITLE
"WriteException" pop up error after I press the clean option

### ISSUE THREAD

**Issue by cranky-pythonista** [d4rken-org/sdmaid-se#148]
[Screenshot_20230411-201400](https://user-images.githubusercontent.com/88152489/231201444-2f8964f3-bf34-4c08-89e8-74d9f0702632.png)
Please suggest what to do. 

Note - The cleaner works afterwards as its supposed to, regardless of this error. It simply shoes up once every time I press the clean button after scanning is finished.

**Comment by d4rken** [comment]
Please wait until the update and if the issue still happens, record a debug log of it:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs

**Comment by d4rken** [comment]
I think this is fixed, please try the latest versions, if this persists, reopen :)
