### ISSUE TITLE
Backup and Restore (Export/Import settings/custom-filters to local storage)

### ISSUE THREAD

**Issue by User1l0** [d4rken-org/sdmaid-se#1480]
I'm just begging you, please make SDMaid able to backup and restore it's state (if possible, then later also with the custom filters included in the export file.

SDMaid really should have ability to backup and restore all it's settings filters etc.
It's really important feature for SDMaid to have, because It's so painful and time consuming trying every time to completely set-up SD Maid. There's schedules, different cleaner settings (even with custom filters) etc. To adjust.

**Comment by NurMiApp** [comment]
I'm sorry Matthias was bad. We are going back SD Maid the triage feature request where is it located.

Regards, the Nurkhametov Mike.

**Comment by d4rken** [comment]
Please add ideas and use-cases related to backup/restore of settings here: #1480

The feature is planned, it just requires some more thought.
