### ISSUE TITLE
AppCleaner|MinimumSize scrollbar overweighted, no keypad invoked

### ISSUE THREAD

**Issue by Eternal9100** [d4rken-org/sdmaid-se#1484]
**Describe the bug**

The slider in the minimum cache size of appcleaner settings is overweighted and impossible to control. Value range not credible (Max size 105MB)

**To Reproduce**
Steps to reproduce the behaviour:

From home sheet: settings wheel | AppCleaner | Minimum Size. Select slider to adjust cache size.

**Expected behaviour**

Lew weighting or credible values selectable in slider and ability to adjust in Kb range or keypad invoked on selection of cache size value

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: A10.
 - Root status: Not rooted, completely stock
 - SD Maid 2/SE version: SE v1.2.8-rc0 play store

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

N/A

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

If required

**Comment by d4rken** [comment]
I changed it so values can be typed in manually to. See #1492

Next update :coffee:

**Comment by d4rken** [comment]
The values should be editable manually with the keyboard. Note that this only works well with English at the moment. After 1.3.3 it should work better in other languages too.

I'm still looking into better slider behavior but that part is a bit tricky (or I have not fully grasped it yet) :coffee:

**Comment by d4rken** [comment]
1.3.2 is available on F-Droid and in staged roll-out on Google Play:
https://github.com/d4rken-org/sdmaid-se/releases/tag/v1.3.2-rc0
