### ISSUE TITLE
Add option to display the start-up apps and allow disabling them in a simple way

### ISSUE THREAD

**Issue by M7amma** [d4rken-org/sdmaid-se#1487]
**Is your feature request related to a problem? Please describe.**
No problems so far. 

**Describe the solution you'd like**
Is disabling startup apps still a thing in A14 and 15? I'm aware there's that way to go for the app list and disable the flag : boot complete to stop those specific apps from running after boot. But this is complex way to do a simple task and I'm not sure if it's affective or not.

> I would like it if SD Maid could make me coffee in the morning.
No thanks.

**Describe alternatives you've considered**
No alternative because I know SDMaid is the best to do such job. 

> I have considered making the coffee myself but both me and myself decided against it.
Aha ok.

**Describe why this would be in the interest of all users**
Because every geek like us would know about those rats that crawl up and hog the ram after every single boot.

> Everyone enjoys getting a hot beverage on a cold morning.
I agree. 

**Additional context**
Please make it simple and clean menu so we can look at this auto run app list after every while to see and disable those new rats.

**Comment by d4rken** [comment]
I'm against this feature. The way I designed it in SD Maid 1 was one of my bigger mistakes.

> Is disabling startup apps still a thing in A14 and 15? I'm aware there's that way to go for the app list and disable the flag : boot complete to stop those specific apps from running after boot. But this is complex way to do a simple task and I'm not sure if it's affective or not.

The core issue is that this was "almost never" a thing. It does not fully stop an app or prevent it from starting, and what happens at boot is not the same as what happens in windows when programs "autostart". There were only very few cases where this was the right solution.

Please see:
https://github.com/d4rken-org/sdmaid/wiki/AppControl#receiver-manager-autostart

Sorry.

**Comment by M7amma** [comment]
like really
