### ISSUE TITLE
Add app to Accrescent

### ISSUE THREAD

**Issue by tegridyfarmer** [d4rken-org/sdmaid-se#1493]
## Problem Statement

[Accrescent](https://accrescent.app/) addresses certain security issues that F-Droid has.
But the Android app is currently not available on Accrescent.

## :grey_question: Possible Solution

The app to be available on Accrescent .
[Here](https://accrescent.app/faq#app-submission) you can find more information on submitting an app on Accrescent.

## :arrow_heading_up: Describe alternatives you've considered

Using the Google Play Store, yet this provides its own issues: privacy issues.

## :heavy_plus_sign: Why this benefits a big amount of users

Mostly privacy and security focused people use SDmaid.
They mostly likely would want to use a secure and private app for downloading en updating applications.

**Comment by d4rken** [comment]
This is currently out of scope.

* Accrescent is still in early alpha
* Submission is a manual process. I would have to build and upload APKs manually and pass reviews.
* Their publishing requirements also state:
    * > [android.accessibilityservice.AccessibilityService](https://accrescent.app/docs/guide/appendix/requirements.html#androidaccessibilityserviceaccessibilityservice)
Accessibility services are highly invasive, presenting a security and privacy risk to users. As such, they are heavily restricted on Accrescent and may only be used to help users with disabilities interact with the device.
    * Which would be problematic as SD Maid makes heavy use of this. Creating another build variant that removes it also a lot of work.

I want to keep development overhead low, additional app stores need to be low overhead and reach larger audiences. I think there is a lot of overlap between F-Droid users and Accrescent users making it not worth the extra work at the moment.

We can revisit this in the future once it's no longer an "early alpha".
