### ISSUE TITLE
Skirt color blend background

### ISSUE THREAD

**Issue by nightznero** [d4rken-org/sdmaid-se#1495]
Helloz,
I would like to suggest to change color of Maid skirt,it's blends with background and looks weird.
Maybe some border/frame?
![Screenshot_20241208_142755_Settings](https://github.com/user-attachments/assets/b40ca2ca-d3f6-4b86-8595-c49b03301577)
Best Regards, NIGHTZNERO.

**Comment by MarkyMarkDE** [comment]
This is a default look for progress overlay 🤷

**Comment by nightznero** [comment]
> This is a default look for progress overlay 🤷

The question is..do i even mentioned the overlay?🤔 Because i speak about skirt of Maid.
Background or as u called that "overlay" can be fully transparent or blacked out like doing that app e.x `KillApps` or `Hibernator`.
This us smoll cosmetic change that just looks weird for me that the obly head and limbs are visible 😵‍💫
