### ISSUE TITLE
Remove screenshots older than X timeframe

### ISSUE THREAD

**Issue by glidingthrough** [d4rken-org/sdmaid-se#1498]
**Describe the solution you'd like**
Totally not sure if this is possible, but thought I'd suggest the idea anyway.

Would it be possible to set a limit on how long call logs, SMS messages and screenshots are kept for?

It'd be great if, for example, there was a function in SD Maid SE to keep call logs for the last 2 weeks only (all older call records are deleted), SMS for 1 month and screenshots for a day. And each of those timeframes is set by the user, so the 2 weeks for calls logs could be changed to X day(s) / Y week(s) / Z month(s), as per the user's desire.

**Describe alternatives you've considered**
Currently all this has be managed manually.

I clear my call logs every month, but a deletion of the full history means that I have the inconvenience of having to look up friends and family in Contacts again. I delete old SMS every now and then, too, especially because if my phone were stolen they'd give away important information - e.g. what banks I use. And I'm not that organised that I stay on top of screenshots, but most are redundant after first use, anyway, so I probably should go in and delete them.

**Describe why this would be in the interest of all users**
As someone who likes to keep my digital life fairly neat and tidy - and I'd imagine most SD Maid SE users do, too - these features would be great to have. There are also privacy gains from implementing this.

**Comment by d4rken** [comment]
Screenshots might a viable feature. Call logs and SMS opens a whole can of worms with Google and with how Google shots first and asks questions later, is likely a too risky permission request to add.

**Comment by glidingthrough** [comment]
I'll take what I can get :smile:

Appreciate you considering my feature requests in earnest and am very grateful for the app you've created. It really is excellent.
