### ISSUE TITLE
AppCleaner error when handling caches from the same app for multiple users

### ISSUE THREAD

**Issue by djocqer** [d4rken-org/sdmaid-se#163]
**Describe the bug**
Error - IllegalArgumentException during Apps Cleaning 

**To Reproduce**
1. Go to 'Clean All'
2. After finished click on 'Delete on AppCleaner' section. 
Error - IllegalArgumentException

**Expected behavior**
No error at all.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Pocophone F1
 - OS: Android 11
 - Root status Rooted - Magisk Alpha v.25211
 - SD Maid 2/SE version [e.g. v0.7.2-rc0]

**Debug log**
[Log](https://drive.google.com/file/d/1W56EVDtUZadm4YQQwmc4dv-Ycf97ByAP/view?usp=drivesdk) 

**Screenshots/Video**
[Screenshot_20230412-234259_SD_Maid_SE](https://user-images.githubusercontent.com/35299809/231529125-8b9b3ac3-0219-4f5c-87c4-87fe4b06444b.png)

**Comment by d4rken** [comment]
Ok, I can reproduce it. Related to the improved multi-user support from the previous updates.

On rooted device multiple apps (from different users) can be listed now in AppControl.

Should we just show the current-user? :thinking: and to clean other users you have to switch to that account? :thinking:

**Comment by d4rken** [comment]
I think we can allow for multi user handling on rooted device, but I'll also add a setting to enable/disable this.

Should multi-user handling be opt-out, or opt-in? :thinking:

**Comment by djocqer** [comment]
> I think we can allow for multi user handling on rooted device, but I'll also add a setting to enable/disable this.
> 
> Should multi-user handling be opt-out, or opt-in? 🤔

I suggest it should be opt-in feature 👌. Btw if I'm using SD Maid SE from Playstore do I keep my subscription if I'm updating from github?
