### ISSUE TITLE
Error when trying to send the debug log.

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#164]
После создания debug log нажимаю "share", появляется ошибка
![Screenshot_2023-04-13-09-24-04-802_eu darken sdmse](https://user-images.githubusercontent.com/60130882/231674019-12c13ae8-870f-4a42-a1d5-6e728ec96616.jpg)

Как я понял это как-то связано с тем что лог теперь сохраняется в папку Android/data...... - #102

**Comment by d4rken** [comment]
This should be fixed by #155 in 0.7.2, can you check?
https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.7.2-beta0

**Comment by Ingood5** [comment]
В 0.7.2 проблема решена.
