### ISSUE TITLE
Higher Donation Tier

### ISSUE THREAD

**Issue by AndrewChqng** [d4rken-org/sdmaid-se#168]
Hi, this is short of a weird request but could you make a £9 tier even if temporary?
I have an offer from Google for £2 of purchases over £9 and want to utilise it properly and help donate to a great developer!
I've used the og sdmaid for many years ago can't wait to see how this new version develops :D

**Comment by d4rken** [comment]
Something like the coffee/pizza IAP in SD Maid 1? :thinking:

**Comment by AndrewChqng** [comment]
Oooo yeah didn't notice that I'll donate through there it's perfect! It'll come to you anyway so all good 😁
