### ISSUE TITLE
Animated maid drinking coffee 

### ISSUE THREAD

**Issue by Helpful-Neko** [d4rken-org/sdmaid-se#173]
**Is your feature request related to a problem? Please describe.**

> I've just recently purchased your app (Older version) and I'm planning on purchasing your newer version but I noticed something. There's no adorable Android maid drinking coffee when I do tasks with the newer version 😿

**Describe the solution you'd like**

>Do you think you'd be able to add the animation of the maid drinking coffee again like in the old version? I do love the layout of the new app despite missing the maid animation. 

**Describe alternatives you've considered**

>Nothing can be done on my end sadly. 

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys seeing the cute Android drink coffee! If they don't they're just grumpy people who need their morning coffee 

**Additional context**

I'll add a image 
[Screenshot_20230414-041037-694](https://user-images.githubusercontent.com/126541816/231984805-b9c094ce-757e-4e2d-a7eb-8f05c6cace84.png)
The adorable animation I miss in the newer version. 

I understand this is probably a silly enhancement for me to mention but I just wanted to throw it out there 😹

If you do get back to me I appreciate your time and for making this amazing app! 😸

**Comment by Helpful-Neko** [comment]
> I'd have to commission that too, my design skills are not that good 😉
> 
> I think it was a bit contentious in SD Maid 1, got a lot of requests asking for an option to disable animations. Personally I liked it.
> 
> In SD Maid 1 it was a .gif which wasn't great, for SD Maid 2 we should get a vector animation, and use [Lottie](https://airbnb.design/lottie/) for the animation.

Mine aren't the greatest either 😹 

I'm not sure why they'd be upset at a happy android maid drinking coffee lol. I thought the ability to disable it in SD Maid 1 was nice but I personally love it to much it's adorable
 
I'm guessing Lottie would be smoother.

Also you're awesome thank you so much for getting back with me!😸

**Comment by catgangdev** [comment]
> I'd have to commission that too, my design skills are not that good 😉
> 
> I think it was a bit contentious in SD Maid 1, got a lot of requests asking for an option to disable animations. Personally I liked it.
> 
> In SD Maid 1 it was a .gif which wasn't great, for SD Maid 2 we should get a vector animation, and use [Lottie](https://airbnb.design/lottie/) for the animation.

Yeah I like that animation too. I hope you will add that in sdmaid SE. It's fun to watch while app doing there cleaning work,😁
