### ISSUE TITLE
Can't Whatsapp Videos download 

### ISSUE THREAD

**Issue by remon06** [d4rken-org/sdmaid-se#186]
After using all the three cleaner I am facing a problem that I can't download video from WhatsApp anymore.

**Comment by d4rken** [comment]
Please provide more infos about your setup.

Pictures still work though? Only videos not?
Have you rebooted/restartet WhatsApp?

**Comment by remon06** [comment]
Oppo Reno2z
Running on Android 11
And yes I have rebooted whatsapp and also my phone

**Comment by remon06** [comment]
And while watching YouTube videos the video stops after watching it for sometime

**Comment by d4rken** [comment]
This sounds sounds more like bad internet.

> And while watching YouTube videos the video stops after watching it for sometime

This can't be caused by SD Maid.

**Comment by remon06** [comment]
No it's not bad internet idk what happened anyway I'm reseting it

**Comment by remon06** [comment]
I'm reseting my phone
