### ISSUE TITLE
Support MDY

### ISSUE THREAD

**Issue by T8RIN** [d4rken-org/sdmaid-se#187]
It would be cool,  if the fabs would be changed according to material 3 design... Only if you seem it useful of course, and have you planned to add material you implementation?

**Comment by d4rken** [comment]
Can you give me an example of what you are looking for?

**Comment by T8RIN** [comment]
Like this
 ![Screenshot_20230415-133929_Image Resizer.png](https://user-images.githubusercontent.com/52178347/232209053-6cd5f9ce-a52b-47d6-82ef-fd22523e545f.png)

You can also find examples on m3.material.io 👀

**Comment by d4rken** [comment]
Ah okay, thanks for the example. It's a nice idea, but currently not a huge priority.
Closing this ticket as duplicate in favor of #50

**Comment by T8RIN** [comment]
Thanks!
