### ISSUE TITLE
"Filter by tags" in AppControl list stuck in infinite loop

### ISSUE THREAD

**Issue by gallegonovato** [d4rken-org/sdmaid-se#189]
Good afternoon:

As it turns out, I get a comment from a co-worker. That on his device a Samsung A30s. When he goes to the AppControl option , and selects among the various options that come up at the beginning. Sometimes it keeps flashing and doing like a loop between options.  That is to say it activates and illuminates one and then the other. So on and on.

And after that you can not choose or check all the options: User, System, On and Off. 

If you check User, the system ones are deactivated.

I don't know if it would be possible to activate all of them in a new version. 

I also wonder if in the future it will be possible to do it like in the old SD Maid. That is: Freeze, stop, force stop, delete, export the apk, and manage the receivers (removing that boot with the system), etc...

Thanks for your time and help

**Comment by d4rken** [comment]
Do you know which SD Maid version this is on, and if there is a specific sequence of taps that reproduce it every time?

> I also wonder if in the future it will be possible to do it like in the old SD Maid. That is: Freeze, stop, force stop, delete, export the apk

Likely

> export the apk

Not sure about that yet as I can't add install functionality, Google won't grant me permission, so is uninstall without install worth it?

> and manage the receivers (removing that boot with the system), etc...

Maybe in a very general sense, but not as a "boot" specific feature, I very much regret adding that to SD Maid 1, it's just not what people think it does:
https://github.com/d4rken-org/sdmaid/wiki/AppControl#receiver-manager-autostart

**Comment by gallegonovato** [comment]
Good afternoon:

Thank you very much for your help and time.

From Sd Maid 1 use it last, the 5.5.9 with the pro unlocker from the play store. 

And from Sd Maid 2 use 0.7.3 beta 0.

Which I think uses Android 11. It keeps flashing either the first option and the last one. Others the third and last.  The screenshots do not show this intermittency. But the truth is that it does happen.

If in the future you can freeze, stop and others; and the other options that can be done with the old Sd Maid would be wonderful and a point more than extra for the new version. 

For the functions to remove from boot, freeze and so on. I use them a lot. And they are a marvel, as it says in the link you give me. For me, it was the best thing that could have been added. Since it makes very different and superior to other applications. And it makes you save on having extra applications. Since you have everything in one.

A hug

**Comment by gallegonovato** [comment]
Good afternoon @d4rken

Thank you very much for your help and time. 

Then I will tell you to wait for a new version?

What you are looking forward to use the final version.

And a question you ask me. Do you recommend him to remove Sd Maid 1 and leave only Sd Maid 2? In the first version you have some applications stopped. (He uses the root version with super user permission in Magisk) according to what he told me. 

Best regards
