### ISSUE TITLE
Duplicate data detection

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#2]
Should a feature similar to SD Maid 1's "Duplicates" feature should be re-added?

According to stats I had before I [removed analytics](https://github.com/d4rken-org/sdmaid/issues/5677), `Duplicates` was not a very popular feature.

It's still a good way to gain additional storage space, but has some issues:

* There is no one "right" way to select duplicates which makes it more difficult to use.
* Storage is super convoluted in Android and one of the toughest points was making sure that SD Maid didn't scan the same storage twice, just via different paths. This has NOT gotten easier with newer Android versions.
* A lot of users expect a feature like this to detect "similar" images, e.g.  a high res photo in your `DCIM` folder and a low res variant generated by a messenger. This is vastly more complex than comparing checksums to find exact matches.

**Comment by BROKEN81** [comment]
It would be nice, however, if it's not a popular feature, then no use to create more work for yourself. 
I think it comes down to most people like familiarity.

**Comment by tathastu871** [comment]
I use termux app with fdupes -Nrd option to remove duplicates.
Maybe fdupes can be compiled into sdmaid

**Comment by tathastu871** [comment]
@d4rken  If possible try adding fdupes utility for removing duplicates. Simple fdupes  -Nrd will work without user intervrmyion.
Howvert it must be users responsivility to use duplicte removal as there is no guarantee it will not remove some imp ile
