### ISSUE TITLE
Specific filters for the app Viber

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#204]
DEEPL (by darken):
Here is a list of folders that are desirable to clean to save space.
Since the application is popular, I think that for some folders it is suitable to create specific filters in AppCleaner (in the window where there are separate filters for Telegram, WhatsApp, Threema, WeChat), so that the deletion does not happen immediately, but after a certain number of days. Or just so that the user has a choice to clear the folder or not, as some users will want to clear some folders, others will want to keep them.

`/storage/emulated/0/Android/data/com.viber.voip/files/.converted_videos` - when sending a large size video, it is compressed, this folder stores compressed copies, which are automatically deleted after about 10 days. After the folder is cleared, the video continues to play in the chat as the original video from the gallery is played. The user may want to clear the folder sooner, as sending a large number of videos can take up a lot of space in the folder. If you clear the folder before the contact is online, the videos will still be successfully delivered (stored on the server).

`/storage/emulated/0/Android/data/com.viber.voip/files/.import `- any types of files sent to Viber from other apps using the "share" item. Not deleted over time. Gradually the folder may grow to a large size. If the folder is cleared, I no longer have access to the sent files in chat, even if the files are still on the device. If you clear the folder before the contact is online, the videos are still successfully delivered.

`/storage/emulated/0/Android/data/com.viber.voip/files/.image` - received photos are saved here. If you save a photo in the chat, it is moved from this folder to the gallery; if you do not save it, it stays in the folder forever, it will not be deleted over time. If the folder is cleared, when you view the photo in the chat, it is loaded into it again.

`/storage/emulated/0/Android/data/com.viber.voip/files/.video` - received videos are saved here. If you save the video in the chat, it is moved from this folder to the gallery; if not saved, it stays in the folder forever, it is not deleted over time. Gradually, the folder can grow to a larger size. If you clear it, when you view it in chat, the video is loaded again.

`/storage/emulated/0/Android/data/com.viber.voip/files/.gif `- incoming gifs. If you save them to the gallery, they are moved from this folder to the gallery. If you clear the folder, when you click in the chat on the gif, it is downloaded again to the folder from the server. They are not deleted over time.

`/storage/emulated/0/Android/data/com.viber.voip/files/.ptt` - incoming and outgoing voice messages. Over time, they themselves are not deleted. If you clear the folder, only messages sent to me are downloaded from the server again (messages that I sent me are not downloaded).

`/storage/emulated/0/Android/data/com.viber.voip/files/.vptt` - incoming and outgoing video messages recorded by the built-in Viber function (video messages in a circle). Over time, they themselves are not deleted. If you clear the folder, only sent messages are downloaded from the server again

> Здесь список папок, которые желательно очищать для экономии места.
> Так как приложение популярное, я думаю что для некоторых папок подходит создать специфичные фильтры в AppCleaner (в окне, где находятся отдельные фильтры для Telegram, WhatsApp, Threema, WeChat), чтобы удаление происходило не сразу, а через определенное количество дней. Либо просто чтобы у пользователя был выбор очищать папку или нет, т.к. некоторые папки одни пользователи захотят очистить, другие захотят сохранить.
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.converted_videos   — при отправке видео большого размера, оно сжимается, в этой папке хранятся сжатые копии, которые автоматически удаляются примерно через 10 дней. После очистки папки видео продолжает воспроизводиться в чате, так как воспроизводится оригинал видео из галереи. Возможно пользователь захочет очистить папку раньше, т.к. при отправке большого количества видео папка может занять много места. Если очистить папку до появления контакта в сети, видео все равно успешно доставятся (хранятся на сервере). 
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.import    — любые типы файлов, отправленные в Вайбер из других приложений с помощью пункта "поделиться". Не удаляются со временем. Постепенно папка может вырасти до большого размера. Если папку очистить, то у меня в чате к отправленным файлам больше нет доступа, даже если файлы ещё остались на устройстве. Если очистить папку до появления контакта в сети, видео все равно успешно доставятся. 
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.image    — сюда сохраняются полученные фото. Если в чате сохранить фото в галерею, оно перемещается из этой папки в галерею; если не сохранить, остаётся в папке навсегда, со временем не удаляется. Если папку очистить, при просмотре фото в чате оно загружается в нее снова. 
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.video    — сюда сохраняются полученные видео. Если в чате сохранить видео в галерею, оно перемещается из этой папки в галерею; если не сохранить, остаётся в папке навсегда, со временем не удаляется. Постепенно папка может вырасти до больших размеров. Если очистить, то при просмотре в чате видео загружается опять.
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.gif    — входящие гифки. Если сохранить в галерею, перемещаются из этой папки в галерею. Если очистить папку, то при нажатии в чате на гифку, она опять загружается в папку с сервера. Со временем не удаляются.
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.ptt   — входящие и исходящие голосовые сообщения. Со временем сами не удаляются. Если очистить папку, с сервера опять загружаются только сообщения отправленные мне (сообщения, которые отправил я мне не загружаются).  
> 
> /storage/emulated/0/Android/data/com.viber.voip/files/.vptt   — входящие и исходящие видеосообщения, записанные встроенной функцией Вайбера (видеосообщения в кружке). Со временем сами не удаляются. Если очистить папку, с сервера опять загружаются только сообщения отправленные мне (сообщения, которые отправил я мне не загружаются).

**Comment by d4rken** [comment]
@Ingood5 did some very good ground work on this :beer:.

 I personally don't use the Viber app so I'd :heart: if others can chime in  too. Messaging apps where pictures are exchanged, are always contentious :slightly_smiling_face: :.

Open questions:

* Should we add this? Is there a lot of benefit for most of SD Maids users?
* What filters should be created? A single for all? One filter for images, one for videos?
* Multiple filters for Sent and Received?
* Which filters should be enabled by default?

Can anyone provide a PATHDUMP (SD Maid 1) or something like `ls -lR .` for the folder?

**Comment by Ingood5** [comment]
[pathdump#_storage_emulated_0_Android_data_com.viber.voip_files#1681892711486.txt](https://github.com/d4rken-org/sdmaid-se/files/11270808/pathdump._storage_emulated_0_Android_data_com.viber.voip_files.1681892711486.txt)

**Comment by d4rken** [comment]
What about the `com.viber.voip/files/.stickers`?

Are they redownloaded? or does deleting them break the sticker pack? In WhatsApp the sticker packs break if the files are deleted.

**Comment by Ingood5** [comment]
С папками .emoticons и .gems проблем не возникает.

После очистки папки .stickers в большинстве случаев возникает проблема как на видео. Стикеры загружаются но чаще всего каждый стикерпак загружается только после того как я переключусь на другой стикер и вернусь обратно на предыдущий. Я не знаю будет ли проблема у других пользователей, и если будет то будет ли это удобно большинству.

https://github.com/d4rken-org/sdmaid-se/assets/60130882/aa514b7f-d13f-40dd-9f6c-b8d84212cdd5

**Comment by Ingood5** [comment]
> Open questions:
> 
> * Should we add this? Is there a lot of benefit for most of SD Maids users?
> * What filters should be created? A single for all? One filter for images, one for videos?
> * Multiple filters for Sent and Received?
> * Which filters should be enabled by default?

Вам ещё нужны ответы по каждой папке?

**Comment by d4rken** [comment]
> С папками .emoticons и .gems проблем не возникает.
> 
> После очистки папки .stickers в большинстве случаев возникает проблема как на видео. Стикеры загружаются, но чаще всего каждый стикерпак загружается только после того как я переключусь на другой стикер и вернусь обратно на предыдущий. Я не знаю будет ли проблема у других пользователей, и если будет то будет ли это удобно большинству.
> 
>  Screenrecorder-2023-05-16-04-08-55-747.mp4 
> Иногда со стикерами в чате тоже возникает проблема как на видео, проходит после того как закрою вайбер.

Hm, we could add the folders to the "offline cache" filter, or we just ignore the :thinking: 

> Вам ещё нужны ответы по каждой папке?

Currently not, I've added the core paths to the Viber filter:
https://github.com/d4rken-org/sdmaid-se/pull/273/files#diff-d7d5cdcd9216cb6488e892057249e8726cccbf63ae0d284ffafcc6cbcc994266R32

and the others to "HiddenCaches" and "Thumbnails" filter.

**Comment by Ingood5** [comment]
> Hm, we could add the folders to the "offline cache" filter, or we just ignore the

Папки gems и emoticons занимают очень мало места, в них скачивается ограниченное количество данных, которые позже не пополняются. Их можно игнорировать. 

Папка stickers. У меня в Вайбере скачано 60 стикерпаков, в папке stickers они занимают 175 мб, при большем количестве стикерпаков будет занято больше памяти. Если я в меню Вайбера удаляю стикер из списка своих стикеров, то папка этого стикера сама очищается. То есть причина добавления папки в очистку одна – в случае если кому-то может понадобиться постоянно освобождать память, не смотря на то что будет неудобство при повторной загрузке стикеров (на видео). Какое количество пользователей выберет освобождать память, даже если будет это неудобство? Если решите добавить папку, то добавьте в специальные фильтры, т.к.  остальные пользователи не захотят ждать пока стикеры повторно загружаются.

**Comment by d4rken** [comment]
They are currently not added. If they are not of value to delete for most users then I'll probably not add them at the moment.

These are the matched files at the moment, all entries with `pos(...)`:

https://github.com/d4rken-org/sdmaid-se/blob/c8520373411bebcd064902053acce14410ae5933/app/src/test/java/eu/darken/sdmse/appcleaner/core/forensics/filter/ViberFilterTest.kt#L29-L65

**Comment by Ingood5** [comment]
Откуда появилась папка converted_gifs? Я ни разу ее не видел. На форуме, где активно обсуждают вайбер, не нашел ее. У вас в отчётах SD Maid 1 и 2 тоже не нашел 🤔

**Comment by Ingood5** [comment]
> These are the matched files at the moment, all entries with `pos(...)`:

Какие из этих папок добавлены в специфичные фильтры?

**Comment by Ingood5** [comment]
Здесь нет ошибки? Два раза написано vptt, после этого ptt. И ptt уже есть в предыдущих трёх строках.

![IMG_20230728_234541](https://github.com/d4rken-org/sdmaid-se/assets/60130882/c68dc882-1efa-4f4f-8286-82044b2be656)

**Comment by d4rken** [comment]
> Откуда появилась папка converted_gifs? Я ни разу ее не видел. На форуме, где активно обсуждают вайбер, не нашел ее. У вас в отчётах SD Maid 1 и 2 тоже не нашел 🤔

Good question, I don't remember 🤔. I think i searched the internet a bit for logs from people and reports in forums. Do you think this does not exist? Should we remove it? No harm in keeping it either though...

> > These are the matched files at the moment, all entries with `pos(...)`:
> 
> Какие из этих папок добавлены в специфичные фильтры?

These are all test cases for the "Viber" filter.

> Здесь нет ошибки? Два раза написано vptt, после этого ptt. И ptt уже есть в предыдущих трёх строках.
> 
> [IMG_20230728_234541](https://user-images.githubusercontent.com/60130882/256929373-c68dc882-1efa-4f4f-8286-82044b2be656.jpg)

Good catch, a mistake in the test 👍 . #540

**Comment by Ingood5** [comment]
> Good question, I don't remember 🤔. I think i searched the internet a bit for logs from people and reports in forums. Do you think this does not exist? Should we remove it? No harm in keeping it either though...

Поиск в интернете "converted_gifs" (в кавычках) не выдает ни одного результата... Но если вероятность появления папки "converted_gifs" с данными, которые нельзя удалять, сильно мала, думаю можно оставить как есть 😀
