### ISSUE TITLE
App Cleaner: Mass deletion happening on pressing Delete for single file

### ISSUE THREAD

**Issue by uli-on** [d4rken-org/sdmaid-se#218]
**Describe the bug**
The accessibility service deletes the whole directory after I chose to delete one single file. Looks like there's that delete button wired up faulty.

**To Reproduce**
1 tap app cleaner
2 wait until SD maid has done its job and the avocado icon appeared.
3 tap that icon
4 tap an app's folder info icon
5 in the list of files tap on one of those. A modal dialog appears with options to choose from.
6 read carefully: Confirm deletion. Delete "storage/path/to/file/filename" ?(retranslation mine)
7 tap delete
8 watch accessibility service now deleting the whole directory

**Expected behavior**
As I tapped on a single file and had been shown a path to a single file, my expectation is it will delete that very file. Beyond that excluding that file from that modal dialogue works on the selected file.

**Smartphone (please complete the following information):**
 - Device: Fairphone FP3
 - OS: Android 10
 - not rooted, no nothing
- SD maid v0.7.5beta0

**Comment by d4rken** [comment]
Do you have a few screenshs or a debug log?
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

I think the bug may be that a single file deletion triggers the accessibility action (which can only click "clear cache" that deletes all default caches...)

So we should probably disable ACS based deletion for this level app cleaner details items that are normal files and not the "default caches" entry? What do you think?

**Comment by uli-on** [comment]
I'm perplexed, it doesn't do this any longer, behaves as it should. I'll keep you informed.

**Comment by uli-on** [comment]
OK, no magic, I found the Accessibility service was deactivated again (without my ado, 4th-5th time in 7 days). Logfile is sent via mail.

**Comment by uli-on** [comment]
> So we should probably disable ACS based deletion for this level app cleaner details items that are normal files and not the "default caches" entry? What do you think?

I'm quite inexperienced with SD Maid, 7 days of dabbling, so will not advise here, sorry. I prefer to be sure about such things. But I was satisfied with SD Maid deleting the moments when Accessibility Service wasn't active, if that answers sufficiently.

**Comment by uli-on** [comment]
Fixed. Thank you.
