### ISSUE TITLE
add delete duplicate files

### ISSUE THREAD

**Issue by KakashiReiDelas** [d4rken-org/sdmaid-se#225]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

> Mornings in Sweden are always very cold and I'm not an early bird.

**Describe the solution you'd like**

> I would like it if SD Maid could make me coffee in the morning.

**Describe alternatives you've considered**

> I have considered making the coffee myself but both me and myself decided against it.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys getting a hot beverage on a cold morning.

**Additional context**

**Comment by d4rken** [comment]
Duplicate :grin:  of #2
