### ISSUE TITLE
Bug in AppControl filters

### ISSUE THREAD

**Issue by RetrogisusDEV** [d4rken-org/sdmaid-se#229]
The bug is simple, because when you step on one of the filters it gets stuck as if it were executed over and over again.

**DEVICE INFO**
 - Device: [**Umidigi A7S**]
 - CPU: [**MT6737**]
 - OS: [**Android 10 Go / API 29**]
 - Root status [**no root**]
 - SD Maid 2/SE version [**v0.7.5-rc0**]

Video:Cargando vidma_recorder_23042023_175745.mp4 @ …

**Comment by RetrogisusDEV** [comment]
You don't want to upload the video xd

Cargando vidma_recorder_23042023_175745.mp4 …

**Comment by RetrogisusDEV** [comment]
https://youtu.be/14_-Jo7nKCA

Here video...
In the new version, it still persists but it does not remain in an infinite loop, but after 3-10min it is unlocked

**Comment by RetrogisusDEV** [comment]
https://youtu.be/14_-Jo7nKCA

Here video...
In the new version, it still persists but it does not remain in an infinite loop, but after 3-10min it is unlocked

@d4rken

**Comment by RetrogisusDEV** [comment]
I forgot to upload the video xd

**Comment by d4rken** [comment]
Does this still happen with 0.7.8?

**Comment by RetrogisusDEV** [comment]
@d4rken Well yes, it is no longer locked, if, now, when changing the category very fast it seems that there was Input Lag, it is no longer such a remarkable problem ...

**Comment by RetrogisusDEV** [comment]
Ah ... and there is a translation error into Spanish, where the name of the dark theme is called `Obscuro` instead of `Oscuro`

![Screenshot_20230513-165842.jpg](https://github.com/d4rken-org/sdmaid-se/assets/99091223/a4e07fbb-46c0-4158-b231-7603935ed61c)

**Comment by d4rken** [comment]
You can change the translation here:
https://crowdin.com/project/sdmaid-se

Closing this as the bug is fixed. :slightly_smiling_face:
