### ISSUE TITLE
Bottom UI Element

### ISSUE THREAD

**Issue by dontobi** [d4rken-org/sdmaid-se#24]
The bottom UI element should display a round icon in the center. A similar UI is provided by the Wavelet app (see screenshot).

![Screenshot_20230325-173515](https://user-images.githubusercontent.com/19261667/227730058-18e42f08-d80e-48b5-8c62-39a91d00d11e.png)

**Comment by d4rken** [comment]
Thanks for the feedback

Is the current way wrong or subjectively unpleasing? :thinking: 

Any other opinions on this?

**Comment by dontobi** [comment]
I've been using the Wavelet app for some time now, and I find the bottom UI to be fitting and coherent.

This can only be the case for me. Would be nice if others would comment on this.

**Comment by d4rken** [comment]
I've tweaked it a bit. Looks close to your screenshot now, happy to hear about it next update :).

**Comment by dontobi** [comment]
Just installed the new version. Looks very good.
