### ISSUE TITLE
Application cache cleanup does not work if you give "administrator" permission to the application.

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/sdmaid-se#242]
Application cache cleanup does not work if you give "administrator" permission to the application.

in miui. In the Russian translation. android 12. only for the application with this permission does not work.  Through Accessibility Service.
After completing an attempt to clear applications with this permission, the application goes to the desktop.

**Comment by d4rken** [comment]
What permission do you mean? Device administrator?
To which app SD Maid or the cleaning target?
Could you show me a video of the issue?

**Comment by d4rken** [comment]
So for apps that are "device administrators", the cache can't be cleared using ACS? So what's the solution, exclude them from results?

**Comment by d4rken** [comment]
Don't write extra posts just to tag me.

> The problem is that there's a "Clear Cache" button right there. There is no "Clear" button. For normal apps, the app first clicks on "Clear" and then on "Clear Cache". But for apps with administrator permission, you have to click "Clear Cache" first. That's it.

Similar to #274 the clean solution would be a decision or branching logic to change course of action when this is detected :thinking:

**Comment by d4rken** [comment]
Can you clean them manually? Is the button clickable? These are not "admin apps" right? So must be a different issue.
