### ISSUE TITLE
Crash when scanning large apps

### ISSUE THREAD

**Issue by E0697** [d4rken-org/sdmaid-se#245]
**Describe the bug**

The app hangs up for too long when scanning apps with large data in the App Cleaner.
In my case it's AnkiDroid ~ 6GB.
I tried excluding it, but it's still included at the end of the scan, as opposed to the beginning.
If I keep waiting for it to finish, the app crashes

**To Reproduce**
1. Go to 'App Cleaner'
2. Click on 'Scan'
3. Wait for a long time
4. App crashes

**Expected behavior**

I really hope the scanning speed can be improved.
SD maid wasn't this slow.

**Smartphone (please complete the following information):**
 - Device: Realme 7 Pro
 - OS: Android 12
 - Root status: Not rooted
 - SD Maid 2/SE version 0.7.8-beta0 708000

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).
[eu.darken.sdmse_logfile_1683103931934.log](https://upload.disroot.org/r/T2X0QEqC#6QcZk/cKwu/HD8TeWlqv19XNsMN/bQ1DvedmoUgp8H0=)

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
If you create an exclusion for AnkiDroid via AppControl, does SD Maid completely skip it or is it still scanning the files and getting stuck?

I'll look more into optimizations that can be done here, but if an exclusion works it would be a workaround for now (and if it doesn't we should make the exclusions work for cases like this...).

SD Maid 2 can't be as fast as SD Maid 1 in some cases due to more thorough checks and support for more storage types, but there are a lot of tricks we can add to still improve performance, and on a case by case basis even be faster than SD Maid 1 (just not in general).

**Comment by E0697** [comment]
It still scans for it. The exclusion doesn't seem to be working.

I can tolerate it being slower in some cases, considering it's more adapted to newer Android version. Which should translate to better results overall.

 The real issue here is the crash. The App Cleaner functionality is practically unusable.

**Comment by d4rken** [comment]
I've only now managed to check the logfile. It seems you just started then stopped it.
It is a recording, can you start it before running the scan, and stop it after the crash?

I checked the user ID from your log and didn't find an automatic report.

The 6GB from AnkiDroid is stuff you created, right?
Or can I just install AnkiDroid and reproduce it that way?

**Comment by d4rken** [comment]
#254 should fix the exclusion, still don't know though where the crash comes from 🤔

**Comment by E0697** [comment]
I remember I started it then started the ecan then stopped it after the scan. I'll try again tho.

Yes that's the one, but the 6GB is a bunch of decks I imported in the app. Not easy to reproduce.

I guess the exclusion is enough for now, I can delete the cache of AnkiDroid manualy. But I'll see what I can do about the log.

Thank you!

**Comment by E0697** [comment]
Here's a new log:
[eu.darken.sdmse_logfile_1683646777762.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11433223/eu.darken.sdmse_logfile_1683646777762.log.zip)

**Comment by d4rken** [comment]
Thanks, but the log is still incomplete 🤔 
You can open it yourself it's just text, there should probably be thousands of lines of text with all the files from AnkiDroid, but  it's not, hm maybe there is a bug with the log recorder, let me test something, whether it survives crash.

**Comment by d4rken** [comment]
Yeah there's a bug, it continues the log with a new file instead of the old one before the crash ☹️ sorry, you'll have to redo the log after the next update.

**Comment by E0697** [comment]
No worries, will do. I suspected such thing. Thanks for looking into it.

**Comment by d4rken** [comment]
v0.7.9-beta1 has fixed debug logs (and the better exclusion code)

**Comment by E0697** [comment]
These are the last couple of lines before the log starts over with "===BEGIN==="

`2023-05-12T09:52:43.823Z  V/SDMSE:Gateway:SAF: lookup(SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data, com.ichi2.anki, files, AnkiDroid1, collection.media, google-949826f4-08598066-3a542789-c9a3b9e5-e093debf.mp3])) -> SAFDocFile(uri=content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.ichi2.anki%2Ffiles%2FAnkiDroid1%2Fcollection.media%2Fgoogle-949826f4-08598066-3a542789-c9a3b9e5-e093debf.mp3)
2023-05-12T09:52:44.198Z  V/SDMSE:Gateway:SAF: lookup(SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data, com.ichi2.anki, files, AnkiDroid1, collection.media, Huhn-aus-Ei-xs-iStock_000004386812XSmall.jpg])) -> SAFDocFile(uri=content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.ichi2.anki%2Ffiles%2FAnkiDroid1%2Fcollection.media%2FHuhn-aus-Ei-xs-iStock_000004386812XSmall.jpg)
2023-05-12T09:52:44.642Z  V/SDMSE:Gateway:SAF: lookup(SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data, com.ichi2.anki, files, AnkiDroid1, collection.media, paste-51157355462657 (1).png])) -> SAFDocFile(uri=content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.ichi2.anki%2Ffiles%2FAnkiDroid1%2Fcollection.media%2Fpaste-51157355462657%20(1).png)
2023-05-12T09:52:45.092Z  V/SDMSE:Gateway:SAF: lookup(SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data, com.ichi2.anki, files, AnkiDroid1, collection.media, paste-25533580574721.png])) -> SAFDocFile(uri=content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.ichi2.anki%2Ffiles%2FAnkiDroid1%2Fcollection.media%2Fpaste-25533580574721.png)
2023-05-12T09:52:45.539Z  V/SDMSE:Gateway:SAF: lookup(SAFFile(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data, com.ichi2.anki, files, AnkiDroid1, collection.media, LFK-Teamwork-01-einfach-schraeg.jpg])) -> SAFDocFile(uri=content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata/document/primary%3AAndroid%2Fdata%2Fcom.ichi2.anki%2Ffiles%2FAnkiDroid1%2Fcollection.media%2FLFK-Teamwork-01-einfach-schraeg.jpg)
2023-05-12T09:52:46.662Z  D/SDMSE:TaskManager: Releasing resource lock for 62430c1b-be91-4aff-baab-963c2d0d37e5
2023-05-12T09:52:46.667Z  V/SDMSE:TaskManager: Task map changed:
2023-05-12T09:52:46.668Z  V/SDMSE:TaskManager: #0 - ManagedTask(id=62430c1b-be91-4aff-baab-963c2d0d37e5, task=AppCleanerScanTask(pkgIdFilter=[]), tool=eu.darken.sdmse.appcleaner.core.AppCleaner@25d0876, queuedAt=2023-05-12T09:05:49.385537Z, startedAt=2023-05-12T09:05:49.406032Z, cancelledAt=null, completedAt=2023-05-12T09:52:46.666355Z, job=LazyStandaloneCoroutine{Active}@25e8dd5, resourceLock=Resource(_item=SDMSE:TaskManager{113801497}, lease=ActiveLease(job=StandaloneCoroutine{Cancelling}@93779ea)), result=null, error=null)
2023-05-12T09:52:46.671Z  V/SDMSE:TaskManager:SR: Releasing shared resource...
2023-05-12T09:52:46.672Z  V/SDMSE:TaskManager:SR: Closing child resource: ChildResource(isClosed=false, child=SharedResource(tag=SDMSE:AppCleaner:SR, leases=1, children=3))
2023-05-12T09:52:46.673Z  D/SDMSE:TaskManager:SR: Shared resource flow completed.
2023-05-12T09:52:46.675Z  V/SDMSE:AppCleaner:SR: Releasing shared resource...
2023-05-12T09:52:46.676Z  V/SDMSE:AppCleaner:SR: Closing child resource: ChildResource(isClosed=false, child=SharedResource(tag=SDMSE:CSI:FileForensics:SR, leases=1, children=2))
2023-05-12T09:52:46.677Z  V/SDMSE:AppCleaner:SR: Closing child resource: ChildResource(isClosed=false, child=SharedResource(tag=SDMSE:Gateway:Switch:SR, leases=2, children=2))
2023-05-12T09:52:46.677Z  V/SDMSE:AppCleaner:SR: Closing child resource: ChildResource(isClosed=false, child=SharedResource(tag=SDMSE:PkgOps:SR, leases=2, children=0))
2023-05-12T09:52:46.678Z  D/SDMSE:AppCleaner:SR: Shared resource flow completed.
`

**Comment by d4rken** [comment]
Hm, looks like a normal task finish. Nothing about a crash.
My previous thought was that this is an out of memory issue due to so many files, but after the task finishes, the memory use should go down...
Can you use an app or a computer to get the crash stack trace from `logcat`?

**Comment by E0697** [comment]
I experienced another crash when using the System Cleaner.
I only excluded Anki from App Cleaner.
Here's the crash log: ![logcat.txt](https://github.com/d4rken-org/sdmaid-se/files/11464206/logcat.txt)

**Comment by E0697** [comment]
Yes, I did.
This one should be complete.
![logcat1.txt](https://github.com/d4rken-org/sdmaid-se/files/11468018/logcat1.txt)

The System Cleaner crash still happens after excluding AnkiDroid.
It should be captured in the logcat above as well.

**Comment by d4rken** [comment]
Great logs, thanks!

**SD Maid is running out of memory in various situations.** 

The system gives SD Maid 132MB of RAM and that seems to be not enough.

Hm, this is tough to fix. I can set `largeHeap=true` for SD Maids next release (SD Maid 1 also has this) as a workaround until I can profile the memory use more. I don't suspect a leak, it's likely that you just have many results that SD Maid tries to keep in memory.

Are you running tools in parallel or one after each other?

Out of memory when gathering app data:

```
05-03 09:38:33.560 26333 31742 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
05-03 09:38:33.560 26333 31742 E AndroidRuntime: Process: eu.darken.sdmse, PID: 26333
05-03 09:38:33.560 26333 31742 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 336 byte allocation with 274544 free bytes and 268KB until OOM, target footprint 134217728, growth limit 134217728; giving up on allocation because <1% of heap free after GC.
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ApplicationInfo$1.lambda$createFromParcel$0(ApplicationInfo.java:2003)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ApplicationInfo$1$$ExternalSyntheticLambda0.readRawParceled(Unknown Source:0)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.os.Parcel.readSquashed(Parcel.java:2139)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:2003)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ApplicationInfo$1.createFromParcel(ApplicationInfo.java:2000)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.PackageInfo.<init>(PackageInfo.java:541)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.PackageInfo.<init>(PackageInfo.java:29)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.PackageInfo$1.createFromParcel(PackageInfo.java:519)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.PackageInfo$1.createFromParcel(PackageInfo.java:516)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.BaseParceledListSlice.readCreator(BaseParceledListSlice.java:126)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.BaseParceledListSlice.readVerifyAndAddElement(BaseParceledListSlice.java:110)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.BaseParceledListSlice.<init>(BaseParceledListSlice.java:98)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:42)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ParceledListSlice.<init>(ParceledListSlice.java:35)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:80)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.ParceledListSlice$1.createFromParcel(ParceledListSlice.java:78)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.getInstalledPackages(IPackageManager.java:5894)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getInstalledPackagesAsUser(ApplicationPackageManager.java:1133)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:1124)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$rawPkgs$1.invokeSuspend(PkgOps.kt:14)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at eu.darken.sdmse.common.pkgs.pkgops.PkgOps$queryPkgs$rawPkgs$1.invoke(PkgOps.kt:13)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at eu.darken.sdmse.common.funnel.IPCFunnel$use$2.invokeSuspend(IPCFunnel.kt:82)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
05-03 09:38:33.560 26333 31742 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dfa0f84, Dispatchers.Default]
```

When scanning folders:

```
05-03 11:52:00.423 22063 32605 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
05-03 11:52:00.423 22063 32605 E AndroidRuntime: Process: eu.darken.sdmse, PID: 22063
05-03 11:52:00.423 22063 32605 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 1672 byte allocation with 876392 free bytes and 855KB until OOM, target footprint 134217728, growth limit 134217728; giving up on allocation because <1% of heap free after GC.
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3766)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:449)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:137)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:132)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$lookup$2.invokeSuspend(SAFGateway.kt:48)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$lookup$2.invoke(SAFGateway.kt:13)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$runIO$2.invokeSuspend(SAFGateway.kt:33)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$runIO$2.invoke(SAFGateway.kt:13)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:72)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway.runIO(SAFGateway.kt:14)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$lookupFiles$2.invokeSuspend(SAFGateway.kt:233)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$lookupFiles$2.invoke(SAFGateway.kt:13)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$runIO$2.invokeSuspend(SAFGateway.kt:33)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway$runIO$2.invoke(SAFGateway.kt:13)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:5)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:72)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway.runIO(SAFGateway.kt:14)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.saf.SAFGateway.lookupFiles(SAFGateway.kt:9)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.GatewaySwitch$lookupFiles$2.invokeSuspend(GatewaySwitch.kt:33)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.GatewaySwitch$lookupFiles$2.invoke(GatewaySwitch.kt:13)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.GatewaySwitch.useGateway(GatewaySwitch.kt:87)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.GatewaySwitch.lookupFiles(GatewaySwitch.kt:7)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.common.files.PathTreeFlow.collectSafely(PathTreeFlow.kt:252)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:69)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at coil.ImageLoaders.toCollection(ImageLoaders.kt:62)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at coil.ImageLoaders.toList$default(ImageLoaders.kt:6)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner.readAppDirs(AppScanner.kt:404)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner.scan(AppScanner.kt:1115)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at eu.darken.sdmse.appcleaner.core.scanner.AppScanner$scan$1.invokeSuspend(Unknown Source:12)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
05-03 11:52:00.423 22063 32605 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@c73539b, Dispatchers.IO]
```

**Comment by E0697** [comment]
I see. I mostly run a single task until it finishes. SD Maid had no problem with multithreading however.

**Comment by d4rken** [comment]
SD Maid 1 used `largeHeap=true`, I've changed this for the next update of SD Maid 2 now, see #277. If that works let's keep the flag, and we can try to optimise memory use, but it's a a lot of manual checking, tweaking lots of little things.

I looked for an hour this morning and didn't find any leaks or unusually large memory allocations, so no "low hanging fruits" that can be fixed.

**Comment by E0697** [comment]
Got it. Waiting for the next update.

Thanks for taking the time!
