### ISSUE TITLE
Can't grant SAF access because "Documents" app is unavailable

### ISSUE THREAD

**Issue by zhangweildlh** [d4rken-org/sdmaid-se#246]
On Android 10 (China MIUI v12.5.5)

The phone has been Rooted, SD Maid SE has obtained Root permission

Unable to obtain access permissions for '/storage/mutated/0' and '/storage/6594-1D01' (SD card) in the 'Storage Access Framework'
[微信截图_20230504184827](https://user-images.githubusercontent.com/62597291/236185283-340a8b0b-f0e1-48b4-a009-ddbb0612215e.jpg)
[微信图片_20230504185225](https://user-images.githubusercontent.com/62597291/236185316-609e4a7c-97a4-4ad5-95d5-c5f4403fe43a.jpg)
[微信图片_20230504184053](https://user-images.githubusercontent.com/62597291/236185339-0396eb6e-a3da-4fb0-86d0-370c293889a6.jpg)

**Comment by d4rken** [comment]
What happens when you try to grant the permission?
What happens when you click the buttons?

**Comment by zhangweildlh** [comment]
> 当您尝试授予权限时会发生什么？ 单击按钮时会发生什么？

After clicking the "Authorize" button, SD will pop up an error window
"mistake"
"The Documents app could not be found. It is a built-in app that should come with all Android devices."
"help", "ok"

![236185283-340a8b0b-f0e1-48b4-a009-ddbb0612215e](https://user-images.githubusercontent.com/62597291/236774833-0465ed58-abef-4b6e-8cb2-fbf15285c676.jpg)
![5baa3b15777f516eef0f9bff9eb7285](https://user-images.githubusercontent.com/62597291/236774857-69d5ad6d-42bf-411a-8690-2ffd1551f8b7.jpg)

**Comment by d4rken** [comment]
The "Documents" app should be available on your device. Did you disable it with scripts?
It's a default app of the Android system!

If I remove this check, and SD Maid only uses root, then SD Maid has less options during search and I can optimize access less 🤔 

I could use root though to find the documents app and enable it again if it's still installed 🤔

**Comment by zhangweildlh** [comment]
> The "Documents" app should be available on your device. Did you disable it with scripts? It's a default app of the Android system!
> 
> If I remove this check, and SD Maid only uses root, then SD Maid has less options during search and I can optimize access less 🤔
> 
> I could use root though to find the documents app and enable it again if it's still installed 🤔

There is a 'Document' application on my phone and it is not disabled.

The 'Document' application is the MT manager

Download link https://bbs.binmt.cc/thread-109815-1-1.html

**Comment by d4rken** [comment]
No the "Documents" app i mean is a built in app from Google, it's in the base OS, in AOSP.

https://source.android.com/docs/core/ota/modular-system/documentsui

If it's removed or disabled, it breaks part of the system... ❗

**Comment by zhangweildlh** [comment]
> > The "Documents" app should be available on your device. Did you disable it with scripts? It's a default app of the Android system!
> > If I remove this check, and SD Maid only uses root, then SD Maid has less options during search and I can optimize access less 🤔
> > I could use root though to find the documents app and enable it again if it's still installed 🤔
> 
> There is a 'Document' application on my phone and it is not disabled.
> 
> The 'Document' application is the MT manager
> 
> Download link https://bbs.binmt.cc/thread-109815-1-1.html

![c8bb9d2c7801e9d9e4406e53cb9ccf3](https://github.com/d4rken-org/sdmaid-se/assets/62597291/de2e711f-2d65-4241-aa97-66e694c0f0af)

**Comment by d4rken** [comment]
I'm currently out of ideas, this is an issue in your ROM, SD Maid is trying to use a normal Android feature.

The only option I currently see is to add an ignore option and let SD Maid try to replace SAF access with root. This could work, but I don't like adding too many special cases.

This is also a problem in SD Maid 1, right?

**Comment by zhangweildlh** [comment]
> 我目前没有想法，这是你的 ROM 中的一个问题，SD Maid 正在尝试使用正常的 Android 功能。
> 
> 我目前看到的唯一选项是添加一个忽略选项，让 SD Maid 尝试用 root 替换 SAF 访问权限。这可以工作，但我不喜欢添加太多特殊情况。
> 
> 这也是SD女仆1的问题吧？
Yes

**Comment by d4rken** [comment]
Currently I see no way to fix this :frowning_face:.

The documents app should be there, but it isn't. This is a ROM bug. SD Maid is using standard Android API's here.

Grant SD Maid root, complete all other setup items, and dismiss the setup.
