### ISSUE TITLE
AppCleaner fails to clear cache

### ISSUE THREAD

**Issue by Shkzeen** [d4rken-org/sdmaid-se#274]
**Describe the bug**
There are 2 bugs, but both are closely related so I wont bother making 2 issues.
1.= App has to tap on 'Storage & cache' before clearing cache.
2.= App is looking for 'clear data' while in miui it is called 'clear cache'

**To Reproduce**
1. Go to 'AppCleaner'
2. Click on 'Delete '
3. Click on 'Delete '

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [XiaoMi Poco X3 Pro]
 - OS: [MiUi 13 / Android 12]
 - Root status [no]
 - SD Maid 2/SE version [0.7.9-beta1]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**possible ideas to fix**
1- add miui check
2- add multi step cache clearing procedure.
**Screenshots/Video**
https://ufile.io/y8a6k029
from last version but still applies, re-tested.
**Additional context**
;D
I think that the '**possible ideas to fix**' thing should be standardized.
Thanks for reading!

**Comment by d4rken** [comment]
Does this work in SD Maid 1?
Normally on MIUI there is a shortcut way through quick buttons at the bottom, SD Maid is looking for that.

**Comment by Shkzeen** [comment]
Hello!
Miui has two ways to display app info: Settings, and security.
Security has the shortcut, but settings doesn't.
We might have to check the current activity, Or start the security activity directly.
I'd be happy to help!
Best regards,
~Matt.

**Comment by d4rken** [comment]
> Does this work with SD Maid 1?


:point_up: 

SD Maid SE uses the same base method as SD Maid 1. So knowing this would help.

When does the "Settings" app and when is the "Security" app used?

**Comment by Shkzeen** [comment]
Sorry.. unable to test sdmaid1, no G-Services.
Anyways! I found where the security and settings things are used.
security is used in the system **by** the system. Clear as mud? Eg. When opening app info from settings or the task switcher.
settings is used everywhere else.
aaaand.. I got some things that might prove useful, by using some debug/factory testing tool that was left in production XD. (Some activity or smth idk)
![Screenshot_2023-05-15-10-14-07-036_com miui securitycenter jpg](https://github.com/d4rken-org/sdmaid-se/assets/50447695/a84221b0-7c94-44af-a5a2-077ab06a16fe)
^security.
![Screenshot_2023-05-15-10-13-54-151_com android settings jpg](https://github.com/d4rken-org/sdmaid-se/assets/50447695/bbd6c95a-9b37-4528-8a8f-76386aff0ef4)
^settings.
Cya!

**Comment by Shkzeen** [comment]
Btw: the app doesn't matter.
I used f-droid and settings as examples, any app could be in their place. (What I'm trying to say is that the security dialogue can have any app, not only system ones)

**Comment by SirSauron** [comment]
New Version 0.7.9 And hasn't gotten any Bretter.
5x every option clicked, Still shows the same?
An app that is made for that should be able to do that.

Old Version 5.5.9 Pro install

**Comment by venkat2305** [comment]
https://github.com/d4rken-org/sdmaid-se/assets/55329452/c979bae3-87e8-40fd-9a2b-68ddc7f4efd9

**Comment by d4rken** [comment]
@Shkzeen Does the latest v0.7.11 fix this? If not, can you get me another debug log?

**Comment by d4rken** [comment]
> Screenrecorder-2023-05-20-07-28-53-928.mp4

That looks like accessibility service is disabled, check SD Maids setup via settings.
If it's enabled please open a new issue. This is unrelated to this one by @Shkzeen

**Comment by Shkzeen** [comment]
Heyy,
Nope.. unfortunately still not fixed.
Sure thing! Here is another log:
[eu.darken.sdmse_logfile_1684669638911.zip](https://github.com/d4rken-org/sdmaid-se/files/11524476/eu.darken.sdmse_logfile_1684669638911.zip)
Hope this helps!

**Comment by Shkzeen** [comment]
![Screenshot_2023-05-21-14-38-34-042_com android settings jpg](https://github.com/d4rken-org/sdmaid-se/assets/50447695/167c987b-a334-4ac4-80d1-a29932b20107)
Screenshot.. 
it still opens the settings so it still is unable to find the clear button.

**Comment by d4rken** [comment]
:frowning: the log still shows the issue with the different settings apps. I don't understand why this is different on your MIUI in comparison to other MIUI devices, I should have more reports if this is a widespread issue.

This can be solved in code, but adding decision logic for this :sweat:.

**Comment by Shkzeen** [comment]
Why not add a switch in the app settings to toggle between aosp clearing and miui clearing, making it greyed out for non-MiUi users?

**Comment by Shkzeen** [comment]
Hello~..Anybody here?

**Comment by Shkzeen** [comment]
An idea:
add text boxes in settings so users can select what the app searches for.

**Comment by Shkzeen** [comment]
@d4rken?

**Comment by d4rken** [comment]
I think this is fixed (or almost fixed) with #339.
SD Maid will now detect which settings activity launches and will adjust the routine.
Please report back after the next update. If it still doesn't work, I'll need a new debug log.

**Comment by Shkzeen** [comment]
It Works!!!!1!!!
TYSM @d4rken ♥

**Comment by Shkzeen** [comment]
It works!!!1!!
tysm @d4rken
