### ISSUE TITLE
The eye icon is too close to the Delete button

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#286]
Значок глаза, который около AppCleaner, находится слишком близко к кнопке Удалить. Я думаю пользователь вместо глаза может случайно нажать на удаление. 

![IMG_20230516_082202](https://github.com/d4rken-org/sdmaid-se/assets/60130882/dc89f8e1-4224-4c91-abd6-366d9cad3417)

**Comment by d4rken** [comment]
Just not much space, :thinking: 
What do you suggest?

**Comment by Shkzeen** [comment]
Maybe left align?

**Comment by uli-on** [comment]
Left align, reduce buttons' paddings, especially if with star icon.
