### ISSUE TITLE
Change the status of file crash_log_1 to "not keeper" 

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid-se#287]
У меня файл crash_log_1 по ошибке помечен как keeper.

https://github.com/d4rken-org/sdmaid/issues/3995#issue-707360972

**Comment by d4rken** [comment]
Do you want to try to change it?

Open this:
https://github.com/d4rken-org/sdmaid-se/blob/main/app/src/main/assets/clutter/db_clutter_markers.json
and click "Edit file" in the top right corner.

then find the entry:
https://github.com/d4rken-org/sdmaid-se/blob/main/app/src/main/assets/clutter/db_clutter_markers.json#L1008

and change it from
```
{"loc": "SDCARD", "path": "Download/crash_log_1.txt", "flags": ["keeper"]}
```

to

```
{"loc": "SDCARD", "path": "Download/crash_log_1.txt"}
```

Now click "Commit changes" and GitHub should create a new pull request with the change :rocket: 

It would show you as contributor to the project in GitHub in the changelog :hugs:

**Comment by Ingood5** [comment]
Сделал 😀

После этого изменения все файлы по маске тоже будут помечены как не keeper? То есть crash_log_1, crash_log_2, crash_log_3 и так далее.

**Comment by d4rken** [comment]
I think it currently only matches "1" , do the others exist too?

**Comment by d4rken** [comment]
There already was a definition for _1 _2, we just had to remove the extra definition :smile:.
