### ISSUE TITLE
app based exclusion not working for SystemCleaner

### ISSUE THREAD

**Issue by rhjdvsgsgks** [d4rken-org/sdmaid-se#290]
**Describe the bug**
in Exclusion manager. after adding a app exclusion. select exclude in "All tools". SystemCleaner still trying to scan the excluded app

**To Reproduce**
1. add termux to exclusion app
2. create a file `/data/data/com.termux/files/home/test.log`
3. run SystemCleaner
4. spend lot of time on scanning termux. and found `/data_mirror/data_ce/null/0/com.termux/files/home/test.log` in "Log files" results

**Expected behavior**
 skip scanning termux

**Smartphone (please complete the following information):**
 - Device: not relevant
 - OS: android 11
 - Root status: Magisk v26.1
 - SD Maid 2/SE version: 0.7.10-beta0

**Debug log**
If you need this, i can provide a striped log

**Screenshots/Video**
seems not necessary here

**Additional context**
similar to #245
my old issue for sdmaid 1 https://github.com/d4rken-org/sdmaid/issues/3834

**Comment by d4rken** [comment]
That's a good idea 💡
