### ISSUE TITLE
Servicio accesibilidad

### ISSUE THREAD

**Issue by androidmonty** [d4rken-org/sdmaid-se#291]
Cada vez que necesito usar la aplicación debo de repetir el permiso para el servicio de accesibilidad. El permiso consta como establecido pero la aplicación me solicita volver a hacerlo. Sd no está optimizada por el sistema.

Xiaomi redmi note 8 pro. (MIUI Global 12.5.7)

![Screenshot_2023-05-19-08-27-35-328_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/134040684/1b500305-8c00-4ae5-8891-5811cac33449)

![Screenshot_2023-05-19-08-27-24-974_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/134040684/0ff23606-aec4-4d25-81c8-800ea9bd4d56)

**Comment by d4rken** [comment]
Have you enabled Autostart for SD Maid?

**Comment by androidmonty** [comment]
What do you mean exactly? Programador is enabled.. yes
