### ISSUE TITLE
App Cleaner's accessibility feature not working properly

### ISSUE THREAD

**Issue by benjaluth09** [d4rken-org/sdmaid-se#297]
**Describe the bug**
On phones with tiny screens, the option Storage doesn't appear and in most of these phones, you must need to scroll down to get the Storage option. Now, SD Maid is scrolling down and those things, but sometimes, it fails to do that and it marks it that it cleaned the app's cache. 
(I have a high DPI)
**To Reproduce**
1. Scan on App Cleaner
2. Click on Details button
3. Select an app

**Expected behavior**
SD Maid scrolling down and clicking the Storage option, then on Clear cache.

**Smartphone (please complete the following information):**
 - Device:
 - OS: Android 9, no personalisation layer
 - Root status: No
 - SD Maid 2/SE Latest version (0.7.11-beta0)

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Scroll behavior was improved and I think this is fixed.
