### ISSUE TITLE
Uninstall functionality

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#30]
Should AppControl get a mass uninstall feature similar to what SD Maid 1 had?

With root it should work quite well. I didn't like the way it worked without root in SD Maid 1 though.

We could try to make use of the accessibility service to confirm mass deletion automatically...

In earlier Android versions, uninstalling system apps with root worked quite well, but broke down due to system partition design changing so much. I kinda dread that part... So I'm leaning to only target uninstall functionality for non-system apps.

**Comment by Rokcy98** [comment]
I asked for this on xda, but, at the moment, maybe there are more important things to implement, even because the app is already capable of deleting thrash as soon as an app is uninstalled

**Comment by K-plus69** [comment]
Yes this would be nice!

**Comment by tathastu871** [comment]
I second this thing. just like clicking clear cache. Sdmaid can click uninstall in settings for apps defined by user or all aapps

**Comment by AlbiDR** [comment]
I bought SDM so many years ago i don't even remember when exactly. So i clearly bought the new app as soon as I saw on Reddit it got released.

I would love for the uninstall feature to be present; better if in mass and better if for system apps.
Unlike someone else i think this is a pretty important feature, it's actually one of the reason why I've had SDM1 installed for all these years.

**Comment by tathastu871** [comment]
For system apps requires Root. and if you have root you dont need sdmaid for uninstalling. Use adb to remove all apps.

However for non root phone I Like sdmaid to have this uninstall feature for bulk uninstalling non system apps without involving adb use

**Comment by tathastu871** [comment]
Also Fearure to disble apps by clicking Disable in settings would be good

**Comment by AlbiDR** [comment]
> For system apps requires Root. and if you have root you dont need sdmaid for uninstalling. Use adb or any uninstaller app to remove all apps.
> 
> However for non root phone I Like sdmaid to have this uninstall feature for bulk uninstalling non system apps without involving adb use


Oh yes, of course i can use ADB to uninstall (or disable) an app. But i don't want to use ADB if SDM2 can do it for me on the go, while not close to a laptop or when I'm on the toilet. 
SDM1 has always been installed on my phone because besides the cleaning tools it also had general use tools like these. SDM1 was and is perfect - so i would be happy to see 95% of the features to be back and maybe packaged in a nicer looking app.

**Comment by tathastu871** [comment]
![Screenshot_20230402-215435_SD Maid SE](https://user-images.githubusercontent.com/65007212/229365909-d966d897-628f-4e79-994e-7f8fca9a338e.jpg)


Add uninstall option Here

Also add support for bulk selecting or all selecting apps and uninstall them

**Comment by d4rken** [comment]
Some functionality was added by #220 and #221 (single uninstall on unrooted devices)

**Comment by d4rken** [comment]
#224 adds single uninstall on rooted devices.

**Comment by d4rken** [comment]
#382 adds multi selection
