### ISSUE TITLE
Extend StorageAnalyzer's "User files" UI

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/sdmaid-se#314]
main tasks:
- Ability to delete files;
- ability to open files;
- Create a setting that is disabled by default: show file thumbnails.

minor:
- Ability to move files, change file names

**Comment by d4rken** [comment]
> Ability to delete files;

Ability to delete files is tracked by #313

> ability to open files;

Planned

> Create a setting that is disabled by default: show file thumbnails.

Currently working on that, basically file preview everywhere in SD Maid, default will be "enabled" though, why should it be disabled?

> Ability to move files, change file names

File explorer functionality is currently not planned. There are better apps for doing this sort of stuff.

**Comment by d4rken** [comment]
Thumbnails are not stored on disk, only loaded into memory. No extra storage is consumed.
