### ISSUE TITLE
Browse app data within StorageAnalyzer

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/sdmaid-se#315]
the ability to enter the application's private folder in the "data" folder from the location shown in the screenshot.

----------------------------------

there should be a button here somewhere. It will allow you to delete unnecessary data there. This is very useful, because right now this application thinks that it is impossible to do this.

![347c804b-44a5-4028-903f-97b1b7ecb69c.jpg](https://github.com/d4rken-org/sdmaid-se/assets/113500363/d93d7106-113d-4ad7-ab71-91136f10925c)

![6a42d5e6-3711-43bb-b03d-2abec4f56a6d.jpg](https://github.com/d4rken-org/sdmaid-se/assets/113500363/9a0360de-8285-41f3-868d-1d06e4bdf6b4)

**Comment by d4rken** [comment]
Ah this is public storage. Yes for < Android 13 this can be viewed.
With root, it can be browsed on Android 13+ too, even private data too...

**Comment by d4rken** [comment]
This is possible now, right?

**Comment by buggad** [comment]
My filer that you're se made force me to use to find /emulated /0
Only take me to download there is no way to get any further with that app I
has to use
F x or file explorer otherwise I can't give the program clerens to 0
folder!
Regards mike

ed90

Den tors 29 juni 2023 22:00Wjxfi ***@***.***> skrev:

**Comment by d4rken** [comment]
@Wjxfi  With v0.10.3 and Shizuku it works, theoretically also on Android 12 with SAF, but I think I have not tested that. What Android version do you have?

**Comment by d4rken** [comment]
> it still doesn't work. Even with shizuku.

Please provide a debug log.

> I would also like you to add the ability to view this folder (/data).

Not feasible with Shizuku.

**Comment by d4rken** [comment]
I need a log of the full StorageAnalyzer scan to find out why `/storage/emulated/0/Android/data` is not being scanned on your device despite SAF and Shizuku.

Start the debug log recording, force stop SD Maid, open SD Maid, let the StorageAnalyzer scan and try to view some app data from `/storage/emulated/0/Android/data`, then stop the log and share it with me. Thanks!

> it can all be done with SAF.

Accessing `/data` requires root (some exceptions exist, like Shizuku->`/data/local/tmp`). Why do you think that it can be accessed with SAF?

**Comment by d4rken** [comment]
I meant /storage/emulated/0/Android/data.

Just to make sure we are not wasting time here: The remaining issue is not being able to access app details in `/storage/emulated/0/Android/data`, via StorageAnalyzer, on an Android 12 devices, despite Shizuku and SAF being set up?

> it completely violates my privacy

You can mail it to me if that is a concern, I'm not making it publicly available.
But I understand if that is not something you want.
Though to fix the remaining issue, I need more data as I'm out of ideas at the moment and can't reproduce this with my Android 12 and 13 test devices.

**Comment by d4rken** [comment]
I have found an issue, but only on my Android 13 device, it's possible that this affects other Android 12 devices too, just not mine :sweat:.

**Comment by d4rken** [comment]
This should be working as expected.
