### ISSUE TITLE
StorageAnalyzer crashes

### ISSUE THREAD

**Issue by uli-on** [d4rken-org/sdmaid-se#326]
**Describe the bug**
The StorageAnalyzer tool crashes SD Maid repeatedly.

**To Reproduce**
1. Tap the tool name or the eye icon, regardless.
2. Wait for the task to complete
3. Tap any of the devices, regardless
4.  Message about  repeated crash appears

**Smartphone **
 - fairphone 3
 - android 10
 - not rooted, no magisk, no magic whatsoever
 - SD Maid 0.8 beta0

**Debug log**
Stacktrace caught with Scoop app:

```
FATAL EXCEPTION: DefaultDispatcher-worker-10
Process: eu.darken.sdmse, PID: 27362
eu.darken.sdmse.common.files.ReadException: Can't read from path. <-> /storage/emulated/0
	at eu.darken.sdmse.common.files.local.LocalGateway$lookupFiles$3.invokeSuspend(Unknown Source:473)
	at eu.darken.sdmse.common.files.local.LocalGateway$lookupFiles$3.invoke(Unknown Source:12)
	at eu.darken.sdmse.common.files.local.LocalGateway$runIO$2.invokeSuspend(Unknown Source:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:102)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:76)
	Suppressed: coil.network.HttpException: [StandaloneCoroutine{Cancelling}@334533c, Dispatchers.Default]
Caused by: java.io.IOException: No matching mode available.
	at eu.darken.sdmse.common.files.local.LocalGateway$lookupFiles$3.invokeSuspend(Unknown Source:176)
	... 7 more
```

**Comment by d4rken** [comment]
Thanks for the report. Hm, full setup , right?

I'll try to find an Android 10 device to reproduce.

Maybe the direct lookup of the storage root fails, but listing the content is possible 🤔

If you go into setup, then menu and views the data areas, what SD CARD types are detected?

(Or do a debug log then this info will be contained)

**Comment by uli-on** [comment]
Re setup: The setup is probably not been completed, but can't remember exactly for the time of the crashes, once I've been annoyed enough by the app repeatedly reminding me to activate the activeated(!) accessibility service, that I pushed ignore/hide/dismiss on the dashboard page. Today I have disabled & reenabled acc services for Maid two times, yet there are 2 contradicting notices, 1 green, 1 pink.

Re debug log: I know where to activate, but where can I copy it?

**Comment by d4rken** [comment]
> repeatedly reminding me to activate the activeated(!) accessibility service

Yea this is annoying, there are 3 possible reasons:
* A bug and the service crashes, if happens enough, the system will not restart it until reboot
* The app was updated/replaced
* The system killed the service for "reasons" (usually battery optimizations)

AFAIK the last one is the most common, at least I don't have any automatic crash reports indicating that it's crashing.

**Comment by d4rken** [comment]
The log shed some light on it, so your detected data areas are:

```java
#0 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[]), type=SDCARD, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@4efc081, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
#1 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/3366-3661, segments=[]), type=SDCARD, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@bd6e3bd, flags=[], userHandle=UserHandle2(handleId=-1))
#2 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, data]), type=PUBLIC_DATA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@510bdb2, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
#3 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/3366-3661, segments=[Android, data]), type=PUBLIC_DATA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@b993103, flags=[], userHandle=UserHandle2(handleId=-1))
#4 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, obb]), type=PUBLIC_OBB, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@87af880, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
#5 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/3366-3661, segments=[Android, obb]), type=PUBLIC_OBB, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@712feb9, flags=[], userHandle=UserHandle2(handleId=-1))
#6 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/primary, segments=[Android, media]), type=PUBLIC_MEDIA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@8c902fe, flags=[PRIMARY], userHandle=UserHandle2(handleId=0))
#7 DataArea(path=SAFPath(treeRoot=content://com.android.externalstorage.documents/tree/3366-3661, segments=[Android, media]), type=PUBLIC_MEDIA, label=eu.darken.sdmse.common.ca.CaStringKt$caString$1@af3da5f, flags=[], userHandle=UserHandle2(handleId=-1))
```

Which are all SAF based paths, so SD Maid does not have normal storage access (interesting) and the StorageAnalyzer does not yet do path mapping i.e. "normal path"<>"saf path".

I somewhat expected an issue there, that the app crashes, instead of showing an error dialog, that is unexpected :thinking:

**Comment by d4rken** [comment]
Yeah the crash is here, we get the volume data from the system and the system gives us a normal path that we just (but can't access), and then we crash.

https://github.com/d4rken-org/sdmaid-se/blob/55222a2afe01ea9efc1ec7eeca6da65705b2d62b/app/src/main/java/eu/darken/sdmse/analyzer/core/storage/StorageScanner.kt#L91-L93

**Comment by uli-on** [comment]
> More of an FYI, the accessibility setup stuff is unrelated to this bug.

Yes, but you asked me for completed setup. Thanks for naming the three reasons. I knew I've read something about it but could not remember what and where. 

Meanwhile I deactivated battery optimizations, restarted the device, and there's no incomplete setup indicated any longer. (The crash happens again, though.)
