### ISSUE TITLE
Improvements around debug log

### ISSUE THREAD

**Issue by uli-on** [d4rken-org/sdmaid-se#327]
**Is your feature request related to a problem? Please describe.**
Could not find log harvesting spot in the app.

**Describe the solution you'd like**
- Remove the shrug emoji from the subline in settings and replace by a description of what to find there. 
- Unite log switch and log harvesting spot in one place. 
- Add a mail address or something else for people who don't want to share these information publicly on GH.

**Comment by d4rken** [comment]
The debug log is stopped via notification and when done so, a popup shows that allows you to share the log via any app that supports it.

As the share dialog is not email specific, I don't want to force it to only show only mail apps. For some GitHub is okay, maybe others want to upload to some cloud storage.

> Unite log switch and log harvesting spot in one place.

You mean stop the recording from the same setting that started it?

**Comment by uli-on** [comment]
OK, I mixed up the Test log in Debug modus and the Debug protocol. Remains to swap out the Shrug emoticon for something more telling.

Will have to make friends with the debug protocol and see whether that can be made more intuitive because the log I just mailed you is from another time. I hope the info you asked for in #326 is still contained.

**Comment by uli-on** [comment]
OK, with some more time I've looked at the whole stuff that made it so hard for me to get my head around re Debug log. 

The shrug emoticon should - as already said - be replaced by a more meaningful subline with the other items that can be found in the Support section. This way, one would be more tempted to tap on that section when browsing the prefs for the first times. 


If you do open the "Support" section, but mistakenly tap on "Install ID", the window that pops up overlaps the "Debug log" section to a large extent on smaller screens. There should be more room for scrolling at the bottom of the page in order to solve this.


The dialog that opens when you tap "Debug log" has the word "Continue" instead of "Start logging" or "Start recording" as the start button. The latter ones would be clearer as well as more meaningful. 


After tapping "Continue", a notification opens that does not indicate that it is from SD Maid. It says "Debug log" and "Loading". Loading? Not Recording or Recording started? 
Design-wise and with the notification sound it could just as well be any error message. Only when you pull down the notification drawer, it shows that it probably comes from SD Maid. 


There is also room for improvement in the now finalized notification (i. e. the one you see when pulling down the notification drawer): Instead of just displaying "Debug log", one could be informed here: "Debug log is being recorded". And instead of the "Done" button, a "Stop recording" or "Stop logging" would be more informative.

**Comment by d4rken** [comment]
Thanks for the feedback, I like your suggestions. I admit that I didn't spend a lot of effort on the UX of the debug log as I thought "it's just a debug log". Making it easier for people to report issues easily is important.

**Comment by uli-on** [comment]
BTW, if it is possible to display a notification that doesn't differ from the "final" one, i. e. show e. g. a "Stop recording" button already when the notification comes up for the first time, it would be even more obvious what's just going on. As excessive as that might sound to the developer, for the first time users it helps a lot to be guided.

**Comment by d4rken** [comment]
> Add a mail address or something else for people who don't want to share these information publicly on GH.

Any suggestions besides email?
While I'm okay to receive emails with logs, placing any easy way to email within the app, causes people to send me emails that look like they sad naked on the phone screen and accidentally mailed me...
In fact I still get such emails that only contain debug info from 7 year old builds of SD Maid 1...
