### ISSUE TITLE
restore deleted system adds

### ISSUE THREAD

**Issue by lompaket** [d4rken-org/sdmaid-se#328]
Could you add functionality to reinstall system apps that you removed pls?

**Comment by d4rken** [comment]
SD Maid SE doesn't support removal or re-install of system apps AFAIK?

**Comment by d4rken** [comment]
App uninstall is planned, but not re-mounting to support system uninstall.

Re-installing would require too much file explorer functionality, I think this grows the app scope too much.

**Comment by lompaket** [comment]
I accidentally deleted com.android.server.telecom bruh and can get it back working
