### ISSUE TITLE
Add Spotify to Specific Filter area under AppCleaner

### ISSUE THREAD

**Issue by emtee40** [d4rken-org/sdmaid-se#343]
When running AppCleaner the longest part is under Spotify. Spotify clearly has a lot of data and I've added it to exclusions, but seeing the apps included in the Specific Filter area in settings, I thought it'd be nice to have "Skip Spotify" option.
I do clear Spotify every now and then but I got to manually go into app settings and do it myself. It'd be nice to have 4 taps instead of 8 taps to clear it's cache.

**Comment by d4rken** [comment]
Hm, the AppCleaner options are for "inclusions", to pick up additional files. Creating extra "exclude" option kinda duplicates the existing exclusion feature...

I think the Spotify cache falls under the "offline cache" filter, if you disable that it should no longer scan it.

Creating a list of exclusions that can be toggled would probably end up just with a list of dozens of apps, with everybody wanting a different app to have a default exclusion that can be toggled, not something I'd like to maintain...

**Comment by Eloutmanixx** [comment]
Hello welcome
