### ISSUE TITLE
Wont clean Cache on Samsung A53 5G

### ISSUE THREAD

**Issue by NotCaptainRex** [d4rken-org/sdmaid-se#376]
- Device: [SamsungA53 5G]
 - OS: [Android 13]
 - Root status [/]
 - SD Maid 2/SE version [0.8.2-beta0]
[eu.darken.sdmse_logfile_1686221930180.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11687230/eu.darken.sdmse_logfile_1686221930180.log.zip)

**Comment by d4rken** [comment]
Can you elaborate? Looks okay on first glance:

```java
D/SDMSE:Automation:AppCleaner:ClearCacheModule: Cleared default primary cache in 1473ms for NormalPkg(packageName=com.brave.browser_beta, userHandle=UserHandle2(handleId=0))
```

**Comment by NotCaptainRex** [comment]
I will send a screenshot that is not work give me 3 min

**Comment by NotCaptainRex** [comment]
![Screenshot_20230608_173744_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/135971905/cb558af4-f6cf-40d8-aa82-e2127b88ed35)

After the "clean"
![Screenshot_20230608_173802_Settings](https://github.com/d4rken-org/sdmaid-se/assets/135971905/d80a78f9-27e1-430e-8306-9bb6c6138ae5)

**Comment by NotCaptainRex** [comment]
Maybe its a Samsung problem I try to manually clean the cache but after 4sec the cache was back

**Comment by NotCaptainRex** [comment]
Idk I will report the problem to the Samsung support maybe they can help

**Comment by d4rken** [comment]
Really doubt they care...

Could be files that are in use, that are locked by a process.
Try force stopping or rebooting and then again.

Closing here as not an SD Maid issue, but I appreciate the quick report with a debug log ❤️
