### ISSUE TITLE
App language switch option

### ISSUE THREAD

**Issue by kaozaza2** [d4rken-org/sdmaid-se#378]
Can you make app language switch in settings?, or add support per-app language preferences (Android 13)?

**Comment by d4rken** [comment]
Is there an issue with the translation SD Maid uses by default?

**Comment by kaozaza2** [comment]
I'm just need English language sometimes, like search any community help.

**Comment by DRYN07** [comment]
+1 for this. My language is one of the hardest in the world and in most cases the translations are weird. I use every app/software in English so it would be awesome if at least there would be a "force English" mode or something :)

**Comment by H4ckerxx44** [comment]
+ 1 for this also, huge pain in the butt when apps default to device language with no ability to change it.

**Comment by H4ckerxx44** [comment]
The update 0.17.2 unfortunately did not solve this problem for me.

I am on Miui 14 (xiaomi.eu) which does not feature a language switch for individual apps.

Easiest would just to be able to set the language in the app instead of requiring the operating system to support some feature which android-based OSs do not have.

**Comment by H4ckerxx44** [comment]
This is still an issue on 0.18.2.

Will this ever be changed (message above), or am I stuck with german?

Would be great if you could comment on that @d4rken

**Comment by d4rken** [comment]
@kaozaza2's idea is implemented

> or add support per-app language preferences (Android 13)?

I can think about adding an additional switcher but please discuss this in a new ticket.

Do you think that MIUI will sooner or later adopt the OS level language switcher?

**Comment by H4ckerxx44** [comment]
> @kaozaza2's idea is implemented
> 
> > or add support per-app language preferences (Android 13)?
> 
> I can think about adding an additional switcher but please discuss this in a new ticket.
> 
> Do you think that MIUI will sooner or later adopt the OS level language switcher?

No idea. I searched for it but the only answer I found about xiaomi.eu (the "fork" I use) is: "No one knows."

But alright, I will write about a new issue.
