### ISSUE TITLE
Some system applications, the cache is not cleared

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/sdmaid-se#383]
first click on "clear cache" instead of "clear"

miui 13.0.5 android 12

As you can see, these applications are system applications, and their cache is not deleted (because they stayed on the list)
![767f4e66-2750-436e-9ec9-7362d25a8651.jpg](https://github.com/d4rken-org/sdmaid-se/assets/113500363/e87a41e7-a719-466a-b8d9-a26329475b07)
(catima accidentally appeared there)

I can do it manually, but that's not a good option.

**Comment by d4rken** [comment]
Can you provide screenshots of the difference between these apps and the other "normal" apps?

**Comment by d4rken** [comment]
> Can you provide screenshots of the difference 

☝️

**Comment by Panas1989** [comment]
![Screenshot_2023-06-12-23-27-06-951_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/100944730/c207f8a6-cb58-4af1-b310-d1b720869a9d)
![Screenshot_2023-06-12-23-26-56-344_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/100944730/e5e49d2a-f026-449f-ab97-304bc608e9f1)
![Screenshot_2023-06-12-23-26-43-122_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/100944730/f2f1e701-7a45-4049-81f3-bfccdde0a459)

**Comment by E0697** [comment]
I have a similar problem with RealmeUI. But the remaining applications have the "clear cache" button greyed out in the app info. Only a few apps (3 - 4).

**Comment by buggad** [comment]
Are thees devices destroyed for ever ?
I don't se the fun i tv this
I have an rauter sagem (c1 hub @ 750 fast) that my former best freind hav
added a untubu script so it's useless it's very valuable to me
So if you know what to do to remotely
Reset it be my geust i will pay you 50€
Pronto if you can get it to work
Then I can move on and reipar the other units
If you wanna give it a try i will connect it and give you the info you need
to
Reset it remotely
Regards Micael vid

ed90

Den fre 16 juni 2023 11:36Issa ***@***.***> skrev:

**Comment by d4rken** [comment]
> Have the same problem on MIUI 14 android 13. Some apps only have "Clear cache" button. In logs there is an exception: "Got 'Clear cache' instead of 'Clear data' skip the action dialog step". 5 retries or so and SD Maid fails to delete these applications' cache

Thanks, that's an important hint.

So it seems like the behavior to switch to a different UI interaction path is not working correctly:

https://github.com/d4rken-org/sdmaid-se/blob/2b08f57eb75861d7086c293542cbe7a14f414b2e/app/src/main/java/eu/darken/sdmse/appcleaner/core/automation/specs/miui/MIUISpecs.kt#L214-L217

That code does look a bit off, might be a from the rework I did for #339 :thinking:

**Comment by d4rken** [comment]
So I think have a solution for this so that SD Maid correctly switched to the alternative accessibility steps.

SD Maid will do does this, if it is a device admin app (see #242) or if SD Maid encounters "clear cache" instead of "clear data". I'm wondering if SD Maid should just assume that there will be "Clear cache" if the app is a system app, or are there any system apps where this is not the case? (What about updated system apps)

---

> I have a similar problem with RealmeUI. But the remaining applications have the "clear cache" button greyed out in the app info. Only a few apps (3 - 4).

This might require a new issue ticket. It will require some kind of logic to determine what to do if the button is greyed out, skip it? wait?

**Comment by d4rken** [comment]
Not impossible, with the decision making I added in #339 it should be possible to have SD Maid just decide dynamic, depending on what the button says. Not sure how fast that is as I don't have a device to test with. Starting with the right steps will be faster but if that isn't possible, a bit slower would be better than not at all?

So let's just try and you could report back your experience after the next update.

**Comment by E0697** [comment]
> > I have a similar problem with RealmeUI. But the remaining applications have the "clear cache" button greyed out in the app info. Only a few apps (3 - 4).
> 
> This might require a new issue ticket. It will require some kind of logic to determine what to do if the button is greyed out, skip it? wait?
> 

It currently waits a bit then skips these apps. I'd say it's relatively fast (a couple more seconds than usual), but I guess it could be sped up by skipping them.

**Comment by d4rken** [comment]
Yeah 0.10.4 was the version that was supposed to fix it. The step abort is still triggering the retry mechanism instead of skipping the step. :frowning_face:
