### ISSUE TITLE
Shizuku support

### ISSUE THREAD

**Issue by ThePBone** [d4rken-org/sdmaid-se#39]
It would be great if this app could have optional support for Shizuku (for non-root devices), which allows developers to use system APIs with elevated permissions using ADB. This requires the user to download the Shizuku app from Play or F-Droid and set up local ADB access using Wireless Debugging, so no PC is required (except on older Android versions).

Website: https://shizuku.rikka.app/
GitHub: https://github.com/RikkaApps/Shizuku

By using Shizuku to run custom code as the `shell` user (uid 2000), you basically inherit all [(protected system) permissions](https://android.googlesource.com/platform/frameworks/base/+/dd52778afbd3c4adbd792a151cf74bd6c58557d8/packages/Shell/AndroidManifest.xml#26) the `com.android.shell` package has. Which allows doing stuff like:
* Using `android.permission.CLEAR_APP_USER_DATA` and `android.permission.CLEAR_APP_CACHE` to clear caches & data much faster without using the accessibility service, which would also allow running that in the background
* Unrestricted (fast) file access on Android 10+
* Allow users to enable/disable apps in the 'AppControl' feature
* Automatically set up & grant all the permissions (accessibility service, all files access, etc...)

**Comment by Shkzeen** [comment]
Shizuku ***is*** listed in the libraries used, but I was unable to find a method to enable it.

**Comment by Bingblop** [comment]
Shizuku or general adb support would definitely take this application to the next level. Currently, it has a lot of cool features, but without adb, it'll never be enough on its own.

**Comment by KhazAkar** [comment]
Additionally, some ROMs have rooted ADB support, which basically will unlock all possibilities of root + more.
