### ISSUE TITLE
When sd maid se is working, it is not possible to answer the call, you have to wait for the end of sd maid se

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#402]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Calls cannot be answered when sd maid se is working.
> Mornings in Sweden are always very cold and I'm not an early bird.
I wanted to improve the work of sd maid se by stopping it during work, when there is an incoming call. The ability to answer calls
**Describe the solution you'd like**

> I would like it if SD Maid could make me coffee in the morning.

**Describe alternatives you've considered**

> I have considered making the coffee myself but both me and myself decided against it.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys getting a hot beverage on a cold morning.

**Additional context**

**Comment by d4rken** [comment]
You don't have to wait until the end though, can't you press cancel?
