### ISSUE TITLE
Clearing cache via accessibility service does not work on Android 11 GO

### ISSUE THREAD

**Issue by Yamir1914** [d4rken-org/sdmaid-se#416]
Hello but sd maid 2 also does not clear cache or stop anything in android 11 go thanks

**Comment by d4rken** [comment]
Please record and share a debug log of the app cleaner failing:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

"Urgent" is not a good title :wink:

**Comment by Fasto5** [comment]
I second this - App Cache Cleaner (free version) was able to clean 1GB of cache data that SD Maid SE (Paid version) couldn't clean.

I tried cleaning multiple times with SD Maid SE (all permissions granted) and also tried after a rebtood.

App Cache Cleaner (free ver) still found apps that were not properly cleaned.

**Comment by Fasto5** [comment]
I'm not sure a log is going to capture what the app can't seem to clean, if it thinks its done its job properly.

**Comment by d4rken** [comment]
I don't have an Android 11 GO device. Without a log file, I'd have to guess what to fix :shrug:.

In most cases SD Maid is not finding some labels to click, the log file will show what SD Maid sees on the screen.

**Comment by Gu57avo** [comment]
I don't know if this is an Android 11 issue, I'm on Android 10 and have the same issue (I think anyway). I have the logs below 👇
[eu.darken.sdmse_logfile_1688752369646.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11984650/eu.darken.sdmse_logfile_1688752369646.log.zip)

**Comment by d4rken** [comment]
> I don't know if this is an Android 11 issue, I'm on Android 10 and have the same issue (I think anyway). I have the logs below point_down [eu.darken.sdmse_logfile_1688752369646.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11984650/eu.darken.sdmse_logfile_1688752369646.log.zip)

Thanks for the log. Is this an Android GO device?

Can you tell me more about your device? Looks a bit weird in the log.

* It says it's a Pixel5
* Running Android 10 (pretty outdated ROM?)
* System accessibility settings contains something from MIUI gamebooster?
* AppCleaner thinks it's a Samsung device :exploding_head: 

The core issue is that SD Maid uses the wrong label. SD Maid looks for `Storage` but needs to find `Storage & cache`. Because SD Maid for some reason thinks it's a Samsung device... :question:

**Comment by Gu57avo** [comment]
It's a custom ROM on a Samsung device, that's probably why, I'm using an AOSP based ROM, and it also probably has some pixel feature somewhere that it needs to report a pixel to work.

**Comment by Gu57avo** [comment]
And on it being outdated... The last official version for this device was 8.1.0 lol

**Comment by d4rken** [comment]
> It's a custom ROM on a Samsung device, that's probably why, I'm using an AOSP based ROM, and it also probably has some pixel feature somewhere that it needs to report a pixel to work.

That's a tough thing to support. And probably not the same issue as @Yamir1914 which is specifically Android GO related.

@Gu57avo You could create a new ticket and we try to find something that works. Your ROM has a specific UI setup, e.g. Samsung or AOSP or MIUI settings UI layout + texts. SD Maid needs to find the right one for your device. Normally SD Maid detects this through the `Build.MANUFACTOR` variable.

**Comment by d4rken** [comment]
Closing due to not enough info. I don't have Android 11 Go and no one was able to provide debug logs.
