### ISSUE TITLE
Support Sui

### ISSUE THREAD

**Issue by rollingmoai** [d4rken-org/sdmaid-se#431]
Continuation of #39. Since SD Maid supports [Shizuku](https://shizuku.rikka.app/), it might as well also support [Sui](https://github.com/RikkaApps/Sui), which uses the same APIs as Shizuku.

https://github.com/RikkaApps/Sui

**Comment by d4rken** [comment]
What is the advantage over what SD Maid already has?

We already use a root launched java service.

https://github.com/d4rken-org/sdmaid-se/blob/9e16bc92c61a269ab3e43cbdb897ee0c13df8054/app-common-root/src/main/java/eu/darken/sdmse/common/root/service/internal/RootHostLauncher.kt#L31

It's actually partly based on multiple similar libraries including Sui:
* [Sui](https://github.com/RikkaApps/Sui) & [Shizuku](https://github.com/RikkaApps/Shizuku) from @RikkaW
* [MaterialFiles](https://github.com/zhanghai/MaterialFiles) by @zhanghai
* [librootjava](https://github.com/Chainfire/librootjava) by @Chainfire
* [VPNHotspot](https://github.com/Mygod/VPNHotspot) by @Mygod
* [libsu](https://github.com/topjohnwu/libsu) by @topjohnw

Whether the service is launched via Magisk or Sui shouldn't make a difference, right?

If my code breaks down (I'm not as experienced as Rikka or John Wu in this area) then we could switch to make maintenance easier, but currently it works on all Android versions AFAIK.
