### ISSUE TITLE
No Android/data and Android/obb access 

### ISSUE THREAD

**Issue by gaich** [d4rken-org/sdmaid-se#432]
Android 13 doesn't allow Android/data and Android/obb access for external apps. If you have no root, you can't do anything to make SD Maid work properly.

https://github.com/d4rken-org/sdmaid-se/assets/3396847/ec464996-6926-47e7-a79a-eea59aaf33bd

[Screenshot_20230628_063419_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/3396847/d1005aac-05bc-4d0b-8554-9220c7602abd)

**Comment by gaich** [comment]
The same thing with other apps. Only the built-in file manager can access this. The problem is that many media files, Telegram images, for the instance, are in Android/data. And now I cannot clean these folders with the SD Maid filters I've created for messengers. And there's no root options for new Huawei phones. EMUI 12 (Android 12) granted the access without any problems and without root. Of course, I can clean manually, but I have always relied on SD Maid in this case.😊

**Comment by d4rken** [comment]
~~It's weird that the setup for card for SAF (storage access framework) based access shows for you. It should not show on Android 13 (API33+) because it's not possible to select anything.~~

Ah, I now noticed you have v0.7.10, this is a very old build, please update :grin:.

The latest update (v0.10.0) adds support for [Shizuku](https://shizuku.rikka.app/guide/setup/). If you set this up, SD Maid should be able to access `Android/data` again.

**Comment by gaich** [comment]
Even with Shizuku it doesn't have access...🤔

https://github.com/d4rken-org/sdmaid-se/assets/3396847/ba72205e-18d5-4f0c-b8ae-3fcfbae443d7

**Comment by d4rken** [comment]
Sorry I wasn't clear.

Shizuku will not change that setup card. The setup card is to set up SAF access.
But with Shizuku SD Maid should be able to read Android/data without using the SAF, so the setup shouldn't be needed.

If SD Maid accesses the files through the Service that is launched by Shizuku, then the files are read with the same permissions as the `adb shell` and during my tests, I was able to access Android/data with that.

Use the StorageAnalyzer, try to find an app with data in `Android/data`, SD Maid should be able to show you the content.

All the different operations in SD Maid have to decide which access method is used for each path. I'm not sure yet if this is working correctly with Shizuku in every case, but in theory, SD Maid should be smart about this, might need a few bug reports though :grin:.

This is on a Pixel 5 with Android 13, no root, but Shizuku:

[2023-06-28 21 19 00](https://github.com/d4rken-org/sdmaid-se/assets/1439229/5723433f-9d11-4d47-8dcb-ddef5d45fd05)

---

On a side note, can you get me a debug log for:
* Start debug log
* Force stop SD Maid
* Open SD Maid
* Open Setup screen

I think it's a bug that you are being shown the setup card for SAF on Android 13.

**Comment by buggad** [comment]
Im 61 yers old and my "bff" cleaned out my bank acconts 4000€ I have
nothing left and my sandbox you fixed it so Iv was down graded from 29 to
28 so I cant fix my divices and what i think if I entepred right
You stop my automatik upgrade from android 10 to 12 maybe I read it wrong
But My Rauter is destroyd by my former bff conny Telander just becouse he
could
So Im help less whith out youre help
So if you can fix both my diveces and my rauter if i send you the stuff and
you fix them an set up protektion on the router so conny cant acces my
stuff, Something he have done for 18 month
I will pay you for youre service
Regards mlcael vld

ed90

Den ons 28 juni 2023 21:07gaich ***@***.***> skrev:

**Comment by gaich** [comment]
[eu.darken.sdmse_logfile_1687982188100.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11899529/eu.darken.sdmse_logfile_1687982188100.log.zip)

That thing with Shizuku I will repeat later, just turned off my PC, because there is no Wi-Fi debugging in my phone😁

**Comment by d4rken** [comment]
> [eu.darken.sdmse_logfile_1687982188100.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11899529/eu.darken.sdmse_logfile_1687982188100.log.zip)

Thanks.

> Android 13 doesn't allow Android/data and Android/obb access for external apps.

You have Android 12, not 13:, theoretically granting SAF access should be possible.

```
HUAWEI/MNA-L29/HWMNA:12/HUAWEIMNA-L29/103.1.0.154C10:user/release-keys
```

So either Huawei is reporting the API Level wrong, or has made additional changes from normal Android 12 :thinking:. On my Samsung with Android 12 it works as expected.

**Comment by gaich** [comment]
[eu.darken.sdmse_logfile_1688054579007.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11908013/eu.darken.sdmse_logfile_1688054579007.log.zip)
This is the log with Shizuku connected. Nothing changes. Maybe you're right, something in Huawei is wrong. Still no access.
![Screenshot_20230629_190107_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/3396847/95c5a717-7c06-4cf7-beab-4733138779f5)

**Comment by d4rken** [comment]
Screenshot: `/data` and `/system` will not be accessible via Shizuku, only with root.

> Use the StorageAnalyzer, try to find an app with data in Android/data, SD Maid should be able to show you the content.

But you should be able to access `/storage/emulated/0/Android/data`.
To go there you have to go
Storage Analyzer > Primary Storage > Apps > App > App Data

**Comment by buggad** [comment]
Most off the bad system apps have no hasch may by that's a way to sort out
some importent system files so this shit breaks down
If you check hasch on all app's the one that have non delete forever
Maybe this monster hack will break down
If it's missing all these no hasch apps
I have no clue it was just an stupid ide
Forget it
Thanks for the updates on this matter
I had to reset my Xperia 18 hours ago
So I'm not inspired to do what I need to
Regards mike

ed90

Den ons 28 juni 2023 08:23gaich ***@***.***> skrev:

**Comment by gaich** [comment]
> 
![Screenshot_20230629_194203_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/3396847/bf716946-1a40-486a-9afd-5e5ce91aa10b)
It seems that it works

**Comment by d4rken** [comment]
Awesome :beers:
