### ISSUE TITLE
WriteException error while deleting deleted apps remain

### ISSUE THREAD

**Issue by djocqer** [d4rken-org/sdmaid-se#44]
Literally my first bug report on github, I'm sorry if it is incorrect. 

[Screenshot_20230327-233529_SD_Maid_SE](https://user-images.githubusercontent.com/35299809/228009140-dbbafcc0-b359-451d-b428-cc66c4555240.png)
[Screenshot_20230327-234046_SD_Maid_SE](https://user-images.githubusercontent.com/35299809/228009154-c436d96e-b82b-4902-8398-92f7c2391425.png)
[Screenshot_20230327-234053_SD_Maid_SE](https://user-images.githubusercontent.com/35299809/228009160-3b96155b-658b-4692-90dc-bebb64397c99.png)

**Comment by d4rken** [comment]
Thanks. Does this happen every time?

Could you tell me which phone, Android version and Magisk version you have?

If it happens every time, or regularly, can you try to capture this in a debug log? (Settings > Support > Record debug log)

**Comment by djocqer** [comment]
1. It does happen every time
2. Xiaomi Pocophone F1, Pixel Experience Plus 11, Magisk 981ccabb (25210)

**Comment by djocqer** [comment]
I Still have the same problem on Beta 0.6.10-rc0 🤔

**Comment by d4rken** [comment]
@djocqer Can you get me a fresh log of it?

**Comment by djocqer** [comment]
> Thanks, working on it. Please don't attempt any more CorpseFinder deletions I think you are getting false-positive CorpseFinder results where SD Maid SE doesn't detect owners correctly for apps installed in a second?work? profile.

Sure! I use SD Maid SE only to test for bugs because I really appreciate your work on OG SD Maid 🙏

**Comment by d4rken** [comment]
Should be fixed by #123

**Comment by d4rken** [comment]
Contacts and telegram are found in the secondary user profile, does it also have these apps installed?
Paypal I'm not sure, is it installed?


Can you get me a log?

**Comment by d4rken** [comment]
* Start log recording
* In the debug card click "reload apps" (or force stop SD Maid)
* Do a scan with the CorpseFinder
* Send me the log

But wait ~20min there is a bug with the debug log sharing (#155), (or you manually extract the log from SD Maids path).

**Comment by d4rken** [comment]
Corpse on `com.google.android.contacts` seems accurate at least with regards to SD Maids package data.
It's only installed for UserHandle 0, the main user.

Same for `org.telegram.plus`

Paypal app is installed though
`CacheKey(pkgId=com.paypal.android.p2pmobile, userHandle=UserHandle2(handleId=10))`  
that seems to be a false positive. It's only installed for the second user, not the main user, but since public external storage is shared, this shouldn't be a corpse as it has an owner.

**Comment by d4rken** [comment]
I think #61 is actually fixed though.

For the paypal app I've opened #156

I think contacts and telegram corpse is correct. I'd expect more corpses if the secondary user data wasn't retrieved correctly. The log looks very good in that regard.
