### ISSUE TITLE
Accessibility service is disabled for security in Android 14 beta

### ISSUE THREAD

**Issue by Atri7** [d4rken-org/sdmaid-se#456]
**Describe the bug**
I cannot enable SD Maid SE's accessibility switch in 14 Beta on my friend's Pixel 7. It's disabled for security.

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - Root status unrooted
 - SD Maid 2/SE version latest beta

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Does this help?
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-appops-restrictions
