### ISSUE TITLE
Color os 13.1 Cleaning the cache is software that jumps to no cache or no cache cleanup

### ISSUE THREAD

**Issue by Fishheadrabbit** [d4rken-org/sdmaid-se#457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
Color os 13.1 Cleaning the cache is software that jumps to no cache or no cache cleanup
![Screenshot_2023-07-01-04-00-15-70_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/d4rken-org/sdmaid-se/assets/105645188/629ea1de-a826-4cad-ad62-dfbb7d18f109)
![Uploading Screenshot_2023-07-01-04-02-02-52_3aea4af51f236e4932235fdada7d1643.jpg…]()

**Comment by Fishheadrabbit** [comment]
Video

**Comment by Fishheadrabbit** [comment]
Uploading Record_2023-07-01-04-04-32.mp4…

**Comment by Fishheadrabbit** [comment]
Uploading Record_2023-07-01-04-04-32.mp4…

**Comment by Fishheadrabbit** [comment]
[video ](https://b23.tv/IgUqwNU) about video

**Comment by d4rken** [comment]
I have trouble recognizing the screen in the video.

Are you saying that the "Clear cache" button is missing? On some of the apps?

Is it only system apps?

Can you record a debug log?

https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by Jung47** [comment]
มีปัญหาเกี่ยวกับการแจ้งเตือน..รันไทม์..ไม่จำอะไรสักอย่าง..จะลบอย่างเดียวแต่ความจำไม่ลดตามทำอะไรไม่ได้เลย..อ้างความจำเต็มอย่างเดียว..พอทำกิจกรรมเสร็จลบความจำจะติดตั้งแอฟฟิเคชั่น..รีโหลด..ความจำเต็มเหมือนเดิม..ปุ่มล้างแคชไม่หายล้างได้แต่ไม่ลดความจำ..ถึงลดก็ลดตอนแรกอันน้อยนึกไม่เท่าที่แสดงไว้และก็เต็มเหมือนเดิม
