### ISSUE TITLE
Crash on full storage

### ISSUE THREAD

**Issue by Mafiadoener36** [d4rken-org/sdmaid-se#458]
SD Maid SE will crash/force close if the storage is 100% full and 0 bytes are free. 
This wasnt/isnt the case with OG SD Maid. 
SD Maid SE will work/launch again when some storage is available again. 
Could potentially have something to do with the giant cache file ( https://github.com/d4rken-org/sdmaid-se/issues/459 ) / something overflowing and causing the fc? 

 - OS: AOSP 11
 - Root status: SDMaid SE runs as root
 - SD Maid 2/SE version: 0.10.2-beta0

**Comment by d4rken** [comment]
Can you get the stacktrace of the crash?
