### ISSUE TITLE
Giant/500mb cache file

### ISSUE THREAD

**Issue by Mafiadoener36** [d4rken-org/sdmaid-se#459]
SD Maid SE creates a >500 mb cache file @ "data/user/0/eu.darken.sdmse/cache/tmp123.tmp". 
Funnily this is found and cleared by OG SD Maid. 
I deleted the file as i needed storage, but if required can try to recreate it to look at its content. 

 - OS: AOSP 11
 - Root status: SDMaid SE runs as root
 - SD Maid 2/SE version: 0.10.2-beta0

**Comment by d4rken** [comment]
> I deleted the file as i needed storage, but if required can try to recreate it to look at its content.

That would help me. I'm not sure what would create this. The debug log file is created in `Android/data` not in private storage.

The FOSS build has an update checker http cache, but that is under `http_base_cache`.

The Google Play build has Bugsnag which may create some cache?

Which build are you using?
