### ISSUE TITLE
Shizuku not clearing default caches via `trimCaches`

### ISSUE THREAD

**Issue by Wjxfi** [d4rken-org/sdmaid-se#460]
shizuku does not clear the cache of regular apps.

miui 13.0.5 android 12 0.10.3-beta0

**Comment by d4rken** [comment]
Does the accessibility service get stuck, like #383 ? Or does it not run?

Can you elaborate, provide a video or a log?

**Comment by d4rken** [comment]
Note: Shizuku can't clear the cache of system apps, for this SD Maid still needs to use the accessibility service.

**Comment by d4rken** [comment]
Can you show me a video of the behavior?

If you disable system apps in AppCleaner settings, how does it behave then?

**Comment by emtee40** [comment]
I got the same issue with Shizuku also. I've never used Shizuku before so I've spent the last week or so trying to figure out if it was my implementation being wrong or a bug.

I'm using a TCL 30 xl budget phone with Android 12.

**Comment by d4rken** [comment]
@emtee40 I still don't know though what the actual issue being reported here is. Can anyone show me a video or give step by step instructions?

**Comment by d4rken** [comment]
Please provide a debug log of this.

The idea is that Shizuku can call `trimCache` with a huge value like 99TB and force the system to delete all caches and try to make this amount of space available.

**Comment by E0697** [comment]
> The idea is that Shizuku can call `trimCache` with a huge value like 99TB and force the system to delete all caches and try to make this amount of space available.

Does this respect exclusions?

**Comment by d4rken** [comment]
> Does this respect exclusions?

No. Exclusions are an SD Maid thing. `trimCaches` is a broad system request that does not take further options. We have no control over which cache is deleted by this, we just know it will be the default public/private caches of apps.

**Comment by emtee40** [comment]
Here’s a video of the bug.

https://file.io/sT8NZrRTRcqM

**Comment by d4rken** [comment]
> Here’s a video of the bug.
> 
> https://file.io/sT8NZrRTRcqM

Which apps did the AppCleaner find in the results?

Can you get me a debug log?

**Comment by E0697** [comment]
It's been deleted.
A log would be very useful too.

**Comment by d4rken** [comment]
> It's been deleted.

There results were deleted? So it is working?

**Comment by E0697** [comment]
> > It's been deleted.
> 
> There results were deleted? So it is working?

No, I should've quoted. Sorry.
The link to the video posted above says it's deleted.

**Comment by d4rken** [comment]
I saw the video, after running delete, the same results were found. It didn't show the apps though, that's why I asked.

My current ideas are:

* System apps are among the results and those are not deleted by `trimCaches` though then it's bug that the accessibility service didn't trigger
* The data that SD Maid gets from the system has not been updated yet. I don't think I can force it to refresh that data :thinking:. Should we make SD Maid wait until the data is updated? :thinking:

**Comment by E0697** [comment]
I just tried testing Shizuku.
It worked as expected.

The app list however wasn't updated initially. It only updated after the accessibilty automation finished deleting system apps cache.

**Comment by Havokdan** [comment]
Doesn't Miui have the habit of closing the app's accessibility function on its own? The same thing happens with the "developer options" function, I always have to deactivate them and activate them again, so that the app works normally.

**Comment by d4rken** [comment]
> I just tried testing Shizuku. ~It worked as expected.~ The app assumed that trimCaches worked, but it actually didn't. It excluded user apps from the automation service. Here's the [log](https://www.swisstransfer.com/d/3f6b3762-d195-43da-8d04-bfb04c0443ba)
> 
> The app list however wasn't updated initially (after running trimCaches). It only refreshed after the accessibilty automation finished deleting system apps cache.

SD Maid will not update any of the results if a task fails and a scan has to happen to determine the new state correctly, e.g. if half of the files were deleted and then an error happened, the displayed list will not be correct until re-scanned.

> It excluded user apps from the automation service.

SD Maid always excludes user apps from the ACS when using `trimCaches` beforehand.

In the log Shizuku executed `trimCaches`, whether it worked or not is not clear, at least there was no error on SD Maid's end. I will improve this for the next update and let SD Maid wait until the system actually deleted something. We should be able to do this by checking the sizes until it drops below 75% of what the cache sizes were before.

Or we could go further and check this on an individual app level and for those apps where `trimCaches` did not make a difference, we include them again for clearing via ACS. :thinking: 

@E0697 

In that log it shows that despite SD Maid having SECURE_SETTINGS access, it was not possible to launch the accessibility service.
It looked like it failed 3 times and then worked the last time.
Do you know why that happened?

**Comment by E0697** [comment]
I'd say the latter option (per app basis) is better, if it is efficient enough.

The accessibilty service was malfunctioning (as reported by the system). It happems occasionally and I have to turn it off then on again to fix it.
It affects other apps as well, so I assume it's the OS to blame.

**Comment by d4rken** [comment]
> The accessibilty service was malfunctioning (as reported by the system). It happems occasionally and I have to turn it off then on again to fix it.
It affects other apps as well, so I assume it's the OS to blame.

Hm, I've made some changes in #510 so SD Maid tries this, maybe it helps.

> I'd say the latter option (per app basis) is better, if it is efficient enough.

Added this in #513, though for some apps I've noticed that the system does not update the usage information :frowning_face:.

**Comment by E0697** [comment]
> Hm, I've made some changes in #510 so SD Maid tries this, maybe it helps.
That's great!
> Added this in #513, though for some apps I've noticed that the system does not update the usage information :frowning_face:.
-Well that's good enough. Thank you!
