### ISSUE TITLE
App cannot load when use Shizuku

### ISSUE THREAD

**Issue by HuyMaster** [d4rken-org/sdmaid-se#469]
**Describe the bug**
Not sure if it's by my device or by something else

**To Reproduce**
1. Turn on Shizuku in Settings
2. See error

**Expected behavior**
App can't initialize after I turn on Shizuku mode

**Smartphone (please complete the following information):**
 - Device: Mi 11 Lite
 - OS: Android 13
 - Root status: Rooted - Magisk v26.1
 - SD Maid 2/SE version: v0.10.4-beta0

**Debug log**

**Screenshots/Video**

**Additional context**
If you need any more information I can provide

**Comment by d4rken** [comment]
Can you provide a debug log from SD Maid?
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by HuyMaster** [comment]
> Can you provide a debug log from SD Maid?
> https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

My bad. After I restarted the phone it was able to run normally
