### ISSUE TITLE
Free space eraser

### ISSUE THREAD

**Issue by shuvashish76** [d4rken-org/sdmaid-se#47]
Feature similar to [Extirpater](https://gitlab.com/divested-mobile/extirpater) _| [F-Droid](https://www.f-droid.org/packages/us.spotco.extirpater/)_ OR desktop program [Bleachbit](https://github.com/bleachbit/bleachbit) _| [Features](https://www.bleachbit.org/features)_.

**Comment by d4rken** [comment]
This is out of scope for SD Maid.
