### ISSUE TITLE
Support for arm7

### ISSUE THREAD

**Issue by imgodfrey101** [d4rken-org/sdmaid-se#48]
Can't install on old arm 7 device.

**Comment by d4rken** [comment]
What Android version and device are we talking about?

**Comment by d4rken** [comment]
The issue isn't arm7, but Android 7. SD Maid's minApi is 26 (Android 8). 
SD Maid 1 works very well with Android 7.1.2.

I have no plans to support Android 7 with SD Maid 2, sorry.

https://apilevels.com/
