### ISSUE TITLE
Import exclusions from SD Maid 1

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#5]
Would make it easier for users to switch.

Will need some way of detecting package vs path exclusions, which are treated the same SD Maid 1, but differentiated now.

**Comment by Rokcy98** [comment]
Yeah that would be good

**Comment by Minkiu** [comment]
Unsure if this would fit within this issue, but when having Internal Storage and a MicroSD, it' would be cool to be able to disable one of the two, in my instance I don't want sdmaid to look at all within the MicroSD. Can make a new issue if it doesn't fall under this. Cheers!
