### ISSUE TITLE
Material You Theme

### ISSUE THREAD

**Issue by MohamadBayz** [d4rken-org/sdmaid-se#50]

**Comment by d4rken** [comment]
The UI already uses components/colors and patterns from Material You/3 all over the app. What specifically would you change?

**Comment by MohamadBayz** [comment]
The entire app's color is green, and it doesn't follow the system Color 
This is my system Color
![Screenshot_20230328-142434_SD Maid SE](https://user-images.githubusercontent.com/63660736/228221321-195c1606-07d2-49c6-a265-6b1c340f69d5.png)

And this is the app Color
![Screenshot_20230328-142427_SD Maid SE](https://user-images.githubusercontent.com/63660736/228221363-e53371bd-b340-4541-9669-75590f2019e3.png)

It would be more appealing if it was the same color

**Comment by BROKEN81** [comment]
I also would like to see this as well. There are a lot of apps now that take on system colors.

**Comment by Romloader** [comment]
+1
This is by no mean a priority over actual features in development but would be a very nice touch indeed

**Comment by Vildanoff** [comment]
> The UI already uses components/colors and patterns from Material You/3 all over the app. What specifically would you change?

Use the day/night app style in the base app theme in Android 13 styles by injecting a dynamic material style in the same format as embedded in the basic style
