### ISSUE TITLE
.trash files

### ISSUE THREAD

**Issue by HathewayWill** [d4rken-org/sdmaid-se#503]
**Is your feature request related to a problem? Please describe.**
.trash files are not being removed from gallery Snapchat etc

**Describe the solution you'd like**
Search for hidden files with . In front of them and remove them. .thumbnails .trash etc

**Describe alternatives you've considered**

Used Ubuntu to look for hidden files

**Describe why this would be in the interest of all users**
Hidden files may have sensitive information or things not want to be recovered 

**Additional context**
Nome

**Comment by d4rken** [comment]
Not all dot files can just be removed. For some users they store important files. If you have specific path/app combinations that are being picked up, please provide some concrete paths and apps that own them.

**Comment by HathewayWill** [comment]
The apps that come to mind is the VLC, Gallary, and google photos .trash files
