### ISSUE TITLE
Multiple processed

### ISSUE THREAD

**Issue by HathewayWill** [d4rken-org/sdmaid-se#504]
**Is your feature request related to a problem? Please describe.**
No. Just a feature in the settings on the other app that's not present in this one 

**Describe the solution you'd like**
Add the multi threading option. If it is already there it's not easily found. 

**Describe alternatives you've considered**
Nonr

**Describe why this would be in the interest of all users**
Speeds up process

![Screenshot_20230712_011422_SD Maid.jpg](https://github.com/d4rken-org/sdmaid-se/assets/118180342/f40faa97-f0de-4c42-b48d-47e17e190be6)

**Comment by d4rken** [comment]
SD Maid 2 is already using multiple threads. Increasing the number of threads does currently not yield any performance improvements. SD Maid is mostly limited by IO. Having more tasks waiting on resources only increases memory usage.

The option in your screenshot only had little effect in later Android versions beyond setting it to "2". It's not something users should be worried about and was more of a debug setting.
