### ISSUE TITLE
SD Maid Cannot clear cache on Samsung Device running customROM

### ISSUE THREAD

**Issue by Gu57avo** [d4rken-org/sdmaid-se#511]
**Describe the bug**
SD Maid Cannot clear cache on Android 10

**To Reproduce**
-Open app
-Scan
-After Scan is finished click on clean cache
-App opens settings on a certain app, and cannot find where to click

**Expected behavior**
Cache cleaned

**Smartphone (please complete the following information):**
 - Device: Samsung J7 (2016) SM-J710MN
 - OS: Android 10 (CorvusOS)
 - Root status: Not Rooted
 - SD Maid SE version [Don't remember actually]
**Debug log**
(https://github.com/d4rken-org/sdmaid-se/files/11984650/eu.darken.sdmse_logfile_1688752369646.log.zip)
**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**
There has to be a way to check if a device is running OneUi/MIUI/any other OEM skin instead of just checking for the device manufacturer, cause I can't be the only one that is using an AOSP/LineageOS based android version instead of the OEM one. And also I know there are MIUI ports for devices not made by XIAOMI, so it would be an issue in that case as well.

**Comment by d4rken** [comment]
Can you provide a debug log with the most recent version?

Or use a 3rd party app to show what your ROM reports for the other information fields from `Build.`, e.g. `Build.DISPLAY`, `Build.PRODUCT`.

Generally, we could add a setting where the user can select the ROM type / UI type, but I would really like to avoid that and find an automatic solution.

**Comment by Rothschear** [comment]
> Can you provide a debug log with the most recent version?
> 
> Or use a 3rd party app to show what your ROM reports for the other information fields from `Build.`, e.g. `Build.DISPLAY`, `Build.PRODUCT`.
> 
> Generally, we could add a setting where the user can select the ROM type / UI type, but I would really like to avoid that and find an automatic solution.

This fails in the original SD Maid too for my device. But thankfully that app had the 'Custom accessibility sequence' option. I hope you'll consider adding it to SD Maid SE.

**Comment by Dibirzichka** [comment]
I'm on OnePlus 7T with Crdroid custom ROM 9.8. I used SD Maid/SE on earlier versions as well. It seems the app is missing Storage look up because on my version of the ROM it says "Storage & cache" . App passes by that option couple of times before moving to next app. Which makes me thing it's not working or failing the text recognition. I shared the log file on dicord.

**Comment by d4rken** [comment]
Currently torn between:

* A "custom sequence" input field, which may be difficult to use, and in some cases not be enough to move through menus, if the navigation is too complex.
* A list of all supported ROM types and the user can pick one and override the detection, so SD Maid will use a different approach than the detected ROM type normally uses. The user would have to try which one works.

:thinking:
