### ISSUE TITLE
Fastlane short_description.txt too long

### ISSUE THREAD

**Issue by IzzySoft** [d4rken-org/sdmaid-se#512]
Fastlane `short_description.txt` is limited to 80 chars, Some of yours exceed that limit and will hence be truncated:

* be/short_description.txt has 87 chars
* de-DE/short_description.txt has 83 chars
* vi/short_description.txt has 84 chars

Just as a note to better stay inside and not have them cut off :wink:

**Comment by d4rken** [comment]
Thanks! I've added a limit to Crowdin (thought I did? not sure why it didn't take), and pinged the translators. Fixed the German one myself.

**Comment by IzzySoft** [comment]
Thanks a lot! Happens with other projects at Weblate as well, so :man_shrugging: Thanks for taking care!

**Comment by IzzySoft** [comment]
Hi @d4rken, same story again just this time for `el-GR/short_description.txt` (has 83 chars) :wink:

**Comment by d4rken** [comment]
Hm, has 80 characters here?

https://crowdin.com/translate/sdmaid-se/137/en-el?filter=basic&value=3

**Comment by IzzySoft** [comment]
No idea, my monthly checker just reported the file (it checks the file locally on my machine, not the weblate/crowdin/… settings). Looking at the directory here at Github, it was last updated about 2 months ago, so probably before you introduced the limit at Crowdin? Nope, closer look says "August 2023". Strange: copy-pasting the content from the WebIf here results in exactly 80 chars. Looking at the local file: oof, found the culprit. The `&` gets converted to its HTML-entity (`&amp;`), most likely on "pruning" ("sanity check" to make sure nobody slips in "bad stuff").

Apologies for the "false alert" then – that's indeed something I have to fix on my end.

**Comment by d4rken** [comment]
No worries, thanks for the update.

**Comment by IzzySoft** [comment]
Found where to fix it, hopefully fixed now (decoding entities after sanitizing and before writing the file now for all but `full_description.txt`, which is converted to HTML here), let's see how it goes. Will now manually fix the `el-GR` one so it's not reported again (done).
