### ISSUE TITLE
delete all folder of empty folder

### ISSUE THREAD

**Issue by researchscum** [d4rken-org/sdmaid-se#517]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

> i created a folder 1 inside 1 and so on
sdcard/0/1/1/1/1/1/

if i scan use sdmaid 2/se only result 1 empty directories
sdcard/0/1/1/1/1/1
so i need multiple scan in case it's faraway like whatsapp media and so on.

if i scan use sd maid the result 5 empty directories
sdcard/0/1
sdcard/0/1/1
sdcard/0/1/1/1
sdcard/0/1/1/1/1
sdcard/0/1/1/1/1/1
once i press delete all of them deleted.

**Describe the solution you'd like**

> I would like it if SD Maid 2 / SE could delete it all like SD Maid

**Describe alternatives you've considered**

> I have considered making multiple scan and delete but both me and myself decided it's inefficient.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys getting a hot beverage on a cold morning without the need to click scan and delete multiple times.

**Additional context**
[1689955277885](https://github.com/d4rken-org/sdmaid-se/assets/97543175/ca5bf6a9-0764-4e06-9095-84686cd9f648)

[1689955277887](https://github.com/d4rken-org/sdmaid-se/assets/97543175/efa35e5b-2360-4d99-95b6-1130638f33fa)

**Comment by d4rken** [comment]
Hm I had already added code to allow for this, but seems this is not working 🤔 

https://github.com/d4rken-org/sdmaid-se/blob/faad28f15058b633cc5434cc622ed0d5310b9c32/app/src/main/java/eu/darken/sdmse/systemcleaner/core/filter/generic/EmptyDirectoryFilter.kt#L112-L116

**Comment by d4rken** [comment]
I got it working now for:

```bash
/sdcard/1/1/1/1
/sdcard/1/1/1
/sdcard/1/1
/sdcard/1
```

What about
```
/sdcard/3/1/1
/sdcard/3/2/2
```

Might slow down scan too much 🤔
