### ISSUE TITLE
Andy Android sipping ... water?! 

### ISSUE THREAD

**Issue by n3rdcub** [d4rken-org/sdmaid-se#518]
**Describe the bug**
Compared to your original SDMaid app whenever the accessibility service is triggered (clear app caches) Andy Android had a steaming hot beverage and would move about. This made him feel alive, real, like a living breathing tiny green android thing. 
Now Andy Android lost his steaming beverage, did it cool off between SDMaid OG and SE? Did he switch to Tea? WAS IT TO SEEM COOL? Cuz it worked and now whenever I use SE I get sad, frustrated, my trust is now waivering because what kind of madman goes from coffee to tea?!(which btw is coming along so freaking nicely gj love the shizuku addition)

**To Reproduce**
1. Go to OG SDMaid and attempt to clear app cache. _Observe arm waving and steaming cup of tasty beverage._
2. Open SDMaid SE and attempt the same task
3. **WTFBBQSAUCE11!!1!!one!** It's missing! 
4. See the error of your ways. Contemplate, stew, probably ignore this issue and chuckle about it as you click close then use that YUGE brain to bang out 1 line of code to fix this unusable mess. 

**Expected behavior**
Cup should steam, arms should be flailing like he just don't care, LIFE IN HIS EYES SHOULD BE BEAMING

**Smartphone (please complete the following information):**
 - Device: ~~[e.g. Pixel 9]~~ WAIT... pixel 9 is already out? Oh crap maybe that's why I only have a pixel 7 with GrapheneOS
 - OS: ~~[e.g. Android 17]~~ I'm too poor for Android 17 I only have Android 13
 - Root status NO ROOT! That's both great for you and sad for me. Thanks GrapheneOS
 - SD Maid 2/SE version: Both! Because I mean why not. You don't have just 1 pen for school or work do you? 

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).
Sorry Mr CoderDeveloper Man, no logs this time

**Screenshots/Video**
I could I guess? Doesn't seem required. You got ocular orbs in your skull right? I mean you made the animations u know what I mean. nawimean? 

**Additional context**
this is obviously one of your lowest issues maybe to date, but for some, like me, it's integral to app functionality because I really grew to like your overlay and lively animations. Now it just feels clerical, boring, lifeless. They grew up too fast. If don't like coffee maybe hot cocoa? Warm apple cider. Or maybe it's finely roasted blood of his enemies because this is hands down the best storage maintenance app around. _is what I would say if your mascot wasn't mopey and depressed with water or juice or Honestly probably nothing even in that cup. It all evaporated_

Hope the touch of humor for this ultra super serious issue was a welcomed change in your inbox. _**KEEP UP THE TERRIFIC WORK._** I might accidently send you beer money twice thru your referral link [again] 
 (I swear I will scream so loud if this isn't fixed...my dog gonna think I'm cuckoo)

**P.S: Love his new bows. Didn't they used to twirl and/or have a sparkle animation?**

**Comment by fillwithjoy1** [comment]
unusable, dev please fix

**Comment by NatureHog** [comment]
I believe this is fixed in the GitHub release, but if not, **_scandalous!_**

**Comment by Sadwhy** [comment]
Him? Then is he crossdressing? This is unacceptable.

**Comment by d4rken** [comment]
¯\\\_(ツ)_/¯

**Comment by fillwithjoy1** [comment]
lmfao
