### ISSUE TITLE
Search difference

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#52]
I compared SD Maid & SD Maid 2
On the example of CorpseFinder
All options are enabled in search settings

Why SD Maid finds more than the second version? In particular dalvik-cache

[Screenshot_20230328-131149](https://user-images.githubusercontent.com/439337/228208764-317cacd0-ce25-4790-9851-d2e066524f5f.png)
[Screenshot_20230328-131203](https://user-images.githubusercontent.com/439337/228208775-a881ac70-89d8-4ade-a94c-95803f114ed7.png)
[Screenshot_20230328-131415](https://user-images.githubusercontent.com/439337/228208778-3968ada3-b96c-4ef4-93cf-a59a2f5011fe.png)
[Screenshot_20230328-131419](https://user-images.githubusercontent.com/439337/228208782-a0052c7f-73e8-4fc9-8577-cd7912f51fa7.png)

**Comment by d4rken** [comment]
Impossible to say without seeing the actual details, the paths that were found.
Please take screenshots of those or record a debug log of the scan.

**Comment by alabotski** [comment]
Ok I will add

**Comment by alabotski** [comment]
![Screenshot_20230329-150113](https://user-images.githubusercontent.com/439337/228539546-bcdd3ac9-2a50-4ea7-bb09-d489bd500027.png)
![Screenshot_20230329-150553](https://user-images.githubusercontent.com/439337/228539551-eaee7875-2673-45af-b50e-e230dc48b6c0.png)

**Comment by d4rken** [comment]
I think that's okay.
The extra results in SD Maid 1 seem to be app optimisations that are done for pre-installed apps that are not necessarily used, but recreated on every boot, so deleting them is futile.

**Comment by alabotski** [comment]
@d4rken 
It's very strange but there is a difference in search

(https://github.com/d4rken-org/sdmaid-se/assets/439337/010e2431-7b60-4dd0-8107-f4c2c74e6f72)
(https://github.com/d4rken-org/sdmaid-se/assets/439337/dfbe533a-4a44-4b77-b9d4-c06cf0b295c2)

**Comment by d4rken** [comment]
:point_down: 

> The extra results in SD Maid 1 seem to be app optimizations that are done for pre-installed apps that are not necessarily used, but recreated on every boot, so deleting them is futile.

If they are recreated on every reboot, is deleting them worth it?
