### ISSUE TITLE
Inconsistent AppControl filter behavior

### ISSUE THREAD

**Issue by gallegonovato** [d4rken-org/sdmaid-se#526]
Good afternoon:

I wanted to add a suggestion. I don't know if it is feasible or not.

I don't know if in AppControl it can be done to show all applications together.

That is, those of the user, system, activated and deactivated. All together on the same screen. 

Since currently it does not allow you to check or enable all filters.

A hug

**Comment by d4rken** [comment]
You should already be able to turn off all filters and view the complete app list.

**Comment by gallegonovato** [comment]
Good afternoon @d4rken

Well, the truth is that it does not allow me to disable the filters.

If you checked system, it does not allow to activate the user ones. That is to say, if I activate user, system is deactivated.

It is the same as if you check enabled it disables the disabled applications. 

I am using 0.10.8 beta 1.

I do not know if it would be possible to add an option to put all the applications. 

This happens to me on a Samsung A30s without root, and a Huawei Nexus 6p with root and lineageos. 

What I do not know if it would be possible in any future version. Add the options: terminate the application, force detection, and other options that were in the previous version of Sd Maid?

Best regards

**Comment by d4rken** [comment]
If system filter is enabled, what happens if you don't touch the user filter, but instead just try to disable the system filter by pressing it again.

Can you record a video?

**Comment by d4rken** [comment]
I think the problem is that the filter operations are not aborted when they are changed again. On slow devices it may take a few seconds. Once the operation finishes, it will update the list and also set the current filter options, which may overwrite any changes you have made after that.

I will apply a fix so that changing the filter options will cancel the current operation and start a new one.

**Comment by d4rken** [comment]
I'm also adding a button to clear all filters, a "show all" button.

**Comment by gallegonovato** [comment]
Good afternoon @d4rken

Many thanks for your time and help.

Best regards
