### ISSUE TITLE
Accessibility service needs to be enabled everytime 

### ISSUE THREAD

**Issue by nikontutorials** [d4rken-org/sdmaid-se#528]
**Describe the bug**
Everytime I reboot or force kill the app I need to reseñable the accessibility service.

**To Reproduce**
1. Open SD Maid SE
2. Open Accessibility service from the promp in the app
3. Enable Accessibility service 
4. Force kill the SD Maid SE
5. Accessibility service is disabled and get prompted again to enable.

**Expected behavior**
The Accessibility service should be enabled even after killing the app or rebooting the phone.

**Device:**
 - Device: Pixel 6a
 - OS: Android 13
 - Root status: Unrooted
 - SD Maid 2/SE version: v0.10.8-beta1

**Comment by d4rken** [comment]
Force stopping an app will always disable the accessibility service. This is just the way Google implemented it.

Why are you regularly force-stopping SD Maid?

A possible workaround is granting SD Maid "write secure settings" access, then SD Maid will keep the service disabled and only enable it when needed, without further user interaction. See:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-troubleshooting
