### ISSUE TITLE
Minimum age for Whatsapp files

### ISSUE THREAD

**Issue by george9816** [d4rken-org/sdmaid-se#548]
**Is your feature request related to a problem? Please describe.**

I'd want all whatsapp files older than 6 months to be deleted.

**Describe the solution you'd like**

An option to specify a minimum age of max 12 months for deleting whatsapp files in AppCleaner Settings.

**Comment by d4rken** [comment]
You can specify a minimum age in the AppCleaner settings, this applies to all results where SD Maid can determine age, including the WhatsApp stuff.
BUT this is currently limited to 6 days via the slider.

Would you be helped if this gets extended to allow entering up to 12 month?

**Comment by george9816** [comment]
I know, but I don't want a minimum age of 6 months for the cache and all the other things. 

So I'd need a separated slider for WApp..

**Comment by d4rken** [comment]
That's kind of an endless thing though...
Maybe a slider for Telegram, and one for Viber, and for WeChat. I can't add 50 sliders 🤔.

We need a general solution.

**Comment by george9816** [comment]
More scans with different setting is a viable solution.

I think this would suppose an option in Scheduler to set different settings for every schedule.

**Comment by d4rken** [comment]
Hm also quite complex to implement. I think extending the current setting to allow for a wider timerange is the only thing I can offer at the moment.

**Comment by d4rken** [comment]
Depends on your apps 🤷
