### ISSUE TITLE
Payment Options visible if you have already paid 

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#561]
I have already payed for lifetime licencse over Play, but the Abo Button is still shown? Is this a expected behavior or a bug? 
I'm on Pixel 7 with the latest Android and no root.

**Comment by MarkyMarkDE** [comment]
> If you mean the entry in the settings menu, then this is on purpose to allow users who bought one of the options to switch to another.
> 
> But pressing any other entry shouldn't show the upgrade screen.

Yes, I mean the entry in settings menu.
But when I have already paid (non abo) then the abo button should maybe not visible.
If this license become invalid (it isn't called "lifetime license" my fault, sorry), then yes.

**Comment by MarkyMarkDE** [comment]
@d4rken do you know where Firefox caches his data? I like no set an app exception, but I like keep the favicons only, but I do not find the right location where Firefox cache his data.

**Comment by MarkyMarkDE** [comment]
thank you for hiding the "Sponsor" Option in Settings for Premium Users!

I understand that you need money, and here I have two ideas.

1. include an option, so the user can additional buy special "badges" to support you additionally.
The idea is from [DAVX5](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=de&gl=US) App, I like it.

2. make an additional donate App, something like the App from Dieter Thies for his [Cell Widget Donate App](https://play.google.com/store/apps/details?id=de.dieterthiess.donate&hl=de&gl=US).
Maybe you can re-use his App, but I'm not sure if it is open source or which license he is using

good ideas?

**Comment by d4rken** [comment]
> include an option, so the user can additional buy special "badges" to support you additionally.
The idea is from [DAVX5](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=de&gl=US) App, I like it.

I like that, i had something similar in SD Maid 1, a "pizza" and a "coffee" IAP. I'm wondering if I should add that, or rather a cheap subscription that can be bought and cancelled at will.

**Comment by MarkyMarkDE** [comment]
> > include an option, so the user can additional buy special "badges" to support you additionally.
> > The idea is from [DAVX5](https://play.google.com/store/apps/details?id=at.bitfire.davdroid&hl=de&gl=US) App, I like it.
> 
> I like that, i had something similar in SD Maid 1, a "pizza" and a "coffee" IAP. I'm wondering if I should add that, or rather a cheap subscription that can be bought and cancelled at will.

The developers of DAVX5 take a different approach.
They sell one-time badges in different sums (one-time) no subscriptions.
They also give the badges funny names (this is new) so that the user is tempted to buy a badge (without finding the "purchase" unpleasant) and then have a special icon displayed in the app.

But sure, you can go another Way, this is only an idea.
