### ISSUE TITLE
Cache cleaning is slower than the previous app

### ISSUE THREAD

**Issue by IIAndrewRyanII** [d4rken-org/sdmaid-se#563]
Es simple, la opción de limpiar cache es un poco más lenta que la versión clásica de sd maid. Compre la aplicación porque creí que realmente sería más rápido, pero al parecer no es así.

**Comment by d4rken** [comment]
If you have a concrete slow down cause, I can work on it.
Saying "it's slower" doesn't help me :slightly_frowning_face:
