### ISSUE TITLE
Abort scheduled tasks if not plugged in

### ISSUE THREAD

**Issue by MithicSpirit** [d4rken-org/sdmaid-se#564]
**Is your feature request related to a problem? Please describe.**
SD Maid's scans can be quite resource-intensive\* and I don't want them to happen automatically (through the scheduler) when on battery power.

(\*or at least I assume they're resource intensive since they can take quite a while to run)

**Describe the solution you'd like**
Add a setting to abort scheduled tasks when not plugged in, like in SD Maid 1.

**Describe alternatives you've considered**
Allow the setting to be set per-schedule rather than globally, or have it as a trigger condition. I think that these are more complex than they're worth for now, although they should be reconsidered down the line.

**Describe why this would be in the interest of all users**
This feature is also present on SD Maid 1, so migrating users are likely to expect it (I did).

**Additional context**
This was discussed on the Discord server starting [here](https://discord.com/channels/548521543039189022/1047079350157193236/1137063076152230028).

**Comment by d4rken** [comment]
Seems like a good feature, looking forward to your PR :blush:.

Thinking out loud:

* New setting in `SchedulerSettings`
* Make the setting visible in `SchedulerSettingsFragment`
* Check the abort condition in `SchedulerReceiver`?

Maybe a nice settings icon, something with a charger?, from https://materialdesignicons.com/ ?
