### ISSUE TITLE
Optimization for Samsung DeX and larger screens

### ISSUE THREAD

**Issue by soutiagojose** [d4rken-org/sdmaid-se#567]
**Is your feature request related to a problem? Please describe.**
SD Maid SE was developed to be a more optimized update to current androids, but nowadays, there are a range of Android devices with different screen sizes, for example, tablets and Samsung DeX.

 Samsung DeX is an interface that transforms the mobile environment into a desktop environment, similar to Windows and which is used in addition to the manufacturer's tablets, on smartphones.  The interface is used on external monitors and is supported by ultrawide.

 SD Maid SE's interface is not optimized for large screens, it is only usable on smartphone screens, but could be optimized for larger screens such as tablets

**Describe the solution you'd like**
The solution is that the interface is more friendly to the tablet screen, a responsive interface, with columns instead of lists when the screen is bigger

**Describe alternatives you've considered**
I find the Bleachbit interface interesting for windows and linux, I even consider SD Maid as an android Bleachbit.

**Describe why this would be in the interest of all users**
This optimization becomes important because there are many devices with large screens and because they are not optimized in the UI, users may feel that it is something more amateurish, confusing and even prefer another app because it is visually more practical.

**Additional context**
![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/4f0232c8-8798-444a-b0eb-a0c2c489954c)
![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/28864447-c928-4ead-a6dd-fdfa5f94c84d)
![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/00a7433a-e6b0-4947-99d6-cf65b5647c0a)
> The old version of SD Maid is even more optimized for large screens than the current one

![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/e35e629a-3bb5-4785-bb5e-3abf01f7a5b5)
![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/1c457069-7231-4e5f-a94b-285464ea8777)
![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/214207d1-a15f-4601-9657-08140c3e1e49)

> When you start cleaning apps on large screen devices, it doesn't have to stop.

**Comment by allytiago** [comment]
When you start cleaning apps on large screen devices, it doesn't have to stop.

**Comment by d4rken** [comment]
I'd be open for some kind of dynamic solution. We need to avoid just duplicating UI work for every other size factor. "Almost all" users are phone users.

Thinking out loud:

The dashboard screen could use a square grid with multiple columns depending on the screen width, e.g. placing two or more cards in the same row. This could be dynamically detected and scaled, e.g. if the screen is even wider place 3 cards in one row.

> When you start cleaning apps on large screen devices, it doesn't have to stop.

Create an extra issue ticket for this :pray:. It's a device specific bug.

**Comment by allytiago** [comment]
> I'd be open for some kind of dynamic solution. We need to avoid just duplicating UI work for every other size factor. "Almost all" users are phone users.
> 
> Thinking out loud:
> 
> The dashboard screen could use a square grid with multiple columns depending on the screen width, e.g. placing two or more cards in the same row. This could be dynamically detected and scaled, e.g. if the screen is even wider place 3 cards in one row.
> 
> > When you start cleaning apps on large screen devices, it doesn't have to stop.
> 
> Create an extra issue ticket for this pray. It's a device specific bug.

![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/b8949f3c-46f3-4fc6-9610-4b3314d5c9de)
>This is a Samsung app, SD Maid is more powerful than it in terms of cleaning.

 His UI, in order to adapt to screen sizes, cards have a maximum width limit and are centralized.

![image](https://github.com/d4rken-org/sdmaid-se/assets/47113005/e5f07140-7dd7-4050-a843-06ea0ff014ea)
In Bleachbit, the UI pushes options to the side, while the center is where the magic happens.  In SD Maid on tablets, app windows are opened in the center and the old UI manages to become more friendly to that

**Comment by d4rken** [comment]
Multi column mode is now used on larger screens.
