### ISSUE TITLE
RAM memory cleaning

### ISSUE THREAD

**Issue by allytiago** [d4rken-org/sdmaid-se#568]
**Is your feature request related to a problem? Please describe.**
SD Maid's idea is to clean the system so it doesn't get too heavy with digital garbage, like cache, thumbnails, temporary files...  The RAM also needs cleaning and I don't see many apps highlighting it.

**Describe the solution you'd like**

**Describe alternatives you've considered**
In addition to the option to clean applications, there is an option that allows you to clean the device's ram memory.

**Describe why this would be in the interest of all users**
It has a device with 4GB of RAM.  That's relatively little for an Android.  Samsung brought a solution, Memory Guardiam, which cleans RAM memory by almost 90%, but the tool is still limited to some devices and not available in app stores.

I use memory guardiam very often, but it needs to be opened in another app first so that it can be opened later and sometimes I find it unintuitive

**Comment by d4rken** [comment]
RAM cleaning is out of scope for SD Maid.

> "RAM cleaning" or "Task killer" apps on Android have long been a hot topic among tech enthusiasts and professionals alike. During the early days of smartphones, many believed that these apps would help improve device performance by freeing up memory and ending processes. The logic was that by terminating background applications, the device could run faster and be more efficient. However, as Android systems evolved, they became better at managing their resources. Modern Android versions are designed to optimize RAM usage and app management intelligently. Using these apps could disrupt this system, sometimes even leading to more battery drain and slower performance. Additionally, constantly closing apps and having them restart can use more power than letting them run in the background. As a result, many experts now advise against the regular use of such apps, leading to a polarized debate on their efficacy and relevance in the current tech landscape.
