### ISSUE TITLE
CorpseFinder: UninstallWatcher notification text is cut off

### ISSUE THREAD

**Issue by uli-on** [d4rken-org/sdmaid-se#569]
**Is your feature request related to a problem? Please describe.**
In the notification bar there's not enough room to display the results of a cleanup after deinstallation cause there's "rocks.poopjornal.metadataremover" displayed. 

**Describe the solution you'd like**
Remove it from the notification 

**Describe alternatives you've considered**
Turning the device to landscape doesn't make the notification wide enough to fully display what's actually informative

**Describe why this would be in the interest of all users**
You'll have set this notification up for the reason to be read, and not for being wiped off the screen, right? 

**Additional context**
I'm using this notification minified in order to have the screen not too cluttered with notifications.

**Comment by d4rken** [comment]
I don't know what you mean. What does this have to do with SD Maid?

**Comment by uli-on** [comment]
![Screenshot_20230806-214607](https://github.com/d4rken-org/sdmaid-se/assets/35634829/4f3fc7e3-5393-4827-8709-fa9ebaedec8a)

Do you recognize it here?

**Comment by uli-on** [comment]
You're free to rename the topic to your liking, it's just what I get displayed.

**Comment by d4rken** [comment]
Okay now I understand.

If I remove it, how do we know about which app the notification is?
Displaying the name might be shorter, maybe?

**Comment by uli-on** [comment]
Ah, I thought it was some kind of "easter egg" that became visible by some accident. (Will have to look that rascal up that coded the app).

Yes, might be more readable and informative having the app's *name* rather than its creator code.

**Comment by uli-on** [comment]
Crazy Marvin's "metadata remover"

Well, actually this notification is two-leveled, one asks "Shall I care for app x's remains, and the second one reports success and amount, so the user should already know which app he's deleted. The amount deleted should suffice, amount first, app name second, I'd say after thinking it through.

**Comment by uli-on** [comment]
One last post for today: Metadata Remover was deinstalled days ago. I've deinstalled five more apps after it, documented by the app "Installalogs". How comes this string is still being used in the notification?

**Comment by uli-on** [comment]
One more app uninstalled, still the known/same string from post #1 displayed.

**Comment by d4rken** [comment]
The unknown string is the unique identifier of an app, the `packagename`. But you are right, it's weird that it's always the same, it should change and match the uninstalled app.

**Comment by uli-on** [comment]
So you seem to wrap the message to a new line now in order to still use the package name. But the issue of displaying an ancient package name after cleaning up is not yet fixed (v0.11.0-beta0).

**Comment by d4rken** [comment]
Can you open a new issue for this and provide a debug log? I could not reproduce this on my test device. I looked into what it takes to show a better name, but decided that caching all app names always, is currently too complicated, maybe the future.

**Comment by uli-on** [comment]
SD Maid opens a plethora of notifications while executing the Corpse Finder, at least three. Are you sure you clicked through to the last one even if you saw "0 objects to remove" on one of the earlier notifications?

**Comment by d4rken** [comment]
Continue in #585
