### ISSUE TITLE
Need instructions on activating accessibility service on Android 13+

### ISSUE THREAD

**Issue by dic1911** [d4rken-org/sdmaid-se#57]
After installing the app, I tried to activate accessibility service for sdmaid, but all I got is a "Restricted Settings" dialog,
I searched a bit and found out it's caused by Android 13, and I could remove such restriction from "App Info" page, but it was still confusing, can you add some instruction that extra action is required on Android 13? thanks.

ref: [https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/](https://blog.esper.io/android-13-sideloading-restriction-harder-malware-abuse-accessibility-apis/)

**Comment by d4rken** [comment]
Wow Google, :bow: 
They really don't want anyone to change this.

* There is no way to detect if the app is affected by restrictions.
* You can only disable the restriction if you have run at least once into the "Restricted settings" dialog
* You can't guide the user to your own app details screen to change it. The user MUST go there manually without going through any other apps.

I've written up a short guide on this with screenshots:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup/_edit#acs-appops-restrictions

**Comment by d4rken** [comment]
Added in-app instructions too:
![Screenshot_20230331_210220](https://user-images.githubusercontent.com/1439229/229229122-3c390e7e-4b84-4399-9b11-a23dd6905780.png)
