### ISSUE TITLE
Settings entry that opens the upgrade screen is still visible

### ISSUE THREAD

**Issue by CodeSpoof** [d4rken-org/sdmaid-se#576]
**Describe the bug**
The button to buy pro version still is shown in general settings after buying it

**To Reproduce**
1. Buy Pro (Lifetime) 
2. Open Settings
3. Go to "General" (Allgemein) 

**Expected behavior**
Button to buy Pro hidden or disabled

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11
 - Root status Rooted - Magisk v26.1
 - SD Maid 2/SE version v0.10.8-beta1

**Comment by d4rken** [comment]
That was on purpose, but just like you, others were confused by this and I've since hidden it in the current update (#571), should by already available! :grin:

**Comment by CodeSpoof** [comment]
> That was on purpose, but just like you, others were confused by this and I've since hidden it in the current update (#571), should by already available! :grin: 

Not included in latest update (0.11.0-beta0)

**Comment by d4rken** [comment]
Should be though, the commit is in there, can you show me a video of the issue?

https://github.com/d4rken-org/sdmaid-se/commit/b0850577fa21f450ca0f70ef6cc70dc1df2838fb

**Comment by CodeSpoof** [comment]
https://github.com/d4rken-org/sdmaid-se/assets/42744253/baac8fbe-604c-43de-b7a6-e02d840edf87

**Comment by d4rken** [comment]
Oh :sweat:, I forgot about that entry. I*ll remove that. Seems duplicate anyways, if there is one in the main menu too. Thanks for the report!
