### ISSUE TITLE
Custom filter did not work

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#583]
I've tried long time to get a custom filter to configure but this do not work. The complete menu is English only and no save button, hit I back, the notification comes up, that I have unsaved changes, yes that's true, but how should I save it without a button?
or do I something wrong?

**Comment by d4rken** [comment]
There should be a save button in the right corner.
It will only be visible if you have entered enough information.

![Screenshot from 2023-08-10 11-02-44](https://github.com/d4rken-org/sdmaid-se/assets/1439229/7d74c6b6-cf87-4bec-b521-4b9e5474aa93)

**Comment by d4rken** [comment]
> By the way: the keywords, is it a comma separated list? This is not explained in the App ...

You need to finish entering at least one path or name. You press "enter" on the keyboard or "done", to create something, this is how things are seperated.

Unfinished:

![Screenshot from 2023-08-10 23-37-44](https://github.com/d4rken-org/sdmaid-se/assets/1439229/1bb35efe-462d-4ef4-8de4-224060357668)

Two finished entries:
![Screenshot from 2023-08-10 23-38-08](https://github.com/d4rken-org/sdmaid-se/assets/1439229/60ab1ca3-6802-4dff-83cf-8f2577603a3e)

**Comment by d4rken** [comment]
I'll change the code to automatically complete the text to a tag when the input view looses focus.

**Comment by d4rken** [comment]
Should be fixed in the next update.
