### ISSUE TITLE
accessibility service bug

### ISSUE THREAD

**Issue by marioharyzal** [d4rken-org/sdmaid-se#589]
the accessibility service becomes disabled if you reopen the application, and if you look at the smartphone settings the accessibility service in the settings is already active for SD Maid Se

bug happened in android 13 on MIUI 14

[Screenshot_2023-08-13-00-09-00-846_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/50802175/228fe0f4-11cb-41c2-a4c0-cf382498b114)

[Screenshot_2023-08-13-00-10-48-428_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/50802175/ccb04843-2382-40f2-ae4a-a0225c6da8dd)

**Comment by d4rken** [comment]
If this is a MIUI ROM then enable "autostart" for SD Maid.

This problem is usually caused by battery optimisations.

If you can use ADB then there are some tricks to solve this too:

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-troubleshooting

**Comment by marioharyzal** [comment]
ok, thanks for your answer
