### ISSUE TITLE
Filter apps by size

### ISSUE THREAD

**Issue by jcgaming-official** [d4rken-org/sdmaid-se#597]
It is better if the app has Storage filter type on App Control [Screenshot_20230821-053326.jpg](https://github.com/d4rken-org/sdmaid-se/assets/77482435/896acd62-89e2-411f-8b0d-37dda551c91b)

**Comment by d4rken** [comment]
What do you mean by "storage"?

**Comment by jcgaming-official** [comment]
> What do you mean by "storage"?

Filtering high or low used storage every app

**Comment by jcgaming-official** [comment]
> > What do you mean by "storage"?
> 
> Filtering high or low used storage every app

Like the feature on sd maid original![Screenshot_20230821-055040.jpg](https://github.com/d4rken-org/sdmaid-se/assets/77482435/3d396c52-f6fa-4599-ab84-29bd5f097f2b)

**Comment by d4rken** [comment]
Added in next update via #858
