### ISSUE TITLE
Greenify users: Is there an issue with "Deep hibernation (by island)" and the CorpseFinder?

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#612]
I've read something that if an app is hibernated using Greenify's "Deep hibernation (by Island)" mode, that the CorpseFinder then produces false-positive results for that hibernated app.

I can't reproduce this though. Anyone know more or is able to reproduce it?

**Comment by kevinjoramos** [comment]
Hi, this is my first time ever contributing to open source, and I'd like to see if I can reproduce this. By false-positive you mean that it will delete the app's files when it shouldn't right?

**Comment by kevinjoramos** [comment]
I was not able to recreate the bug. I'm using a Pixel 4a 5g with android 12.

**Comment by d4rken** [comment]
Could not reproduce it either so far, if anyone can reproduce this, please re-open.

@kevinjoramos Thanks for testing.
