### ISSUE TITLE
File deduplication

### ISSUE THREAD

**Issue by adRn-s** [d4rken-org/sdmaid-se#625]
I use czkawka (it has different methods) on Linux. You may be able to port functionality from there. It would be great to run this on specific subfolders (e.g. Music). Thanks in advance!

**Comment by d4rken** [comment]
Closing this for now in favor of this discussion are this is not an immediately actionable task:
https://github.com/d4rken-org/sdmaid-se/discussions/356

Semantic duplicate detection for music or images would be awesome, tough tech though on a phone 🤔
