### ISSUE TITLE
Scheduler starts at random times. 

### ISSUE THREAD

**Issue by HathewayWill** [d4rken-org/sdmaid-se#626]
**Describe the bug**
[Screenshot_20230915_181252_SD Maid SE.jpg](https://github.com/d4rken-org/sdmaid-se/assets/118180342/65d253c3-a657-407f-8816-5899c9e1a218)

**Expected behavior**
Expected to run at night not during middle of day. 

**Smartphone (please complete the following information):**
 - Device: Samsung s23 ultra
 - OS: android q3
 - Root status not rooted
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Comment by d4rken** [comment]
Which SD Maid version?

Are is battery optimization disabled for SD Maid?

**Comment by MarkyMarkDE** [comment]
Same here with the last Beta 0.11.0-beta0
My own schedule seems to work additional to the crayze other autostarts

**Comment by d4rken** [comment]
This is somehow related to using the "more battery efficient" scheduling that Google wants apps to use if they are not "Alarm apps". I'll look into this

**Comment by d4rken** [comment]
I'm working on replacing the schedule current scheduling via `AlarmManager` with delayed `WorkerManager` requests.

e.g.:
https://code.luasoftware.com/tutorials/android/android-schedule-daily-reminder-alarm-at-specific-time-with-workmanager

**Comment by MarkyMarkDE** [comment]
> I'm working on replacing the schedule current scheduling via `AlarmManager` with delayed `WorkerManager` requests.
> 
> e.g.: https://code.luasoftware.com/tutorials/android/android-schedule-daily-reminder-alarm-at-specific-time-with-workmanager

this sounds great! The current one is really frustrating as G* did what IT did. It leaves the USER no really choices

**Comment by MarkyMarkDE** [comment]
only a short feedback: it works now awsome. On AndroidTV the time is 100% exact as my schedule and on Android 13 (Pixel 7) little different, maybe you are able to fine tune here.
