### ISSUE TITLE
Shizuku vs Root configuration options inconsistent 

### ISSUE THREAD

**Issue by mrandreastoth** [d4rken-org/sdmaid-se#641]
**Describe the bug**
Under Settings | Setup, even if a device has no root, the option to use it can still be set. This simply means that the configuration can be shared across devices that may or may not be rooted since the option will only apply if root is actually available.

However, the same option is disabled for Shizuku when it isn't installed meaning the configuration cannot be shared across devices that may or may not have Shizuku installed.

**Expected behavior**
Both of the Shizuku options are to be available even when the app isn't installed. This would not just make for a consistent behaviour between the Shizuku and root settings but also make the configuration more flexible and sharable.

**Smartphone:**
 - Device: Samsung Galaxy S21 Ultra 5G
 - OS: Android 13
 - Root status Not rooted
 - Shizuku: Not installed
 - SD Maid 2/SE version 0.12.0-beta0

**Comment by d4rken** [comment]
There is no direct way to detect root, except by launching a super-user shell, so testing availability would look the same as granting access to the user. Popping a random super user request is not nice for the user.

For Shizuku I can check whether the Shizuku app is installed.

So we can discuss whether the Shizuku setup card should be permanently visible. :thinking: 

* Would the majority of users be confused because they don't know what Shizuku is?
* How many people don't have Shizuku installed, but would set it up, just for SD Maid?

Should we just make it visible and see? :shrug:

**Comment by mrandreastoth** [comment]
I had no idea what Shizuku was until I saw the setting relating to it. However, that isn't the point I was trying to make but that of consistency and flexibility.

Consistency in terms of how two similar features and their settings currently operate differently. After all, "if root is available" is fundamentally the same thing as "if Shizuku is available" when considered generically. So, if the user configures the app to use root even though root isn't available, that shouldn't be different to allowing the matching setting for Shizuku even if Shizuku isn't available. Of course, this does mean SD Maid must actually test for this and not just take the setting for gospel, but so it must be doing anyway since Shizuku is an app and, as such, can be uninstalled after the setting has been set. As such, I propose that the same note/wording as sued with regards to root should be used with Shizuku, i.e., when the setting ise set, Shizuku will be used "if it is available."

Flexibility in terms of being able to take the SD Maid configuration and use it on another system without needing to make any changes to it in order to remain valid and not cause any issues. After all, there shouldn't be any side-effects of having Shizuku installed on one system and configuring SD Maid to use it to then either uninstalling Shizuku or using the configuration on another system. Currently, however, since the setting is disabled when Shizuku  isn't available,  that would suggest the setting would need to be changed by SD Maid to remain valid, but SD Maid should never modify a user's settings as that would be considered a side-effect, and side-effects, as we know, are bad.

Note that making the Shizuku setting behave as the root setting is better than making the root setting behave like the Shizuku since the Shizuku setting has a side-effect while the root setting hasn't. Note also that is because of this side-effect that I consider the current behaviour a bug and not a feature request.

**Comment by ZeroXXX-1** [comment]
> Не существует прямого способа обнаружить root, кроме запуска оболочки суперпользователя, поэтому проверка доступности будет выглядеть так же, как предоставление доступа пользователю. Отправка случайного запроса суперпользователя неприятна для пользователя.
> 
> Что касается Shizuku, я могу проверить, установлено ли приложение Shizuku.
> 
> Итак, мы можем обсудить, должна ли карта настроек Шизуку быть постоянно видимой. 🤔
> 
> * Будет ли большинство пользователей сбиты с толку, потому что они не знают, что такое Шизуку?
> * Сколько людей не установили Shizuku, но хотели бы установить его только для SD Maid?
> 
> Должны ли мы просто сделать это видимым и посмотреть? 🤷

Yes, many people use it Shizuku (speaking for 4pda). If there are some more flexible and detailed settings that can be applied, let's do it! 💪
