### ISSUE TITLE
Customer Filter - "Error - AssertionError"

### ISSUE THREAD

**Issue by demetry14** [d4rken-org/sdmaid-se#643]
**Describe the bug**
When attempting to save a custom filter in "Settings > SystemCleaner > Manage custom filters" I receive" that only contains the name test and only contains the saved word hot in Name criteria I receive this error:
"Error - AssertionError
Missing field is kotlin.text.RegexOption"

**Expected behavior**
custom filter should save without issue

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10
 - OS: Android 12
 - Root status: No root
 - SD Maid 2/SE version: 0.12.0-beta-1 (1200010 ~ 726246c6 /GPLAY/BETA

**Debug log**
[eu.darken.sdmse_logfile_1695397648017.log](https://github.com/d4rken-org/sdmaid-se/files/12702476/eu.darken.sdmse_logfile_1695397648017.log)

**Screenshots/Video**
![Untitled](https://github.com/d4rken-org/sdmaid-se/assets/5199569/78ed61f9-b075-417a-b717-f6e9fb2412eb)

**Comment by aamadorj** [comment]
Same issue here. I only add that all my custom filters previously used just vanished from SD Maid SE after the recent update.

**Comment by d4rken** [comment]
@demetry14 Thanks, R8 broke the serialization, will be fixed in the next update.

> I only add that all my custom filters previously used just vanished from SD Maid SE after the recent update.

That's was on purpose, there was a large data format change and didn't want to add migration code for beta releases (but I also thought next update would be out sooner... sorry :frowning_face:).
