### ISSUE TITLE
After delete default schedule not possible to add new one

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#662]
When I delete the default schedule, I can't click on "+" to apply a new one (click has no effect).
If no other ways possible, then show maybe something like an alert, that this schedule can't be deleted. If you delete the default one,  you can only delete the sd maid se cache and set up the whole app again.
If you have the default one and a custom schedule, there is no problem to delete the default one, this happens only, when after deleting no schedule exists. 

Pixel7
Android13
Latest Patches September 23
No root 

SDMaid-2/SE FOSS 0.13.0-beta0

**Comment by d4rken** [comment]
I can't reproduce this.

Can you provide a debug log of this?

**Comment by MarkyMarkDE** [comment]
> I can't reproduce this.
> 
> Can you provide a debug log of this?

You mean this bug is on AndroidTV only?
Here is the bug really present

**Comment by MarkyMarkDE** [comment]
And additional there is not really possible to change something in schedule, as reason that the "frame" with the keyboard overlap this content round 100%. It would be great, if you can look at this, I know, AndroidTV is not official supported.

**Comment by d4rken** [comment]
Android TV? You wrote Pixel7!

**Comment by MarkyMarkDE** [comment]
> Android TV? You wrote Pixel7!

Indeed, so sorry. I thought it happend also on Pixel 7, I had not tested, my fault, please sorry.

But I can't understand, all of SDMaid SE is working on AndroidTV, but only this menu didn't, after delete the default schedule, I'm not able to tab on "+" to add a new one, so it is really like my first post.

Let me test this on my Pixel7 too, I will come back to this.

**Comment by MarkyMarkDE** [comment]
Okay, I have test it now.
On my Pixel 7 it is working, but it is really tricky.
If you click on "+" you should enter a Name, but my SwiftKey Keyboard let me not out of this text box to select time and days

**Comment by MarkyMarkDE** [comment]
and on AndroidTV with gboard keyboard is it exactly same, when you try to change the default schedule

**Comment by MarkyMarkDE** [comment]
Hopefully you can understand it now, otherwise I try to explain it differently

**Comment by MarkyMarkDE** [comment]
Only a short feedback: your UI changes in v0.15 works great now on AndroidTV, thank you so much for this!
Now I was able to change the default schedule to 8pm on every day 😉
