### ISSUE TITLE
zygisk and lsposed 1.9.1 (6990): LSposed partially activated: SEPolicy is not loaded properly

### ISSUE THREAD

**Issue by znarknesor** [d4rken-org/sdmaid-se#669]
**Describe the bug**
After cleaning phone with sdmaid latest beta 0.13.0 zygisk and lsposed 1.9.1 (6990): LSposed partially activated: SEPolicy is not loaded properly

**Smartphone (please complete the following information):**
API Version
100

Xposed API-Aufrufschutz
Deaktiviert

Dex Optimizer Wrapper
Unterstützt

Framework Version
1.9.1 (6990)

Name des Managerpakets
com.android.shell

System Version
13 (API 33)

Gerät
Samsung SM-G990B2 

System ABI
arm64-v8a

Magisk 26300

fully rooted

**Comment by d4rken** [comment]
Is this reproducible? Please provide a debug log.

I don't think this is related to SD Maid.

**Comment by Misakamoe** [comment]
**The issue has been reproduced:**

If you have checked the ''Download cache'' option in `Settings -> SystemCleaner`, you will scan out `/cache/magisk/zygisk_lsposed/sepolicy.rule` or other `sepolicy.rule` files in the SystemCleaner Tool, and then clean them up. However, when you restart the device again, this/these files will not be automatically rebuilt, so you will see **"SEPolicy is not loaded properly"** in LSPosed.

**Solution:**

- Reinstall LSPosed and then restart
- Exclude "Download cache" in `Settings -> SystemCleaner`

**Comment by d4rken** [comment]
@Misakamoe Great find, let's exclude that subdirectory by default :+1:

**Comment by Misakamoe** [comment]
> @Misakamoe Great find, let's exclude that subdirectory by default 👍

Aside from LSPosed, there are `sepolicy.rule` files created by other modules, so I suggest excluding `/cache/magisk/`.
