### ISSUE TITLE
problem allow grant access

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [d4rken-org/sdmaid-se#68]
[Screenshot_20230330-172721.jpg](https://user-images.githubusercontent.com/41585567/228886908-37d9150e-891d-4991-b423-2d0959398dbc.jpg)

**Comment by d4rken** [comment]
What Android version and device is this?

The app SD Maid wants to open HAS to exist, it's a built-in system app.

**Comment by d4rken** [comment]
I've expanded the setup wiki with details about this:

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#storage-access-framework
