### ISSUE TITLE
Barrierefreiheit unter MIUI 14.0.2

### ISSUE THREAD

**Issue by charlybaer0366** [d4rken-org/sdmaid-se#690]
**Describe the bug**
Barrierefreiheit wegen Einschränkungen von Android nicht mehr aktivierbar. 
Autostart aktiviert auch keine Besserung 

**To Reproduce**
1. Go to Setup
2. Click on Barrierefreiheit
3. Click ON Aktivieren 

**Expected behavior**
Barrierefreiheit lässt sich aktivieren

**Smartphone (please complete the following information):**
 - Redmi Note 11G Pro
 - OS: Android 11
 - Root status Rooted MIUI
 - SD Maid 2/SE version 0.14 Beta

**Debug **
[eu.darken.sdmse_logfile_1696336764241.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12792956/eu.darken.sdmse_logfile_1696336764241.log.zip)

**Screenshots/Video**
![Screenshot_2023-10-03-15-25-44-393_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/25280182/71e21655-af4b-4c97-b96d-9df5382bb457)
![Screenshot_2023-10-03-15-28-12-657_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/25280182/cc701693-f476-4451-93b5-86c92db5251c)

**Comment by MeloriTensei** [comment]
Hi, thanks for reaching out for your issue with SD Maid SE. In regard to your issue, let's try to slim down the possibilities here.  Have you tried to reactivate the Accessibility Service AFTER you have activated auto start? And/or rebooted your device as well?

Looking forward to hear back from you.

[DeepL Translate]
Hallo, vielen Dank, dass Sie sich wegen Ihres Problems mit SD Maid SE gemeldet haben. Was Ihr Problem betrifft, so sollten wir versuchen, die Möglichkeiten einzugrenzen.  Haben Sie versucht, den Erreichbarkeitsdienst zu reaktivieren, NACHDEM Sie den Autostart aktiviert haben? Und / oder haben Sie Ihr Gerät neu gebootet?

Ich freue mich auf eine Antwort von Ihnen.
