### ISSUE TITLE
Scheduler did not stop in some cases

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#692]
SD-Maid-SE with the new service for schedule execution does not always stop finally on end.
I have a schedule and it is running, then the job is done SD-maid is closing and starts a few seconds after again. Then i click on Cancel, SD Maid is closing, and a few seconds after it starts again, then i click on cancel again and then the spook is really over.
I Cannot say which conditions must match for this bug and error logging is not really possible, I don't know before when the bug occurs.

Please check if, after successfully execution of the current schedule, the new service really ends finally.

Android 13
Latest Updates of September 2023
Pixel 7
Non-root
sdmaid-se-0.14.0-beta0-foss

**Comment by MarkyMarkDE** [comment]
> Hi, if you do have the time to experiment, you can attempt to set a schedule a minute or two after the current time on a Daily Schedule to let a scheduled task run today. See if it's possible for you to find the possible conditions for it to recreate the issue.
> 
> Looking forward to hear back from you.
> 
> @MarkyMarkDE

Yesterday the problem was really hard. The Scheduled run is finished, the overlay is closed - so far so good. Few seconds later it starts again, I click Cancel and nothing happened! I click Cancel again, nothing happened. Click again Cancel, then it is being canceled for some seconds and the app starts again. This I can repeat multiple times, why. I have only the chance to kill the app, or I'm in an endless loop.

**Comment by MeloriTensei** [comment]
@MarkyMarkDE That's exactly what we are trying to catch, just by merely describing what happened mast not be enough for a complicated issue.

It would still be great to keep recording the debug log consistently until the end and catch it off-guard when it happens.

**Comment by MarkyMarkDE** [comment]
> @MarkyMarkDE That's exactly what we are trying to catch, just by merely describing what happened mast not be enough for a complicated issue.
> 
> It would still be great to keep recording the debug log consistently until the end and catch it off-guard when it happens.

okay, i will try that, but when i start debug log before, does the app runs different in visual with active debug logging? When yes, then i don't see if my schedule is started and don't see if is done.

**Comment by d4rken** [comment]
Note for myself:
Possible error triggering the retry mechanic of the worker.
Unclear what causes the initial error and retry.
Cancel not working due to loop? Cancellation exception -> retry .... ?

**Comment by MarkyMarkDE** [comment]
> Note for myself: Possible error triggering the retry mechanic of the worker. Unclear what causes the initial error and retry. Cancel not working due to loop? Cancellation exception -> retry .... ?

note to you: this happens only on Android 13/14 (Pixel 7 not rooted) not on AndroidTV 11 (here is all fine!)

**Comment by MarkyMarkDE** [comment]
[eu.darken.sdmse_logfile_1696874127636.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12849538/eu.darken.sdmse_logfile_1696874127636.log.zip)

Here the log, it shows all my reportet tickets

**Comment by MarkyMarkDE** [comment]
SDMaid SE is driving me absolutely crazy!

My schedule was of course not started on time at 8pm, but much later (why not exactly at my plan?).
Then the job was done and since then the task "Standardzeitplan" starts again and again, and I can always click cancel and still this schedule is started again and again, really have to kill the app, wait for some minutes and starts it manually & gave access to Accessibility service again, then I have peace for today but tomorrow is exactly the same problem. The problem is only on my Pixel 7 with Android 13/14, on AndroidTV with Android 11 everything is perfect, even the schedule is executed 100% exactly and not restarted continuously afterwards. What is different on Android 13/14 or on Pixel 7 than on AndroidTV?

**Comment by d4rken** [comment]
> Then the job was done and since then the task "Standardzeitplan" starts again and again, and I can always click cancel and still this schedule is started again and again, really have to kill the app, wait for some minutes and starts it manually & gave access to Accessibility service again, 

Do you have the scheduler option enabled to use the accessibility service?
By default, the scheduler shouldn't use the accessibility service, because the scheduler runs in the background and the accessibility service does not work in the background.

**Comment by MarkyMarkDE** [comment]
![Screenshot_20231014-001116](https://github.com/d4rken-org/sdmaid-se/assets/12845477/702d6fb8-389c-463f-8f47-b7d0d34fc11c)

![Screenshot_20231014-001139](https://github.com/d4rken-org/sdmaid-se/assets/12845477/da26ed91-f304-475e-95db-393e2f06bdeb)

**Comment by d4rken** [comment]
I still couldn't reproduce it and no one else was able to record this on a log so far.

After further pondering though :beers:, I don't think this is related to retry behavior and might be a time calculation issue.

While the docs don't explicitly mention it, I think the `setInitialDelay` function for the work requests can be subject to variance, depending on the systems power management.

So in a scenario where the system executes the work manager task in an "earlier slot" to batch work operations across all apps to save battery, it's possible that our scheduled work executed before it's exact scheduled time.

e.g. Schedule is set to 22:15, but the system executed it at 22:10. If the work only takes 4min, then at the end of the work, SD Maid would call `reschedule()` and that would look up the time, see that it is before 22:15, and reschedule it for 22:15, so it would execute again very soon (theoretically even immediately if the system doesn't respect `setInitialDelay` again.

**Comment by MarkyMarkDE** [comment]
okay and I found out, that this happens, when the accessibility mode is enabled but on AndroidTV I had also another problem. The Cache Cleaner had a lot of Problems to work and was trying often to delete some Caches.

So I deleted today the Cache and Data from SD Maid and set up the App again. After this, I run SD Maid manually and the Cache Cleaner worked without any Problems.

I will see in the next days if this was the solution for that (I think so), maybe with the old "Cached" Settings from 0.14.* > 0.15.* can some Incompatible Settings enabled which require explicitly root access now.
On my Phone, I did the same now.

So now maybe incompatible settings should normally resetted by default if this now can result in Problems as reason of deeper changes in the code base.

With the new settings I see, that lot of options which I had enabled before are now disabled by default (I have no root access on my devices).

**Comment by boognish-rising** [comment]
I want able to read the entire thread but this sounds like the issue I'm experiencing on my pixel 6 pro running 14. It doesn't occur on my 8 pro running 14.

Basically, it just keeps triggering over and over again until ultimately, I just had to turn scheduling off on that device. When I have a bit more time than I do rn I'll gladly provide anything that would be helpful (and read the thread in its entirety)

**Comment by MarkyMarkDE** [comment]
Ich sage es nur ungern, das Problem existiert sowohl auf AndroidTV als auch auf dem Pixel7 mit November Update weiterhin
sdmaid-se-0.16.2beta0-foss

[eu.darken.sdmse_logfile_1699473354148.log.zip](https://github.com/d4rken-org/sdmaid-se/files/13301020/eu.darken.sdmse_logfile_1699473354148.log.zip)

Auch fehlt in der Hauptübersicht nun die Zeile "Zuletzt Ausgeführt" auch bei beiden Androids, ist das so gewollt?

**Comment by MarkyMarkDE** [comment]
noch ein Nachtrag: ich möchte dafür kein eigenes Ticket auf machen, mir ist im Bezug auf SDMaid etwas aufgefallen, darüber müsste ich mal mit dir sprechen. Ich hatte es ja schon mal angesprochen, ich meine dass es ein Problem mit den von SDMaid gespeicherten "Daten" (Quasi mit den gespeicherten Appeinstellungen) gibt, was ich bisher bei keiner anderen App so wahrgenommen habe.

**Comment by MarkyMarkDE** [comment]
@d4rken was hast Du mit SD-Maid 0.16.0beta0 gemacht?
Die App rennt wie bekloppt durch das System, hast Du den Code gedoped? Super!!!

Aber: auf regulärem Android 14 mit November Patch hat SD-Maid bei einigen Elementen Probleme, die Caches zu löschen. Die App bleibt bei einigen Elementen länger stehen und leider sehe ich auch nicht welche Elemente das sind, da das im Progress Overlay nicht dabei steht.
Es waren mal z.B. Bluetooth und Tethering. Ob das jetzt auch noch so ist, sehe ich ungünstigerweise nicht.
Ebenso ist im Progress Overlay nur noch der Spinner, aber kein "Progress Status" mehr, ist das so beabsichtigt?
Dafür ist nun die Zeile "Zuletzt ausgeführt" wieder da :wink: und anscheinend ist der Bug mit dem niemals enden wollenden Zeitplan auch nicht mehr vorhanden. Habe SD-Maid gestern aktualisiert und heute gab es schon mal keinen Loop mehr.
Mal sehen was morgen ist ....

**Comment by MarkyMarkDE** [comment]
@d4rken ich weiß wirklich nicht, was Du mit SD Maid 0.16.0beta0 gemacht hast, die Dauerschleife (alle 10 Minauten) des Zeitplaners ist weg. Gestern alles gut und heute auch (sowohl AndroTV als auch Andro). Super! Daher schließe ich dieses Ticket jetzt. Auch wenn der Changelog diesbezüglich nichts hergibt, scheint irgendwas anderes was Du optimiert oder korrigiert hast, diesen Fehler gelöst zu haben.

**Comment by MarkyMarkDE** [comment]
:unamused: the bug is back.

Zuerst fing es auf AndroTV an, am dritten Tag kam es wieder zur alle 10 Minuten startenden Schleife des Zeitplans. Dann habe ich dort die App neu eingerichtet, mit exakt den gleichen Einstellungen wie vorher.
Bis dahin lief auf dem Pixel noch alles richtig. Dann habe ich aber am selben Tag dort auch alles neu eingerichtet und seither wird in beiden Andros der Standarzeitplan alle 10 Minuten gestartet, aber lustigerweise erst am dritten Tag. Ich habe aber gar nichts geändert. Muss dann wieder für ein paar Minuten den Zeitplan deaktivieren. Meine Geräte laufen 24 Std. durch, es sei denn es gibt Updates, die einen Neustart erfordern. Müssen vielleicht in regelmäßigen Abständen irgendwelche init-Prozesse getriggert werden oder so?

**Comment by MarkyMarkDE** [comment]
@d4rken also es ist tatsächlich so:

AndroTV: am 3. Tag (waipu 4k Stick ohne Reboot zwischendrin) funktioniert der Zeitplaner nicht mehr, sprich SD Maid registriert den erfolgreichen Lauf nicht mehr, es hilft nur ein Neustart des waipu 4k Sticks, nach Neustart läuft der Zeitplan nochmal durch und alles ist für 2 Tage prima.

AndroNormal: auch hier dasselbe Spiel, allerdings genügt hier ein Deaktivieren des Zeitplans für einige Minuten, dann startet SD Maid zumindest an diesem Tag nicht alle 10 Minuten, am Folgetag geht es auch hier wieder los, d.h. auch hier muss man nach 48 + Stunden das Gerät neu starten, dann läuft der Zeitplan auch hier wieder problemlos durch und 2 + Tage später dasselbe in Grün.

Was muss SD Maid also alle 48 + Stunden tun? 
Das scheint ja irgendwie die "magische" Zeitspanne zu sein, ab wann der Zeitplan in die Hose geht.

**Comment by boognish-rising** [comment]
Just an update: whereas before I experiencing the same issue @MarkyMarkDE is describing, I haven't noticed it in a while on my Pixel 6 Pro, which if you recall was the device on which SDMaid SE exhibited the behavior. It's possible if happened without my noticing, since it's not my primary device anymore but in my experience with this particular bug, it did not resolve itself so, who knows?

I haven't experienced it at all on my Pixel 8 Pro. Which is strange because they're both on the exact same Android version with all the same security patches, etc. The P6P's bootloader is unlocked but it's not rooted. Not sure how that could make any difference but again, who knows?

**Comment by d4rken** [comment]
While adding a reboot command option to the scheduler, I noticed that if the worker just dies, the system will retry it. #842 includes a change that prevents this, so this issue here could be fixed after the next update. What remains unclear is why the worker was crashing in your cases :thinking:

**Comment by MarkyMarkDE** [comment]
wieder sehr seltsam: ich musste auf Android 14 SD-Maid killen, Cache und Daten löschen und SD-Maid neu einrichten (vorher immer error in der Notification bar). Danach das System neu booten, jetzt läuft der Scheduler schon den zweiten Tag in Folge ohne Fehler durch (Task Standarzeitplan ran successful in der Notification bar). Auf AndroTV habe ich nur die x.1 über die x.0 installiert und den Stick neu gestartet, auch hier schon den zweiten Tag in Folge ohne Loop und somit sind beide Geräte jetzt seit über 48 Stunden in Dauerbetrieb. Hoffentlich bleibt es jetzt so.

**Comment by MarkyMarkDE** [comment]
So wie es scheint, hat 0.17.1 das Problem schon gelöst aber ich musste auf Android 14 SD-Maid killen, Cache und Daten löschen und die App neu einrichten, warum weiß ich nicht. Vorher lief jeder Zeitplaner in Fehler - warum? Keine Ahnung. 

Die letzten drei Tage (01.12 bis einschließlich 03.12.), lief alles auf beiden Androids korrekt (beide Geräte wurden nicht neu gestartet), vorhin vor dem Zeitplaner das Update auf 0.17.2 gemacht und der Zeitplaner danach lief auch problemlos durch (ran successful oder wie es in deutsch jetzt heißt). 

Auf Stein geklopft, dass dieser Bug endgültig gelöst ist. Werde in jedem Fall weiterhin Feedback geben.

Sollten der SD-Maid Cache und Datenbereich wirklich in manchen Fällen das Problem sein, bräuchte man hier vielleicht irgendeine Lösung.

**Comment by MarkyMarkDE** [comment]
yep, this bug is really fixed now, thank you so much!
btw: i'm now a monthly sponsor of your work here on git :wink:
