### ISSUE TITLE
Statistics missing? 

### ISSUE THREAD

**Issue by rmkhalfay** [d4rken-org/sdmaid-se#694]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

> Mornings in Sweden are always very cold and I'm not an early bird.

**Describe the solution you'd like**

> I would like it if SD Maid could make me coffee in the morning.

**Describe alternatives you've considered**

> I have considered making the coffee myself but both me and myself decided against it.

**Describe why this would be in the interest of all users**
Describe why this is not a niche feature, but would be a benefit for the majority of users.

> Everyone enjoys getting a hot beverage on a cold morning.

**Additional context**

After schedule run or manual run the statistics of data cleaned  is not seen anywhere 

Also the scheduled run does not run even after unrestricted battery setting, only after clicking on the notification the job runs

**Comment by d4rken** [comment]
Please create a more appropriate bug ticket with the default texts removed and some info about your device and versions.

**Comment by d4rken** [comment]
Scheduler timing issues #693 

Statistics is not missing, the feature is just not currently part of SD Maid 2, I've not seen many people use this in detail in SD Maid 1, and all lesser used features are not added yet.
