### ISSUE TITLE
Inconsistent setup behaviour

### ISSUE THREAD

**Issue by DragonJTS** [d4rken-org/sdmaid-se#698]
During setup, both shizuku and root access have the option to use _if_ available, and state the setting has no effect if not rooted/don't have shizuku. 
If both are enabled but you have neither root nor shizuku, the root option will just be ignored, but the shizuku option will consider setup incomplete until it can be found. The wording should be changed for one of them, or both should behave the same way.

**Comment by d4rken** [comment]
With 651bbc2297fc60b9d2021d69347b75b3016a755b the Shizuku card should hide like the root card. "Waiting for link" will only be shown if the Shizuku app is actually installed.
