### ISSUE TITLE
Android/data access setup on Android 12 Samsung ROMs

### ISSUE THREAD

**Issue by jackemygdio** [d4rken-org/sdmaid-se#700]
Ao tentar garantir o acesso ao framework de acesso ao armazenamento não e aberta a janela com o caminho pré-selecionado, ao clicar em "Garantir acesso" abre a janela do app arquivos onde não e possível localizar pastas como /storage/emulated/0/Android/data, /storage/emulated/0/Android/obb. Por bloqueio do Android 

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'Configurações'
2. Clique em 'Configuração'
3. Role para baixo até 'Framework de acesso ao armazenamento'
4. Clique em 'Garantir acesso
5. Veja o erro **a janela não abrirá com o caminho correto pré-selecionado. As entradas não ficam verdes porque o acesso não é concedido.**

**Smartphone (preencha as seguintes informações):**
Dispositivo: [Galaxy A31]
 - SO: [ANDROID 12]
 - Status da raiz [sem informação. ]
 - Versão SD Maid 2/SE [0.14.0-beta0]
 Registro de depuração:

[eu.darken.sdmse_logfile_1696793443145.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12841565/eu.darken.sdmse_logfile_1696793443145.log.zip)

**Comment by d4rken** [comment]
Thanks for log continuing here: #639
