### ISSUE TITLE
Shizuku setting triggers in-app notification when Shizuku is unavailable

### ISSUE THREAD

**Issue by mrandreastoth** [d4rken-org/sdmaid-se#715]
**Describe the bug**
A system without Shizuku using the "Use Shizuku if available" setting has the app display a pinned "incomplete configuration" notification.

**To Reproduce**
1. Don't have Shizuku installed
2. Open SD Maid SE
3. Ensure Shizuku is configured to "Use Shizuku if available"
4. Go to the main screen

**Actual behaviour**
The screen displays a pinned notification advising about an incomplete configuration.

**Expected behaviour**
Assuming all other configurations are complete, the main screen will not display the pinned notification about incomplete configuration settings.

**Device information**
 - Device: Samsung S21 Ultra 5G
 - OS: Android  23
 - Root: No
 - Shizuku: No
 - SD Maid 2/SE: 0.14.0-beta0
 
**Screenshots**
![Screenshot_20231013_093130_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/26897855/1b06cece-61f6-4fd1-a422-e8a908e893e9)

![Screenshot_20231013_093138_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/26897855/08a282e2-625c-480f-a462-5f38f3e9ee88)

**Comment by d4rken** [comment]
Should be fixed by #681
