### ISSUE TITLE
App crash on launch with Shizuku/superuser permissions

### ISSUE THREAD

**Issue by PalmDevs** [d4rken-org/sdmaid-se#721]
**Describe the bug**
The app crashes upon launch when superuser permissions are granted or Shizuku access is granted on version `0.15.0-beta0`.

**To Reproduce**
1. Open the app
2. Wait for app to test for superuser permissions/Shizuku access
3. Observe the crash

**Expected behavior**
App should launch and not crash with superuser permissions/Shizuku access.

**Smartphone (please complete the following information):**
 - Device: Samsung A13 (SM-A135F/DS)
 - OS: Android 13
 - Rooted with Magisk 26.3
 - SD Maid 2/SE version 0.15.0-beta0

**Debug log**
`logcat | grep AndroidRuntime`:
```
10-14 06:25:08.144 27985 27985 D AndroidRuntime: Calling main entry eu.darken.sdmse.common.root.service.RootHost
10-14 06:25:09.151 27924 27986 E AndroidRuntime: FATAL EXCEPTION: javaroot:RootConnectionReceiver#385e9c06-cf54-4f51-8cad-9482436ff213
10-14 06:25:09.151 27924 27986 E AndroidRuntime: Process: eu.darken.sdmse, PID: 27924
10-14 06:25:09.151 27924 27986 E AndroidRuntime: kotlin.io.FileSystemException: Failed to get user connection
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at eu.darken.sdmse.common.root.service.internal.RootHostLauncher$createConnection$1$ipcReceiver$1.onConnect(Unknown Source:97)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.doOnConnect(Unknown Source:23)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at eu.darken.sdmse.common.root.service.internal.RootConnectionReceiver.access$doOnConnect(Unknown Source:0)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at androidx.core.app.ActivityCompat$$ExternalSyntheticLambda0.run(Unknown Source:24)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
10-14 06:25:09.151 27924 27986 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Screenshots/Video**
![Video recording of the issue (with superuser)](https://github.com/d4rken-org/sdmaid-se/assets/67689562/7255fd9e-a93c-4314-876e-0095111b72ff)

**Additional context**
- The last working build is `0.14.0-beta0`.
- After investigating, an attempt to fix this issue was made in #705 but that didn't seem to work.
- I have NOT tested with Shizuku yet, but #722 seems to be having issues with that.

**Comment by kopiciekda** [comment]
Same issue
Device: POCO X3 Pro
OS: Android 13
Rooted with KernelSU v.0.6.9
[Log](https://bin.kv2.dev/~6529d9ee5de7ed6bfdb9add2)

**Comment by christantoan** [comment]
Same here with:

Device: OnePlus 7 Pro
OS: Android 11
Rooted with Magisk 26.3
SD Maid 2/SE version 0.15.0-beta0

**Comment by d4rken** [comment]
Doesn't crash in debug mode, might be R8 related. :thinking:
