### ISSUE TITLE
Crash on start with shizuku enabled

### ISSUE THREAD

**Issue by dctrbnsttr** [d4rken-org/sdmaid-se#722]
**Describe the bug**

Version 0.15 crashes on launch with shizuku enabled. 

**To Reproduce**

Launch app when shizuku enabled
Uncheck sd maid se in shizuku app
SD Maid se then launches normally
Re-enable shizuku and sd maid se crashes upon launch

**Expected behavior**

Launch without crash

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

Samsung galaxy s10 plus 
Android 12
Not rooted
SD Maid se 0.15

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

Sd maid se launched normally with shizuku enabled in prior versions

**Comment by PalmDevs** [comment]
#721

**Comment by CapnMarius** [comment]
time: 1697262965338
msg: kotlin.io.FileSystemException: Failed to get user connection
stacktrace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	... 1 more
Caused by: kotlin.io.FileSystemException: Failed to get user connection
	at eu.darken.sdmse.common.shizuku.service.internal.ShizukuHostLauncher$createConnection$1$callback$1.onServiceConnected(Unknown Source:164)
	at rikka.shizuku.ShizukuServiceConnection$$ExternalSyntheticLambda0.run(Unknown Source:272)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7922)
	... 3 more
New Snippet  Fork 
 Memochō

**Comment by mistermojorizin** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Version 0.15 crashes on launch with shizuku enabled.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> Launch app when shizuku enabled Uncheck sd maid se in shizuku app SD Maid se then launches normally Re-enable shizuku and sd maid se crashes upon launch
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> Launch without crash
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. Pixel 9]
> * OS: [e.g. Android 17]
> * Root status [e.g. Rooted - Magisk v25.2]
> * SD Maid 2/SE version [e.g. v0.6.6-rc6]
> 
> Samsung galaxy s10 plus Android 12 Not rooted SD Maid se 0.15
> 
> **Debug log** If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).
> 
> **Screenshots/Video** If applicable, add screenshots or a video if it helps to explain your problem.
> 
> **Additional context** Add any other context about the problem here.
> 
> Sd maid se launched normally with shizuku enabled in prior versions

Same here on 0.15. i don't have root. But crashes with shinzuke. Won't open. Everything was fine on 14. Cleared data several times. As soon as shinzuke gets enabled the problem starts. I'm using Galaxy s23 with Android 13.
