### ISSUE TITLE
App Control

### ISSUE THREAD

**Issue by MartinEM92** [d4rken-org/sdmaid-se#727]
Hi. I want to apologize if I should have written a similar thing on discord (but it didn't work, apparently they have some error today, I also created a second account  there because of this question, it didn't work anyway). The question is will there ever be app control in sd maid 2 like in sd maid 1? I mean, for example, setting the boot after starting, a lot of other functions like this. Sd maid 2 basically only offers what android itself offers. Thank you, because without it, sd maid 2 makes not usable for me. Thank you. Martin

**Comment by d4rken** [comment]
Possibly but not certain, are you talking about these features?

#664 
#599
