### ISSUE TITLE
Accessibility service

### ISSUE THREAD

**Issue by erfirya** [d4rken-org/sdmaid-se#729]
**Describe the bug**
Can't enable accessibility service in the app and in the system settings

**To Reproduce**
1. Go to 'settings > setup'
2. Scroll down to 'accessibility service'
3. Click on 'enable service and grant access'

**Expected behavior**
It should be enabled without any problem

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO X3 NFC
 - OS: crDroid 9.10 Android 13
 - Root status Rooted - KernelSU v0.6.9
 - SD Maid 2/SE version 0.15.1.beta01

**Debug log**
[eu.darken.sdmse_logfile_1697328020975.log.zip](https://github.com/d4rken-org/sdmaid-se/files/12908266/eu.darken.sdmse_logfile_1697328020975.log.zip)

**Screenshots/Video**

https://github.com/d4rken-org/sdmaid-se/assets/71990871/19dc454d-8da5-437b-bafd-8ec9c9ff95ce

![IMG_20231015_082754](https://github.com/d4rken-org/sdmaid-se/assets/71990871/64dbcf14-fbf4-438b-ad69-db3ed1bb209e)
![IMG_20231015_074716](https://github.com/d4rken-org/sdmaid-se/assets/71990871/9dad7f78-6740-4206-b0c9-0ddb11337373)
![IMG_20231015_074732](https://github.com/d4rken-org/sdmaid-se/assets/71990871/aaab9c1e-4ded-469c-b778-9e37734feb6d)
![IMG_20231015_074938](https://github.com/d4rken-org/sdmaid-se/assets/71990871/0bb21375-cc0a-4531-9a71-425645ae27fb)

**Additional context**
When I open AppCleaner settings, the 'include inaccesible caches' setting briefly shows up then disappears (as you can see in the video).

**Comment by d4rken** [comment]
The issue in your video seems to be Google's restriction for sideloaded apps, see here on how to enable it:

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-appops-restrictions

Technically, if SD Maid has root, this should not be necessary though.
SD Maid could either not ask for this setup step, or automatically do it through root :thinking:
