### ISSUE TITLE
Enabling Accessibility Not Remembered 

### ISSUE THREAD

**Issue by GitAlexToTheGreek** [d4rken-org/sdmaid-se#731]
Hi,

Running 0.14.0-beta0 on Samsung S23 Ultra (SM-S918U), Android 13

Every time I use the app, it's necessary to enable Accessibility...

![Screenshot_20231014_201713_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/59787873/a713ee15-1adf-489b-8880-55baa43b0146)

![Screenshot_20231014_201646_Accessibility](https://github.com/d4rken-org/sdmaid-se/assets/59787873/818390d3-8453-413d-94b0-61a621bae0f1)

...for some reason, my ticking of "On" each time is not stored/recalled the next time I use the app.

Any suggestions would be appreciated. 🙂

**Comment by d4rken** [comment]
It's interesting that on some ROMs if the service is killed, the toggle stays "On" but the service is not running, while on other ROMs if the service is killed, the toggle returns to "Off".

Either way, a ROM issue, not an SD Maid issue, see here for some of the solutions.

Granting `WRITE_SECURE_SETTINGS` is probably the most comfortable solution.

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#acs-service-is-disabled
