### ISSUE TITLE
APK Versions 0.52/0.50 do not update or install on Android 14 b2

### ISSUE THREAD

**Issue by ImAgoodGirlSumtimz** [d4rken-org/sdmaid-se#734]
Although d4rken updated the app last night to  eu.darken.sdmse-v0.15.2-beta0-1502000-FOSS-BETA-743eb932.apk, the same issue occurs. 

**Describe the bug**
When you run the apk, it asks if you want to install (or update) SD Maid SE, but when you tap Yes, nothing happens. It never installs or updates and there aren't any further messages or indications that the APK failed or was successful.

**To Reproduce**
1. Go to the download apk
2. Click on the APK, and choose yes to update/install the app.
3. Nothing else happens at all.

**Expected behavior**
I expect the app to install/update successfully 

**Smartphone (please complete the following information):**
 - Device: Verizon Google Pixel 6 Pro 
 - OS: Android 14 beta 2
 - Root status: Non-root
 - SD Maid 2/SE version: 0.15.0 beta 0

**Debug log**
N/A

**Screenshots/Video**
N/A

**Additional context**

**Comment by d4rken** [comment]
I'm able to install the app on a Pixel 8 running Android 14.

Please try to install the app with an app or a tool that gives out error messages, ideally, through adb/termux, e.g. `adb install file.apk`.

Or record a logcat of the install failing.

Common causes are trying to update over an app with the wrong signature, or apps being installed in other profiles that conflict.

**Comment by d4rken** [comment]
What was the solution/fix?
