### ISSUE TITLE
Working Overlay not showing

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#739]
When my scheduled plan is running, I don't have the working overlay anymore and also no status reports in notification bar.

On AndroidTV is all as I would expect overlay while scheduled run, but not on my phone.

Yes, on both devices I have the same settings, incl running and active accessibility mode. 
On AndroidTV is really all what I like to have on my phone too (behavior of the app). 

Pixel7
Android 14
Not rooted
sdmaidse-0.15.2-beta0-foss

**Comment by d4rken** [comment]
Is the display on and the screen unlocked?
The automation will hide the overlay and self-cancel if the lockscreen is enabled or the display is off.

**Comment by MarkyMarkDE** [comment]
> Is the display on and the screen unlocked? The automation will hide the overlay and self-cancel if the lockscreen is enabled or the display is off.

why? your app has full control over my phone, if something is not as expected, then you are maybe able to change e.g. enable the screen and show a message that the user should now unlock his phone or something.
But cancel the complete schedule is in my eyes not the best way to handle such cases.

On AndroidTV all is working well, only on my phone the app make stranger things :wink:

**Comment by d4rken** [comment]
> why? your app has full control over my phone, if something is not as expected, then you are maybe able to change

SD Maid can't unlock the phone.

> e.g. enable the screen and show a message that the user should now unlock his phone or something.

If the phone is locked while the accessibility service should run, that's an error state.
SD Maid could wake the phone, display a dialog and wait for the user to unlock, **but**:

SD Maid does not know why the phone is locked, or the display was off. It's possible that the user is not aware of this and waiting for someone to unlock the screen (which could take hours), would just drain the battery.

> But cancel the complete schedule is in my eyes not the best way to handle such cases.

Normally accessibility service based actions should not even run via Scheduler as they can't run in the background. This has to be manually enabled by the user in settings, the default is to NOT use it as normally it does not work. The setting only exists for edge cases, e.g. Android TVs where the display/lock screen behavior is different. For phones the setting does not make sense.

> And then you show in the app, executed at xx.xx and next execution at xx.xx, but the current job has not runned.

Better status/result/error handling for schedules is planned. I'm still thinking about how to best do it.

I think this is working as expected. You should disable the setting on your phone that the scheduler should use the accessibility service.

Setting up Shizuku and excluding system apps can make the default cache deletion work in the background on phones.

**Comment by MarkyMarkDE** [comment]
> SD Maid can't unlock the phone.

>> And it is really important, that the phone must be unlocked? Or is there another way possible?
As you explained your self, on AndroidTV you don't have such settings and here is all what i would expect.

> If the phone is locked while the accessibility service should run, that's an error state. SD Maid could wake the phone, display a dialog and wait for the user to unlock, **but**:

> SD Maid does not know why the phone is locked, or the display was off. It's possible that the user is not aware of this and waiting for someone to unlock the screen (which could take hours), would just drain the battery.

>> Then wait only for e.g. some minutes only and then cancel first or something.

> Better status/result/error handling for schedules is planned. I'm still thinking about how to best do it.
I think this is working as expected. You should disable the setting on your phone that the scheduler should use the accessibility service.

>> But to delete really all caches you need to have this option enabled, right?

> Setting up Shizuku and excluding system apps can make the default cache deletion work in the background on phones.

>> No way, i have never worked via adb.
I know that you can do some more things over this, but without any knowledge about, you are not able to do anything.

PLEASE TRY TO HANDLE PHONES SAME AS ON ANDROID TV.
I KNOW, YOU ARE A GOOD AND WELL EXPERIENCED PROGRAMMER AND I'M SURE, THAT YOU WILL FIND A WAY OR TRICK, I DO REALLY TRUST IN YOU :wink:

**Comment by MarkyMarkDE** [comment]
> > And it is really important, that the phone must be unlocked? Or is there another way possible?
> 
> Absolutely! It uses the screen like you. It fakes human input. Only what is visible can be interacted with.
> 
> > As you explained your self, on AndroidTV you don't have such settings and here is all what i would expect.
> 
> Because there is no lock screen, right?
> 
> > Only an idea: is it possible to enter my lock screen password in SD Maid settings and then SD Maid is able to unlock my phne with it? This could be really a solution, if this will be possible.
> 
> I don't know 🤔. But I'm not sure that this is a good idea. Using the accessibility service might also be something that Google takes issue with.
> 
> > Then wait only for e.g. some minutes only and then cancel first or something.
> 
> I think that's the wrong approach. It could be seconds, minutes, hours! The scheduler is probably most used when the user is not actively using the device, e.g. while sleeping, so it would probably me closer to hours than minutes.
> 
> > But to delete really all caches you need to have this option enabled, right?
> 
> Yes, but as said, due to the limitations of Android, running this in the background is not possible.
> 
> > No way, i have never worked via adb.
> > I know that you can do some more things over this, but without any knowledge about, you are not able to do anything.
> 
> It is a much much much better solution. Shizuku gives SD Maid access to the ADB user. And the ADB user can force the system to empty caches of user apps, in the background. No accessibility service needed.
> 
> > PLEASE TRY TO HANDLE PHONES SAME AS ON ANDROID TV.
> > I KNOW, YOU ARE A GOOD AND WELL EXPERIENCED PROGRAMMER AND I'M SURE, THAT YOU WILL FIND A WAY > OR TRICK, I DO REALLY TRUST IN YOU AND WE ARE TALKING OVER THE FOSS VERSION, G* WILL NOT SEE > THIS CODES 😉
> 
> I can't do magic 🧙. There are already two solutions available: Root and Shizuku. I currently don't see any other solution.

Yes, i know about, but you are perfect in this what you do - "Chief Developer SAP for Corona Warnapp" right? :wink:
Please try to find a better solution, i'm sure that a way will possible, which we currently not know about. Keep this in your head as a possible "Enhancement Request". Please don't wipe off this Topic completely off the table.
Yes G* maybe would not like that solution, but we are here out of G*, so your Codes have not been passing their automatic reviews, right :wink:

Not all users are skilled in root their device or work with adb - this is much knowledge you need to have.
This is exactly the reason why users install a app what can do clean up all automatic.
