### ISSUE TITLE
In app purchase doesn't applied to another device with same Google account

### ISSUE THREAD

**Issue by Smasherthe7** [d4rken-org/sdmaid-se#742]
Paid the $9 life time purchase on my cellphone to update it to professional edition, however, the app on the android tablet still requires me to pay again for this.

Is the SD maid 2 no longer support to share purchase on multiple devices?

Smartphone:
Nokia XR20
Android 13
Not rooted
0.15.2-beta0
Tablet:
Nokia T20
Android 12
Not rooted
0.15.2-beta0

Appreciate your response!

**Comment by SyafaHadyan** [comment]
This is a Google Play bug, and it happened to me too but not only on SD Maid but on almost every app that I have purchased through In-app purchase option, however, you can restart your device, or tap on the purchase button again on your second device and a pop-up will appear saying that **“You already have this item”** and this action will not charge you again, however if it does not work, you have to wait for a few hours for the purchase to sync.

**Comment by d4rken** [comment]
@SyafaHadyan is right, this is very likely related to how Google Play caches data.

Clearing cache and forcing Google play to do a fresh sync usually fixes this.

I have also made some changes that hopefully reduce the likelihood of this happening, see #747.

**Comment by Smasherthe7** [comment]
Thank you so much Matthew!

Matthias Urhahn ***@***.***> 于 2023年10月22日周日 04:03写道：
