### ISSUE TITLE
sdmaid-se app cleaner loop

### ISSUE THREAD

**Issue by miko614** [d4rken-org/sdmaid-se#744]
Loops everytime i try to clean apps in app cleaner

Device type : RMX3231
Android ver : Android 11 (go edition)

[eu.darken.sdmse_logfile_1697807471960.log.zip](https://github.com/d4rken-org/sdmaid-se/files/13054752/eu.darken.sdmse_logfile_1697807471960.log.zip)

**Comment by bjpafa** [comment]
Yes
