### ISSUE TITLE
Help to disconnect a hacker connected to a Chromebook 3 through the host role USB port to my Samsung A12 Android

### ISSUE THREAD

**Issue by 80901** [d4rken-org/sdmaid-se#746]
What do I have to do to disconnect a Samsung Chromebook 3 from my Samsung Galaxy A12 cell phone? They downloaded software that can connect up to 20 people. They are stealing my cell phone line, emails and company, and my identity is apparently connected by a USB port. Host role and this connected as if I were her daughter connection to link world this is the ip 192.168.0.4 until now it is private, they are criminals who constantly threaten me for a long time ⏳ thank you please, I have been one of your clients for a long time.  This is my email crespomarie509@gmail.com or by this means I will be very attentive GOODBYE 👋

**Comment by d4rken** [comment]
No one is hacking you
