### ISSUE TITLE
PRO version gone after purchase

### ISSUE THREAD

**Issue by apbucaneg** [d4rken-org/sdmaid-se#749]
**Describe the bug**
Already bought the PRO version, one time purchase, but when I checked again after a few hours, it's asking me to purchase PRO again

**Smartphone (please complete the following information):**
 - Device: POCO F3
 - OS: Android 13
 - Root status: Rooted, magisk 26.3
 - SD Maid 2/SE version: 0.15.2-beta0

**Comment by GoldenGorilla18** [comment]
> **Describe the bug** Already bought the PRO version, one time purchase, but when I checked again after a few hours, it's asking me to purchase PRO again
> 
> **Smartphone (please complete the following information):**
> 
> * Device: POCO F3
> * OS: Android 13
> * Root status: Rooted, magisk 26.3
> * SD Maid 2/SE version: 0.15.2-beta0

Go

**Comment by d4rken** [comment]
I think this is fixed in [v0.15.3](https://github.com/d4rken-org/sdmaid-se/releases)

If it's not, can record a debug log for me?

**Comment by apbucaneg** [comment]
Where can I get latest version? I'm just updating via play store, and the
latest is what I have.

Thanks.

**Comment by russell1b** [comment]
Hi, i am also having the same problem. I already bought the one time payment via Google play store. But after i pushed the delete button of the scanned items, it redirect me to upgrade.

Xiaomi mi9t
Derpfest A13 version
Unrooted
0.17.1 beta 0

**Comment by d4rken** [comment]
AFAIK the purchase code is working correctly.

Most issues are related to multiple accounts being used with Google Play.
In that case force an app install through the Google Play website so that it links to the right Google account.

**Comment by kullurumanoj** [comment]
I'm also facing same issue. Already purchased pro via Google play, however it says my app is not pro. When I uninstall and try to install from google play it shows the attached error. However, the app is getting installed. When I try to purchase again it doesn't redirect to google play but redirects to different screen where it shows the app management screen
![Uploading Screenshot_2024-01-20-21-22-28-28_fc704e6b13c4fb26bf5e411f75da84f2.jpg…]()
. Attached the screenshot. Please help!
![Screenshot_2024-01-20-21-20-15-36_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/d4rken-org/sdmaid-se/assets/18289196/8fa4dadf-29b1-4d5e-a984-e84321dd834c)

**Comment by d4rken** [comment]
@kullurumanoj These are issues with the Google Play app or your system, but not SD Maid, so I can't fix them.
