### ISSUE TITLE
Unresponsive UI

### ISSUE THREAD

**Issue by 2Clutch-129** [d4rken-org/sdmaid-se#766]
**Describe the bug**
UI nonresponse to input when selecting (settings, app control, storage analyzer, scheduler & upgrade to pro) as well as premium service from original app not transferring to SE. Scan filters in accessable to customize. App will become completely nonfunctioning after corpse scan

No error message or code given when unresponsive UI becomes completely unusable

All permissions given and accessibility as well. Notifications allowed and not battery optimized

Device: Samsung Galaxy Note 20 Ultra 5G (SM-N986U)
Updated Android 13 & One UI 5.1

Baseband version
N986USQS5HWI1

Kernel version
4.19.113-27095354
#1 Mon Sep 25 17:35:13 KST 2023

SE for Android status
Enforcing
SEPF_SM-N986U_12_0001
Mon Sep 25 17:33:58 2023

Security Patch: October 1st 2023
**No Root**
---------------------------------------------------------------------------------------------

**Expected behavior**
N/A

**Debug log unaccessible due to bug/issue 
App Version 0.15.3-beta0

**Comment by d4rken** [comment]
> App will become completely nonfunctioning after corpse scan

Only after using the CorpseFinder, and not when using any other tool?

**Comment by 2Clutch-129** [comment]
It seems to be working well after a hard restart but initially yes it was
only after using the corpse finder feature. Will my paid version of the
original app transfer over to the new one? Ive yet to find an option to
restore purchases or anything similar that would do so. Thanks for your
help,

– C.M. Jarrell

**Comment by d4rken** [comment]
> It seems to be working well after a hard restart but initially yes it was
only after using the corpse finder feature. 

Okay, so not reproducible :+1: 

> Will my paid version of the
original app transfer over to the new one?

No, see https://github.com/d4rken-org/sdmaid-se/wiki/FAQ
