### ISSUE TITLE
Screen gets stuck at 120 HzScreen gets stuck at 120 Hz refresh rate when using Sd Maid SE on main screen (while using adaptative refresh rate)

### ISSUE THREAD

**Issue by segamalaga** [d4rken-org/sdmaid-se#767]
Issue: Screen gets stuck at 120 HzScreen gets stuck at 120 Hz refresh rate when using Sd Maid SE on main screen (while using adaptative refresh rate)

Device: POCO X3 NFC 
Android version: 13 
Custom ROM: Octavi OS AOSP 
App version: 0.15.3 beta (Pro Version Trial)
Root status: rooted via Kernel Su v11328
Steps to reproduce:
1. Open Sd Maid SE.
2. Go to the cleaning page.
3. Start the cleaning process.
4. Observe the refresh rate of the screen.
Expected behavior: The refresh rate of the screen should dynamically adjust based on the
content being displayed as any other apps in my device does
Actual behavior: The refresh rate of the screen gets stuck at 120 Hz.
Additional information: This issue is erratic and does not occur every time the app is used.
However, it has been observed multiple times.
Impact: This issue reduces the battery life of the device and can also cause the device to
overheat.
Severity: Medium

Screenshots: some of them showing app stucked at 120hz on main screen and others where refresh rate is variable (refresh rate counter on the upper left)

![Screenshot_20231029-233810_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/55357602/3f029874-9f28-4746-899d-7631b5196206)
![Screenshot_20231029-234053_Chrome](https://github.com/d4rken-org/sdmaid-se/assets/55357602/d720f168-7e22-4046-9e28-5386d948ce8b)
![Screenshot_20231029-235215_KernelSU](https://github.com/d4rken-org/sdmaid-se/assets/55357602/63efe54d-8c0a-4559-9868-c12afab44903)

**Comment by d4rken** [comment]
There is no code in SD Maid that is specifically related to the refresh rate.

Your ROM likely maxes the refresh rate while animations are being displayed, e.g. the progress counter or the animated SD Maid mascot.

Does the refresh rate change if you go to a static screen like the settings?

**Comment by d4rken** [comment]
This is working as intended. It's the animation on the dashboard causing the screen to be at max refresh rate. If you go into settings or any other static screen, the refresh rate drops.
