### ISSUE TITLE
Error when opting to Upgrade SD Maid: BillingClientException

### ISSUE THREAD

**Issue by drewwesley** [d4rken-org/sdmaid-se#769]
**Describe the bug**
An 'Error - BillingClientException' prompt appears whenver user action prompts payment (assumed).

**To Reproduce**
1. Go to 'Upgrade SD Maid' section
2. Click on 'Upgrade'
3. See error:
    Error - BillingClientException
    Service connection is disconnected.

...or...

1. Go to AppCleaner
2. Clock on folder icon with magnifying glass to scan for expendable data.
3. Click on 'Delete'.
4. See error (same as above).

**Expected behavior**
A payment window should appear if user encounters a paywall.

**Smartphone (please complete the following information):**
 - Device: Moto G Power (2020)
 - OS: Android 11 (64-bit)
 - Root status: Stock (not rooted)
 - SD Maid 2/SE version: Beta 0.15.3-beta0

**Debug log**

**Screenshots/Video**

**Additional context**
Super good app.

**Comment by d4rken** [comment]
Hm, this is an internal Google Play error. SD Maid failed to connect to Google Play.

There is already a retry-mechanism. I'm not sure what more I can do to reduce the chance of this happening :thinking:.

A reboot usually fixes this, although it's not a great "solution".

**Comment by vaimalaviya1233** [comment]
Issues like billing service disconnected happened to me once while I was using macrodroid and it would normally resolve by force-stop and then opening app again with google play store running in background.
