### ISSUE TITLE
Shizuku connection is missing

### ISSUE THREAD

**Issue by timi35** [d4rken-org/sdmaid-se#774]
**Describe the bug**
With Ashell working Shizuku app, doesn't work with SD Maid.

Shizuko shows SD Maid as allowed app, but the message "Shizuku link is ready" is still missing.

**To Reproduce**
Shizuko Service is online
SD-Maid Setup > Shizuku is on
No message that Shizuku is available and no feature regarding Shizuku.

**Expected behavior**
The message "Shizuku link is ready" is should be available.

**Smartphone (please complete the following information):**
 - Device: Samsung S23 ultra
 - OS: Android 14
 - Root status without root
 - SD Maid 2/SE version 0.15.3 beta 0 pro

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Need a debug log of setting Shizuku up in SD Maid.

**Comment by timi35** [comment]
[eu.darken.sdmse_logfile_1699292833449.log.zip](https://github.com/d4rken-org/sdmaid-se/files/13270876/eu.darken.sdmse_logfile_1699292833449.log.zip)

**Comment by d4rken** [comment]
Is the Shizuku app not installed? SD Maid thinks that at least.

https://play.google.com/store/apps/details?id=moe.shizuku.privileged.api&hl=de&gl=US

If the app is not detected, the link status is hidden.

**Comment by Shadotty** [comment]
I'm having the same problem, I tried to uninstall and reinstall both SD Maid and Shizuku and redo the configuration but without success

Device: Galaxy S23 (SM-911B/DS)
OS: Android 14
SD Maid 2/SE Version: 0.17.0-beta0

![Screenshot_20231115_111637_Shizuku](https://github.com/d4rken-org/sdmaid-se/assets/69601357/1e0acec5-689d-4eb7-bf22-445a791675d5)
![Screenshot_20231115_111634_Shizuku](https://github.com/d4rken-org/sdmaid-se/assets/69601357/16a7bf84-99d5-4f35-a0eb-478d8d33f126)
![Screenshot_20231115_111625_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/69601357/7fd69a40-0ac7-4537-803b-e2ad2ce7c51f)

**Comment by d4rken** [comment]
Did you install Shizuku via Google Play @Shadotty ?
Is there any kind of "hide app" mod going on with it?

**Comment by Shadotty** [comment]
@d4rken yes shizuku has been installed via the play store, regarding the second question I don't think so (?) at least not something that I'm aware of, I even checked if there was some kind of app suspension/sleeping mode going on (maybe OS-wise) but it doesn't seem like it. I even tried to set the app battery usage to "unrestricted" but with no success.

**Comment by d4rken** [comment]
Does SD Maid list Shizuku in the AppControl tool?

**Comment by Shadotty** [comment]
Yes, it does
![Screenshot_20231115_115802_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/69601357/fdc9375e-8d5f-460f-bf37-3de27981de94)

**Comment by timi35** [comment]
Oh, new comments. 
I confirm, I have the same situation.
