### ISSUE TITLE
Not working in new firesticks. Permissions missing 

### ISSUE THREAD

**Issue by jydhthrshrhty** [d4rken-org/sdmaid-se#779]
New firesticks need permissions we can’t grant.

Any plan to add an option we can grant those permissions via a one click adb commands ?

thank you

**Comment by d4rken** [comment]
* What is the specific hardware identifier
* What Android version
* What permission can't be granted?
* Why can the permission not be granted? Error? Greyed out? Not avaiable?

If possible share a video of the issue and record a debug log in parallel if there is an error.
