### ISSUE TITLE
Update to 0.16.1-beta0 impossible 

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#782]
https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.16.1-beta0

Update to 0.16.1-beta0 impossible, there are zip and tar.zip and no apk

![Screenshot_20231106-161135](https://github.com/d4rken-org/sdmaid-se/assets/12845477/85cdc560-83b0-4a09-ae83-8ca1a6d00a12)

**Comment by Oloooooooo** [comment]
> https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.16.1-beta0
> 
> Update to 0.16.1-beta0 impossible, there are zip and tar.zip and no apk
> 
> ![Screenshot_20231106-161135](https://user-images.githubusercontent.com/12845477/280756613-85cdc560-83b0-4a09-ae83-8ca1a6d00a12.png)

Just remane .zip to .apk and then install :)

**Comment by MarkyMarkDE** [comment]
> > https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.16.1-beta0
> > Update to 0.16.1-beta0 impossible, there are zip and tar.zip and no apk
> > ![Screenshot_20231106-161135](https://user-images.githubusercontent.com/12845477/280756613-85cdc560-83b0-4a09-ae83-8ca1a6d00a12.png)
> 
> Just rename .zip to .apk and then install :)

aaaahhh good to know, thank you. On Mozilla tis is same, rename from zip to xpi and all is fine :wink:

**Comment by MarkyMarkDE** [comment]
I close this ticket now. Thanks for assistance and explanation.
