### ISSUE TITLE
After updating to sd maid 0.16.0 the application stopped working

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#785]
After updating to sd maid 0.16.0 the application stopped working

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi note 10 pro]
 - OS: [e.g. Android 13]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.16.0]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).Sd maid SE 0.16.0 does not open after update

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Could it be the same issue as #786?

**Comment by bjpafa** [comment]
Glad to hear that problems exist with rooted devices.
First apk was very good from SDK 19-28 rooted supetSU/Magisk. 👌

**Comment by Panas1989** [comment]
Problem fixed Sd maid SE works as before.
