### ISSUE TITLE
deduplicator cause SDMaid SE crash

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#786]
The new option deduplicator in 0.16.2-beta0-foss causes a crash of SDMaid and it is impossible to start it up again.
When you enable "delete all" and after you do scan the device and delete nothing (click on abort) and you disable "delete all" again and then go back to the result in Main window then delete the founds from previous scan, cause this a crash of SDMaid SE and you are not able to start it again (default error message of android that this app crash often) .

You need to kill the process and delete cache and data and set up the whole app again and all is fine again until you didn't my case here.

Hope you can reproduce this otherwise I will try to provide a debug log.

Pixel7
Android 14
non rooted
sdmaid-se-0.16.1-beta0-foss

**Comment by d4rken** [comment]
Can't reproduce it yet. Got a log or a stack trace?

**Comment by MarkyMarkDE** [comment]
I can't reproduce the bug at the moment, but it was definitely there. Maybe keep an eye on it and you might see things that could be problematic and then optimize it.

By the way: does the time planner currently also execute this new function?

**Comment by d4rken** [comment]
> By the way: does the time planner currently also execute this new function?

Not yet, I'm undecided whether duplicates can/should be deleted without review.

#787 fixes an crash related to the scheduler and battery/power options, could be your crash, but is unrelated to the deduplicator.

**Comment by MarkyMarkDE** [comment]
> > By the way: does the time planner currently also execute this new function?
> 
> Not yet, I'm undecided whether duplicates can/should be deleted without review.

You can add a option here, so the user can decide it by self

![Screenshot_20231107-013518](https://github.com/d4rken-org/sdmaid-se/assets/12845477/8953f62b-b7e2-4b27-864f-6bb09f9d797a)

> #787 fixes an crash related to the scheduler and battery/power options, could be your crash, but is unrelated to the deduplicator.

Mmhh then this cannot be the bug...

**Comment by d4rken** [comment]
Is the crash fixed?

**Comment by MarkyMarkDE** [comment]
> Is the crash fixed?

Can't reproduce it since, so I would say "yes" but I'm not sure. Will close this for now. I can reopen if needed.
