### ISSUE TITLE
Accessibility is your ☠️, at least 4 non root 

### ISSUE THREAD

**Issue by bjpafa** [d4rken-org/sdmaid-se#789]
Android 13 SDK 33 oneplus 9 pro ( include Xiaomi X3 Pro, OnePlus 10 T, Samsung Galaxy 8+, One plus 11)

Since you apply for accessibility.
First, people have things to do.
Your process must go background.

Referring SE beta, which I paid.
Never have seen such a regression. 
UI/UX, especially bugs, dear, canary, Alphas are more stable. 
Acessibility and other functions cease to turn on. 

No one wants a permanent Acessibility permission even for mams.

Improve. 
OK, I'm using non root and buyed root apk, much appreciated at the time. 
Best regards ✨

**Comment by d4rken** [comment]
This is an unactionable ticket, consider using discussions next time.

It's obvious the accessibility service is not a great solution.

You do understand that it's that or nothing, right? :thinking:
If there was a better solution I'd use it.
