### ISSUE TITLE
[feature request] Whatsapp Business backup deletion 

### ISSUE THREAD

**Issue by K-plus69** [d4rken-org/sdmaid-se#80]
Hello,
First of thanks for developing this wonderful app! I will buy the pro in a few days too!

I'm using Whatsapp Business and I think the backups are in another location. It would be nice if the app would scan for these too (if it already doesnt) and delete the older ones!

**Comment by d4rken** [comment]
I don't have WhatsApp Business, so I can't really test it.
Can you share some paths? In what way does it differ?
I think SD Maid already covers some parts of it, what is missing?

**Comment by K-plus69** [comment]
> I don't have WhatsApp Business, so I can't really test it.
> Can you share some paths? In what way does it differ?
> I think SD Maid already covers some parts of it, what is missing?

![Screenshot_20230401-204959.png](https://user-images.githubusercontent.com/90862487/229308995-e3470761-dfa2-4177-b71d-56dc6cca2d19.png)

This is what I found.

**Comment by d4rken** [comment]
That's the path but not the contents, what are the filenames? I'll add support based on the MsgStore file name patterns if this doesn't match, reopen.
