### ISSUE TITLE
Inconsistent default cache sizes

### ISSUE THREAD

**Issue by f1100** [d4rken-org/sdmaid-se#818]
calculating it wrong of system app cache size

 - Device: [e.g. galaxy tab a 2016]
 - OS: [e.g. Android 8.1]
 - Root status [No root]
 - SD Maid 2/SE version [e.g. v0.17-0]
 -![1](https://github.com/d4rken-org/sdmaid-se/assets/41730397/8111fed8-a8bb-46e2-af94-33a29dd07812)
![2](https://github.com/d4rken-org/sdmaid-se/assets/41730397/572d9aa5-5234-4d20-9d21-6893e286e259)
![3](https://github.com/d4rken-org/sdmaid-se/assets/41730397/5865ee17-259f-4e87-baf4-acc00031dd1d)

**Comment by d4rken** [comment]
Do you have any other 3rd party app installed that calculates it correctly?

What does SD Maid 1 show?

**Comment by d4rken** [comment]
Sorry 😢, not a straight forward issue, so I keep procrastinating it...

**Comment by d4rken** [comment]
I've looked into this for the system pkg `android` and I see the discrepancy too but I'm not sure what to do yet.

SD Maid is asking the system API and the `externalCacheBytes` for `android` returns as 33MB, while when visiting the system settings page for `android` it shows as `14.34 KB`.

**Comment by d4rken** [comment]
SD Maid uses the wrong API which also includes other app's sizes if they share the same user-id, which is more common with pre-installed system apps, that's why it was more visible there.

Fix coming :)
