### ISSUE TITLE
Lucky Patcher filter

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#822]
The filter does not work correctly when I want to find the **Lucky Patcher** application

lu -> all work
luc -> doesnt' show anything

[Screenshot_20231120-114154_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/439337/f3e2cb6d-386a-4873-9d53-4f6b8ef5076b)
[Screenshot_20231120-114159_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/439337/56de16d4-5004-408e-9493-820c411f26ed)

**Comment by Sadwhy** [comment]
People still use lucky pather?

**Comment by alabotski** [comment]
1. There is an error that the filter is not working correctly. 
2. What's wrong with Lucky?

**Comment by d4rken** [comment]
Please get a debug log of this.

Is it possible that lucky patcher uses non-default characters (to evade detection) so it's not actual the english letter "c"?

**Comment by alabotski** [comment]
@d4rken 

Hi

On v0.17.1-beta0
I can't reproduce
