### ISSUE TITLE
"Accessibility service is enabled" + "Accessibility service is stopped" when using app in Secure Folder & normal profile

### ISSUE THREAD

**Issue by refugeindhamma** [d4rken-org/sdmaid-se#824]
**Describe the bug**
I am unable to turn on accessibility service in the app inside Secure Folder when I have already installed the app in normal profile and also turned on accessibility service. I have also tried, as suggested by the app, turning on/off the accessibility service and rebooting the phone but it does not solve the problem.

**To Reproduce**
1. Install SD Maid SE in both normal profile and Secure Folder
2. Turn on accessibility service
3. If the app inside Secure Folder is turned on first, the accessibility service cannot be turned on as it will remain grey.
4. If the app in normal profile is turned on first, the app inside Secure Folder will show both "Accessibility service is enabled" & "Accessibility service is stopped" (As shown in screenshot).
5. If I install app inside Secure Folder only, there is no option to turn on Accessibility service on the phone's settings.

**Expected behavior**
Turning on accessibility service for app in the phone's settings should have it enabled and running in both apps in both profiles.

**Smartphone (please complete the following information):**
 - Device: S23 Ultra
 - OS: Android 14
 - One UI 6.0
 - Not rooted
 - SD Maid 2/SE version v0.17.0-beta0

**Screenshots/Video**
[SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/101639308/0f4902e6-e132-4c0f-9e45-b40a9b25c187)

**Comment by d4rken** [comment]
I'm not sure if that can be fixed.

Do you know of any app that supports accessibility services inside the "secure folder"?

**Comment by refugeindhamma** [comment]
The only other app that I'm using is a home launcher "Kvaesitso". It also has the option to enable accessibility. 

If it cannot be fixed, if I leave it as it is, will it affect the operations of the app?

**Comment by d4rken** [comment]
> The only other app, that has the option to enable accessibility, is a launcher "Kvaesitso".

It's possible that launcher apps get special treatment here :thinking: 

> If it cannot be fixed, if I leave it as it is, will it affect the operations of the app?

Only the parts that use the accessibility service, e.g. AppCleaner default caches.

You might be able to regain some of that if you can set up Shizuku to work with the secure folder.

Keeping this open for a bit longer, but I'm currently not sure what to do here.
