### ISSUE TITLE
The scheduler starts but does not clean

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#825]
When the phone is not in an active state and when unlocking it, the scheduler shows opening Google Chrome settings without cleaning at a certain time
**Describe the bug**
The scheduler does not automatically clean and shows the settings of the Google Chrome application in my case
**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Redmi note 10 Pro]
 - OS: [e.g. Android 13]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.17.0-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.
![Screenshot_2023-11-23-07-20-03-394_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/100944730/1bc5e28f-5d50-4e8d-ae3e-9da8deda766e)

**Additional context**

**Comment by d4rken** [comment]
The scheduler can't execute the accessibility service based deletion. This is expected behavior and a technical restriction we can't get around.

But SD Maid should not have attempted it and opened the Chrome settings though...

Is Chrome the app with the biggest cache? i.e. at the top of the list of results in AppCleaner?

**Comment by Panas1989** [comment]
![Screenshot_2023-11-28-17-08-37-049_com miui securitycenter](https://github.com/d4rken-org/sdmaid-se/assets/100944730/3d04e4ae-c064-4d5a-8fdc-7d061a027c1b)
Google Chrome cache memory 297 MB

**Comment by d4rken** [comment]
@kilbert666 Note that the accessibility service based deletion does not work in combination with the scheduler as the device is likely locked when it starts.

**Comment by kilbert666** [comment]
Thank you for that information. That's an easy work around. All I had to do
is use smart lock to keep my device unlocked while I'm at home and change
the time that SD maid runs to that time. I have tried this and it is now
working. Thank you very much.

**Comment by MarkyMarkDE** [comment]
indeed, i use currently Tasker and some Plugins for this App, but it will not really work, this App is really complexly.
It would be great, if darken can help here little bit in settings for SD-Maid (e.g. enable screen if the scheduler starts and keep them active untill the scheduler is finished). This is currently a job for the Tasker App on my Phone, but this feature don't work well as reason that this App is really complex and you also need for some stuff extra Plugins for the Main App Tasker and it is not documented as well.
