### ISSUE TITLE
[BUG] Scheduled tasks start, but task notifications appear and disappear immediately.

### ISSUE THREAD

**Issue by chuwza** [d4rken-org/sdmaid-se#828]
Hi, as shown in the GIF, I set up a scheduled task, and the scheduled task was successfully triggered, but the notification for the task only appeared for a moment, and the notification disappeared immediately.

Is this a Feature or a bug? is the notification disappearing because the background is automatically cleaning it up, or is the task not running?
![sd maid se zz](https://github.com/d4rken-org/sdmaid-se/assets/30049891/6fa541b6-5710-4bff-a9f5-b50cc780ff94)

**Comment by d4rken** [comment]
In the current release the scheduler only has a progress notification.

#821 adds result notifications that should stay until swiped away.
