### ISSUE TITLE
Error SystemCleaner filter failed: EmptyDirectoryFilter(216478389).

### ISSUE THREAD

**Issue by abyss1247** [d4rken-org/sdmaid-se#83]
![Screenshot_2023-04-01-22-47-45-87_a65106d178f5bee05a749e7f17331c4b](https://user-images.githubusercontent.com/116548657/229296423-4429b673-3e4a-4f88-97ae-1f5b4b28b39f.jpg)
[eu.darken.sdmse_logfile_1680360105397.log](https://github.com/d4rken-org/sdmaid-se/files/11129817/eu.darken.sdmse_logfile_1680360105397.log)

**Comment by Rokcy98** [comment]
It happens to me too
![Screenshot_20230401-230944](https://user-images.githubusercontent.com/62332789/229314084-33b68c
[eu.darken.sdmse_logfile_1680383353837.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11130608/eu.darken.sdmse_logfile_1680383353837.log.zip)
ed-46cf-4e01-aece-87431519dbab.jpg)

**Comment by d4rken** [comment]
Two different causes though @abyss1247 is an issue with the storage access framework, while your issue @Rokcy98 uses normal file access (see difference in paths).

**Comment by d4rken** [comment]
@abyss1247 Does this still happen? Everytime you scan?

**Comment by d4rken** [comment]
Can reproduce it by just installing the CapCut app :heart:

**Comment by d4rken** [comment]
Weird stuff, so querying the systems for all items in the folder gives us the name of the subfolders, but if actually querying them the system acts like they don't exist.

If you use the systems SAF explorer, you also see that they are not visible from that perspective...

![Screenshot from 2023-04-03 15-43-35](https://user-images.githubusercontent.com/1439229/229528548-6f89b725-3c01-4029-9265-27c1f78fedf1.png)
