### ISSUE TITLE
Scheduler Finished Banner Notification wont clear

### ISSUE THREAD

**Issue by CraigDoe** [d4rken-org/sdmaid-se#843]
**Describe the bug**
After scheduler has finished the notification banner can not be cleared.

**Smartphone (please complete the following information):**
 - Device: Samsung s22+
 - OS: ONE UI 5.1 Android version 13
 - Root status unknown
 - SD Maid 2/SE version beta 0.17.1-beta0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by CraigDoe** [comment]
![Screenshot_20231201_104141_One UI Home](https://github.com/d4rken-org/sdmaid-se/assets/152568682/9917d612-c35f-4c9c-bcf4-93d05ebb42e8)

**Comment by d4rken** [comment]
Fixed by #839 in next update
