### ISSUE TITLE
Error while iterating empty directory paths

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#85]
It happens to me too
![Screenshot_20230401-230944](https://user-images.githubusercontent.com/62332789/229314096-0f5e7773-46a4-4fd4-8566-5d6a8b5093d4.jpg)
[eu.darken.sdmse_logfile_1680383353837.log.zip](https://github.com/d4rken-org/sdmaid-se/files/11130608/eu.darken.sdmse_logfile_1680383353837.log.zip)

_Originally posted by @Rokcy98 in https://github.com/d4rken-org/sdmaid-se/issues/83#issuecomment-1493123746_

**Comment by Rokcy98** [comment]
My problem could be bypassed by adding the folder to exclusion filter I guess

**Comment by d4rken** [comment]
TwinApps is an "app cloner" by Asus, maybe that makes this folder special.
I can't find anything I could do different to get it to read that folder.

The change by #93 should also "fix" this. The folder will be gracefully skipped and operations should continue. Please reopen if this still happens after the next update.
