### ISSUE TITLE
Subscription is not working 

### ISSUE THREAD

**Issue by Juloboy** [d4rken-org/sdmaid-se#87]
I have purchased the lifitime subscription yesterday and app was showing as a PRO version. Today PRO label is disappeared and I see the opportunity to buy subscription again.... Latest beta of Sdmaid SE.

**Comment by MohamadBayz** [comment]
Mine doesn't show any pro version at all

**Comment by Juloboy** [comment]
> Mine doesn't show any pro version at all

Did you buy subscription too?

**Comment by d4rken** [comment]
Please provide debug logs:
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

e.g. start the recording, close SD Maid, open SD Maid, visit the upgrade screen, then stop the recording and make it available to me.

**Comment by Juloboy** [comment]
> Please provide debug logs: https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log
> 
> e.g. start the recording, close SD Maid, open SD Maid, visit the upgrade screen, then stop the recording and make it available to me.

Log sent to your email

**Comment by K-plus69** [comment]
Had the same problem. Delete the app data. Then it works

**Comment by d4rken** [comment]
> Had the same problem. Delete the app data. Then it works

SD Maid app data? Or Google Play app data?

**Comment by K-plus69** [comment]
> > Had the same problem. Delete the app data. Then it works
> 
> SD Maid app data? Or Google Play app data?

After I purchased the life time license, pro didn't get recognized and pressing "buy" again says that it's already purchased. So I deleted sdmaids app data and it automatically said pro

**Comment by MohamadBayz** [comment]
> 
> Did you buy subscription too?

I started sponsoring in Github but i don't see any pro version in sdmaid se

**Comment by d4rken** [comment]
@MohamadBayz This is unrelated to Google Play. You need to download the [GitHub build](https://github.com/d4rken-org/sdmaid-se/releases), click "Sponsor development", then return back to the app, it will say "SD Maid FOSS" which is the upgraded state of the GitHub build.

**Comment by MohamadBayz** [comment]
> @MohamadBayz This is unrelated to Google Play. You need to download the [GitHub build](https://github.com/d4rken-org/sdmaid-se/releases), click "Sponsor development", then return back to the app, it will say "SD Maid FOSS" which is the upgraded state of the GitHub build.

Ok understood thanks for the explanation
