### ISSUE TITLE
App Cleaner showed over 700 MB to clean, but cleaned only 35

### ISSUE THREAD

**Issue by cccc030** [d4rken-org/sdmaid-se#873]
Ulefone Armor 14 pro
Android 12
Latest Magisk Delta

The issue only but always happens with App Cleaner 

![Screenshot_20231220-060310](https://github.com/d4rken-org/sdmaid-se/assets/83896117/547e99cd-5e18-4b79-9806-4e9fdcd429da)

![Screenshot_20231220-060401](https://github.com/d4rken-org/sdmaid-se/assets/83896117/9f9258a7-c125-42fa-8af6-9ad4d0057a50)

**Comment by d4rken** [comment]
Please provide a debug log:

https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by GamersXbox56** [comment]
Si está aplicación no tuviera q canjear y fuera gratis en todas las funciones de borrar,seria una buena opción para aquellos que no pueden hacer para limpiar su móvil, porque cada vez q se pone para borrar todo se pone para canjearlo y no todos tienen esa oportunidad de tener cuentas de divisas en el extranjero 😔

**Comment by araafroyall** [comment]
try [this](https://github.com/araafroyall/Cleaner-Pro-Lite) advance cleaner instead
