### ISSUE TITLE
Scheduler: after some time, SD-Maid-SE stop updating the logging in statusbar

### ISSUE THREAD

**Issue by MarkyMarkDE** [d4rken-org/sdmaid-se#875]
after some time, SD Maid SE did not update the logging in statusbar of the current running scheduler anymore.
It logging only "current Scheduler execution start xx mins." but no further progress anymore.
Unfortunately I can't say after which time this exact happens ...

sdmaidse-0.18.0-beta0-foss
not rooted
android 14 on Pixel 7 with current patch

**Comment by d4rken** [comment]
You mean the timestamp on the dashboard card "Nächste Ausführung (ungefähr)" is incorrect?

**Comment by MarkyMarkDE** [comment]
> You mean the timestamp on the dashboard card "Nächste Ausführung (ungefähr)" is incorrect?

nein, es steht in der Statusbar nur noch sowas wie "Aktuelle Ausführung Standardzeitplan vor 3 Minuten." oder so ähnlich formuliert, doch es wird der Job selbst nicht mehr geloggt (Erfolgreich or fails)

**Comment by MarkyMarkDE** [comment]
![Screenshot_20231223-200453](https://github.com/d4rken-org/sdmaid-se/assets/12845477/6da9a416-efd9-4d59-8a04-1b4d09f08151)

![Screenshot_20231223-200512](https://github.com/d4rken-org/sdmaid-se/assets/12845477/82084b8e-fd64-4a7e-98a9-27f184ce962a)

**Comment by MarkyMarkDE** [comment]
Das heißt, in beiden Androids läuft vermutlich das gleiche schief, auf TV läuft nicht mal mehr der Job nach einer gewissen Zeit, auf dem Smartphone hingegen schon

**Comment by MarkyMarkDE** [comment]
und beide (TV und Smartphone) haben am 21.12. "ihren Dienst quittiert"

**Comment by MarkyMarkDE** [comment]
habe eben 0.18.1beta0-foss installiert, werde berichten

**Comment by MarkyMarkDE** [comment]
0.18.2-beta0 Genau das gleiche, habe jetzt mal SD Maid gekillt, Cache und Daten gelöscht und alles neu eingerichtet. Lustigerweise waren danach meine App Ausnahmen noch da, alles andere musste ich natürlich wieder einstellen. Oder gibt es jetzt per Default App Ausnahmen für die Sparkasse PUSH TAN App und ImpfpassDE App?

Vorher:
![Screenshot_20231225-200456](https://github.com/d4rken-org/sdmaid-se/assets/12845477/a68c86c0-42ef-49cb-94d8-287dfb88aa96)

**Comment by d4rken** [comment]
> Oder gibt es jetzt per Default App Ausnahmen für die Sparkasse PUSH TAN App und ImpfpassDE App?

Ja

https://github.com/d4rken-org/sdmaid-se/pull/848

Seit

https://github.com/d4rken-org/sdmaid-se/releases/tag/v0.18.0-beta0

Sind aber derzeit nur die 2

https://github.com/d4rken-org/sdmaid-se/blob/4c254802091c128db1a7053a33a77670ce4985db/app/src/main/java/eu/darken/sdmse/exclusion/core/DefaultExclusions.kt#L40-L49

**Comment by MarkyMarkDE** [comment]
oha, habe ich voll überlesen :disappointed: . Nunja super, dann habe ich beim neu einrichten was ja während Beta öfter mal passiert an weniger zu denken :wink;

**Comment by MarkyMarkDE** [comment]
Keine Chance, SD-Maid loggt nicht mehr.
Siehe (direkt nach dem Job) :

![Screenshot_20231226-200421](https://github.com/d4rken-org/sdmaid-se/assets/12845477/afdd0116-d89f-4da6-b7ff-9c720ba6bb36)
![Screenshot_20231226-200514](https://github.com/d4rken-org/sdmaid-se/assets/12845477/3448d403-939f-47e5-8370-c4e9d9425a5e)

**Comment by MarkyMarkDE** [comment]
Keine Chance, SD-Maid loggt nicht mehr.
Siehe (direkt nach dem Job) :

![Screenshot_20231226-200421](https://github.com/d4rken-org/sdmaid-se/assets/12845477/afdd0116-d89f-4da6-b7ff-9c720ba6bb36)
![Uploading Screenshot_20231226-200514.png…]()

**Comment by MarkyMarkDE** [comment]
habe jetzt mal einen Neustart des Gerätes gemacht, mein Zeitplaner ist nicht nochmal angestoßen worden, somit lief der letzt wohl fehlerfrei durch.

Nach Neustart:
![Screenshot_20231226-201738](https://github.com/d4rken-org/sdmaid-se/assets/12845477/50a55d9b-eb77-4490-877e-a217e116c909)

Bislang wurde nach einem Neustart dann "zuletzt Ausgeführt" angezeigt, in dieser SDMaid Version jedoch nicht.

**Comment by MarkyMarkDE** [comment]
Langsam wird es mir echt peinlich.
SDMaid loggt plötzlich wieder.

Was habe ich getan?
Zuerst hatte ich die App ja nur gekillt und Cache und Daten gelöscht. Danach hatte ich die defaults, soweit richtig.
Nur lief SDMaid danach gar nicht mehr!
Gestern habe ich SDMaid vom Pixel7 komplett gelöscht, neu installiert und wieder eingerichtet. Plötzlich war auch mein App Ausschluss wieder da, der ja natürlich nach Cache und Daten löschen nicht mehr da war.
Plötzlich stand auch unter "zuletzt Ausgeführt" wieder ein Datum aber das war glaube der 27.11.23, wo kommt das plötzlich her? Nachdem ich Cache und Daten gelöscht hatte, stand da gar nichts mehr...
Nunja, jetzt im Moment sprich heute das erste Mal, läuft SDMaid wieder korrekt, loggt und auch das zuletzt Ausgeführt Datum ist korrekt.

Was passiert hier?
Stelle ich mich doof an und mache etwas falsch?

Auf AndroidTV ist scheinbar auch wieder alles okay.

Was habe ich gemacht?
Ich habe unter "Apps" - > "Spezielle Berechtigungen" - > "Spezieller App-Zugriff" - > "Optimiert er-Energieverbrauch" restlos alle Apps auf "Energieverbrauch wird nicht optimiert" gesetzt. SDMaid und einige andere eigene Apps hatte ich eh schon umgestellt.

**Comment by MarkyMarkDE** [comment]
> I'm changing the code that updates the last execution time so that it always logs the last time, even if the last execution was aborted due to an error.
> 
> I think the overall issue might have been caused by an error during scheduler execution but to fix that I'll need a log of it.
> 
> I'll consider some kind of history/stats mechanism that can log more details about scheduler executions, in a future update.

maybe it will be even better, if you can "re-init" the whole sd-maid processes after some time, so we are really sure that all is working as expected.
At the moment, I reboot all my devices once a day to ensure that all is working, and all is working well.
