### ISSUE TITLE
Storage Analyzer stuck at 2%

### ISSUE THREAD

**Issue by sombresu** [d4rken-org/sdmaid-se#876]
**Describe the bug**
Stuck at 2% 

**To Reproduce**
Analyze storage space

**Expected behavior**
Scan all storage content

**Smartphone (please complete the following information):**
 - Device: Poco X3
 - OS: Android 12
 - Root status Rooted - Magisk v25.2
 - SD Maid 2/SE version v0.18.0-beta0

**Comment by d4rken** [comment]
Most likely lots of small files.

Provide a debug log of this, then I can look further into it.

https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by ifacify** [comment]
Same here, the process is taking way too long when a lot of files are present on the device, adding a background task that keeps the app awake while the user switches to another app during the process is preferred.

**Comment by d4rken** [comment]
> Same here, the process is taking way too long when a lot of files are present on the device, adding a background task that keeps the app awake while the user switches to another app during the process is preferred.

That's a nice idea. I implemented that for the next update: #934

**Comment by d4rken** [comment]
As @sombresu didn't provide any debug logs, I'm closing this.
