### ISSUE TITLE
The duplicator deleted three necessary photos, they are similar to each other, but could have left one

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#885]
The duplicator deleted three necessary photos, they are similar to each other, but could have left one

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please elaborate.
Note that there is a setting to disable deleting all copies of a duplicate set.
If you have enabled "Perceptual hash" and those 3 images were sorted into into different duplicate sets, then this could have happened. There is no way around that when using any other detection method than checksums.

**Comment by Panas1989** [comment]
> Пожалуйста, дополните. Обратите внимание, что существует настройка, позволяющая отключить удаление всех копий повторяющегося набора. Если вы включили «Перцепционный хеш» и эти три изображения были рассортированы по разным наборам дубликатов, то это могло произойти. При использовании любого другого метода обнаружения, кроме контрольных сумм, этого невозможно обойти.

**Comment by Panas1989** [comment]
I wanted to send these three photos to Viber, then an error popped up and these three photos disappeared, but before this evening the sd maid SE was scheduled to be cleaned, is there a connection between sending photos to Viber from the sd maid SE?

**Comment by d4rken** [comment]
Yes, depending on how SD Maid is configured, the picture could have been deleted, and Viber didn't notice until you tried to send them.

**Comment by Panas1989** [comment]
But I looked at these photos in the gallery, they then disappeared when sent
