### ISSUE TITLE
xiaomi hyperOS can't use

### ISSUE THREAD

**Issue by a500021** [d4rken-org/sdmaid-se#890]
i have just purchased SE and unexpectedly found that it is not usable.Are there any adaptation plans in the future?

**Comment by d4rken** [comment]
Possibly fixed by #888

Please provide a debug log or wait till next update.

**Comment by a500021** [comment]
[eu.darken.sdmse_logfile_1703564455010.log](https://github.com/d4rken-org/sdmaid-se/files/13768578/eu.darken.sdmse_logfile_1703564455010.log)
this is the debug log.

**Comment by d4rken** [comment]
Yes will be fixed in the next update :+1:

**Comment by a500021** [comment]
thx
