### ISSUE TITLE
Accessibility malfunctioning 

### ISSUE THREAD

**Issue by leonardlloyd** [d4rken-org/sdmaid-se#902]
**Describe the bug**
The accessibility set-up is malfunctioning. Everytime I open the SD Maid SE app, it has this accessibility set-up need to be done. What I do is to go thru the set-up process toggle off the button and toggle on again. In short, the accessibility service is disabled even though on the device accessibility service is enabled.

**To Reproduce**
1. Go to 'Continue setup' button
2. Click on 'Download apps
3. Scroll down to 'SD Maid SE' 

**Expected behavior**
The accessibility service once done set-up no longer asking to continue the set-up process. Even when closing the app or force closed the app.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9s
 - OS: Android 12
 - Root status : N/A
 - SD Maid 2/SE version v0.18.2-beta0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
See photos attached for references.
[Screenshot_2024-01-01-22-52-44-258_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/155335881/9d436f6f-3c61-4d20-a801-a9cf12e60e38)
[Screenshot_2024-01-01-22-54-31-021_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/155335881/06308dfe-92ac-4d14-9b3a-58175d7804e7)

**Comment by leonardlloyd** [comment]
![Uploading Screenshot_2024-01-02-00-15-10-501_eu.darken.sdmse.jpg…]()

**Comment by MarkyMarkDE** [comment]
Try to go to Settings -> Apps -> accessibility service and check if SDMaid SE is enabled here.
If you click to much often on turn on or off, Android will block the Action, then you gave to reboot the system before your next change

**Comment by leonardlloyd** [comment]
> Try to go to `Settings -> Apps -> accessibility service` and check if SDMaid SE is `enabled` here. If you click to much often on turn on or turn off, Android will block the Action, then you have to reboot the system before your next change for this Action. The isn't unfortunately not a bug ...

I tried checking to see if the SD Maid SE is 'enabled' and yes it is. I tried to reboot the handset but still issue still exist. It indicates that the Accessibility service is enabled and it stopped. I check it on the setting where it indicates malfunctioning.

I attached the images for references.

![Screenshot_2024-01-06-07-53-49-636_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/155335881/6667be0f-7947-4616-887f-d76fb9af70ee)
![Screenshot_2024-01-06-07-56-52-618_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/155335881/f02a0633-db20-4a8e-8da6-942308e1aeb2)
![Screenshot_2024-01-06-07-56-57-478_com android settings](https://github.com/d4rken-org/sdmaid-se/assets/155335881/2d5b1f4f-5ecd-4df0-8095-35e1d14b7e78)

**Comment by MarkyMarkDE** [comment]
Please provide a debug log, so darken see maybe what's going on your device if the issue is triggered

**Comment by d4rken** [comment]
As @MarkyMarkDE said, some ROMs are notorious for killing the accessibility service, you can find some known workarounds:

https://github.com/d4rken-org/sdmaid-se/wiki/Setup#accessibility-service

If neither of that helps, it gets tough to debug...

**Comment by MarkyMarkDE** [comment]
> As @MarkyMarkDE said, some ROMs are notorious for killing the accessibility service, you can find some known workarounds here:
> 
> https://github.com/d4rken-org/sdmaid-se/wiki/Setup#accessibility-service
> 
> If neither of that helps, it gets tough to debug...

Yes, HUAWEI is really cheeky and kills all "unnecessary" processes just to save power "come hell or high water", much to the annoyance of customers.
For me this case looks like that the ROM has killed the Accessibility Service, this is not a SD Maid SE thing, but we will see.
