### ISSUE TITLE
Custom Filter doesn't process all directories

### ISSUE THREAD

**Issue by alabotski** [d4rken-org/sdmaid-se#904]
**Describe the bug**
I create custom filter to delete `.thumbnails` directories
But for some reason it skips some directories, as an example - /storage/emulated/0/Movies/.thumbnails

**To Reproduce**
Import 
[.thumbnails - 9704731626.json](https://github.com/d4rken-org/sdmaid-se/files/13826680/default.thumbnails.-.9704731626.json)

**Expected behavior**
I want all directories that store thumbnails of photos to be deleted

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - Root status: Kitsune 26.4 Stable
 - SD Maid 2/SE version: 0.18.2-beta0

**Debug log**

**Screenshots/Video**
[Screenshot_20240103-233751](https://github.com/d4rken-org/sdmaid-se/assets/439337/68583d64-48da-43f7-934a-58d12daec8fa)
[Screenshot_20240103-233925](https://github.com/d4rken-org/sdmaid-se/assets/439337/0d698589-0ec7-471c-9096-2606d6157cf7)
[Screenshot_20240104-085739](https://github.com/d4rken-org/sdmaid-se/assets/439337/b8285916-af4b-4bb3-90da-5779e90eda4e)

**Additional context**

**Comment by d4rken** [comment]
I can't reproduce this, I imported your custom filter on a Pixel 5 (A13) and it worked.

[Screenshot from 2024-01-17 18-27-21](https://github.com/d4rken-org/sdmaid-se/assets/1439229/e05889db-118e-4e0d-bf10-6cd677787ba4)

Can you record a debug log of this?

**Comment by alabotski** [comment]
@d4rken 
The problem is this
I excluded the `sdcard/Music` folder
And include `sdcard/Music/.thumbnails`
I want my filters to work independently of other higher-level filters

Because I see this solution now
1. Go to the *Music* folder
2. Create N filters for each subfolder.

And then my *.thumbnails* filter will work

**Comment by d4rken** [comment]
Exclusions always superseed specific filters, what you are trying to do is not supported.

If you create a systemcleaner exclusion for a folder, it will be skipped during search and thus not checked by the filters.
