### ISSUE TITLE
AppCleaner Automation not working when force app to other language than device language

### ISSUE THREAD

**Issue by kaozaza2** [d4rken-org/sdmaid-se#907]
**Describe the bug**
When set app language other than device language, appcleaner automation stuck at app info.

**To Reproduce**
1. Open app
2. Click on onetap at bottom bar.
3. See error

**Expected behavior**
I think problem is automation cannot find target to click because mismatch language.

**Smartphone (please complete the following information):**
 - Device: Samsung S21 FE
 - OS: Android 14
 - Root: none
 - Version: 1.18.2-beta0

**Screenshots/Video**
![stuck app info](https://github.com/d4rken-org/sdmaid-se/assets/11665930/5ae4da62-9e07-47af-89cf-99a72f1e18cf)
![language switch](https://github.com/d4rken-org/sdmaid-se/assets/11665930/1f93fbe1-1fc1-46fb-974d-1fece90700b1)

**Comment by rivalcomp** [comment]
Automation doesn't work either when the language is the same. In my case it's Hungarian. The target text seems to be good (Tárolóhely-használat), but it can't find it and the automation stucks at app info.

(OnePlus 10 Pro 5G, stock Android 14, no root, accessibility service enabled)

**Comment by rivalcomp** [comment]
Automation doesn't work either when the language is the same. In my case it's Hungarian. The target text seems to be good (Tárolóhely-használat), but it can't find it and the automation stucks at app info.

(OnePlus 10 Pro 5G, stock Android 14, no root, accessibility service enabled)

![Screenshot_2024-01-14-14-12-05-93_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/d4rken-org/sdmaid-se/assets/75625744/7cb56e72-d70e-40ed-9ba5-6b85292cfa4c)

**Comment by d4rken** [comment]
Can you record a debug log of this?
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by rivalcomp** [comment]
Dear d4rken,

See the requested log file attached.
Thanks.

Regards,
István Varga

--
Varga István
rendszer-informatikus

RivalComp Szolgáltató Bt.
+36 20 3326966
www.rivalcomp.hu

Microsoft Minősített Szerviz Partner
--

Az üzenetet mobil készülékről küldték. This message was sent from mobile device.

Ekkor: 2024. január 15. 16:21:49 CET, Matthias Urhahn ***@***.***> írta:
>Can you record a debug log of this?
>https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log
>

**Comment by d4rken** [comment]
Attaching files via email attachments does not work with GitHub

**Comment by d4rken** [comment]
@rivalcomp  your issue is unrelated to forcing language settings, please open a new ticket for that with a debug log.

@kaozaza2 I can't reproduce this. I've set my phone to german and forced sd maid to english and SD Maid looks up accessibility sequence (correctly) for german.

**Comment by d4rken** [comment]
@kaozaza2 okay, I can reproduce it if I use the system language setting that FORCE overrides the app. It works though the language is changed from the `System > Settings > SD Maid > Language`. It doesn't work when using `System > Language > Override > SD Maid`

**Comment by d4rken** [comment]
Okay this seems to be an Android bug.

System: DE
App: Default (DE)

When changing to

System: DE
App: EN (forced)

SD Maid gets back the language list [EN,DE] (SD Maid picks first entry and that doesn't work), and after restarting SD Maid it's [DE] and it works again.

:thinking:

**Comment by d4rken** [comment]
Currently think that this is an Android bug, but it is fixed when restarting SD Maid.
