### ISSUE TITLE
Ensure app detects Tidal's offline files / downloaded songs.

### ISSUE THREAD

**Issue by foss-friendly** [d4rken-org/sdmaid-se#909]
**Describe the bug**
Tidal's downloaded songs / songs for offline usage are cleared by the app.

**To Reproduce**
1. Download some songs with Tidal for offline use.
2. Run SD Maid
3. Songs are registered as cache and are cleared by the app.

**Expected behavior**
Offer a way for downloaded songs to remain on device.

**Smartphone (please complete the following information):**
 - Device: Nokia X20
 - OS: Android 13
 - Root status: No
 - SD Maid 2/SE version: Latest from Google Play

**Comment by d4rken** [comment]
Can you provide some paths and maybe a debug log?

**Comment by d4rken** [comment]
Don't have the tidal app, can't proceed here.

Reopen if more details are available.
