### ISSUE TITLE
Das löschen des "Downloads"-Ordners ist nicht möglich, die Einrichtung wird nicht vollständig.

### ISSUE THREAD

**Issue by AtzeOnTour** [d4rken-org/sdmaid-se#913]
Ich bin leider nicht versiert genug, um das Problem genauer zu erklären.
Einfacher Nutzer/Tester ohne technischen Hintergrund.

Habe versucht es auf einem Lenovo Tab zu installieren, funktionierte auf meinem Handy tadellos.
Auf dem Tablet möchte er aber im SD-Card Ordner die "Downloads" Berechtigung zum löschen, was dauerhaft abbricht und somit die Einrichtung unvollständig bleibt.

Alle anderen Funktionen sind möglich.

**Comment by d4rken** [comment]
SD Maid kann nicht immer den richtigen Pfad direkt anzeigen, du musst nachhelfen, eine Ebene über dem Download Ordner ist der richtige Pfad. Statt z.B.: `/"Interner Speicher"/Download` will SD Maid `/"Interner Speicher"/`.

Siehe auch:
https://github.com/d4rken-org/sdmaid-se/wiki/Setup#saf-troubleshooting
