### ISSUE TITLE
AppCleaner hangs at "Buffering life choice"

### ISSUE THREAD

**Issue by sschuberth** [d4rken-org/sdmaid-se#914]
1. Start the app
2. The "AppCleaner" displays "Loading / Buffering life choice" plus a circle that spins forever
3. Pressing "Cancel" has no effect

**Expected behavior**

I'd expect loading to finish reasonable quickly, or at last cancelling to work.

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 40
 - OS: Android 13
 - Root status: n/a
 - SD Maid 2/SE version: 0.18.2-beta0 (Pro)

**Debug log**

[eu.darken.sdmse_logfile_1705081135635.zip](https://github.com/d4rken-org/sdmaid-se/files/13922404/eu.darken.sdmse_logfile_1705081135635.zip)

PS: Is there a way to do this from the PC via `adb shell logcat`?

**Screenshots/Video**

n/a

**Additional context**

n/a

**Comment by d4rken** [comment]
The dashboard loads fine?
Just the AppCleaner showing stuck progress?
Force stopping SD Maid should fix this.
If this is reproducible, please provide steps.

> PS: Is there a way to do this from the PC via adb shell logcat?

If you enable debug mode in `SD Maid Settings > General > Debug` then logcat will contain SD Maid debug output just like the debug log feature.

**Comment by sschuberth** [comment]
> The dashboard loads fine?

Yes.

> Just the AppCleaner showing stuck progress?

Yes.

> Force stopping SD Maid should fix this.

Indeed it did, thanks.

> If this is reproducible, please provide steps.

There were actually no steps other than start SD Maid. Fore reference, this is how the screen looked like:

![Screenshot_20240115-182822](https://github.com/d4rken-org/sdmaid-se/assets/349154/72be34c4-7244-4aab-838d-e8dd283baacb)
