### ISSUE TITLE
deduplicator crash after access the immutable attribute file

### ISSUE THREAD

**Issue by ajdgsu** [d4rken-org/sdmaid-se#916]
**Describe the bug**
Some software creates files for tracking users within public folders (e.g. Download Documents Music Movie etc.).This makes possible to track users across applications.And when you delete the tracking file, it will immediately recreated.So the best way to do is clear  the content in the tracking files and then use "chattr +i" command  lock the file to prevent them from being modified. But when deduplicator reads a file with immutable attribute, it crashes immediately.

**To Reproduce**
1. chattr +i $file (make sure that file is included in the deduplicator search path)
2. runing Deduplicator function

**Expected behavior**
Just skip the inaccessible files

**Smartphone (please complete the following information):**
 - Device: [Xiaomi 13]
 - OS: [MIUI 14.0.17]
 - Root status [Rooted - Magisk Alpha-a0b8aa4d]
 - SD Maid 2/SE version [v0.18.2-beta0]

**Screenshots/Video**
![Screenshot_2024-01-13-20-09-23-748_eu darken sdmse](https://github.com/d4rken-org/sdmaid-se/assets/45306865/c5eb842a-49b6-40bb-8e0a-df1e3e73950a)

**Comment by ajdgsu** [comment]
> Hm interesting, I didn't know you could set `+1` on emulated storage 🤔

You can't. but you can access the /data/media/0 to modify permission(at least work on my device). I'm not sure who created this folder, but this path do have full permission control support, and my data partition still have f2fs encryption.

**Comment by d4rken** [comment]
Hm, can you record a log?

```
r8q:/data/media/0/Download # lsattr vid1.mp4                                                                  
----i----E---------- vid1.mp4
r8q:/data/media/0/Download # lsattr vid2.mp4                                                                  
---------E---------- vid2.mp4
```

![Screenshot from 2024-01-17 15-28-48](https://github.com/d4rken-org/sdmaid-se/assets/1439229/f408a1d5-ce9b-44ea-9754-d65e4b31322d)

I can produce a write exception:

```
15:29:39.771 SDMSE:TaskManager                    E  execute(): Execution failed (3039c5be-dd66-48d2-b82d-1eacb1dea366): DeduplicatorDeleteTask(mode=Duplicates(targets=[Id(value=/storage/emulated/0/Download/vid1.mp4)]))
                                                     eu.darken.sdmse.common.files.WriteException: Can't write to path. <-> /storage/emulated/0/Download/vid1.mp4
```

which makes sense, as it is unexpectably not writable. Not sure where the "FileNotFound" comes from, `+i` should not affect visibility :thinking: 

I'm currently not certain that we should just skip files like this. In a bulk operations they could be skipped and just remain, and if singled out, an error would make sense. Implement such detailed error feedback is a bit much imho though. hmmmmm

**Comment by d4rken** [comment]
Okay so I'm not sure if your error comes from scan or deletion.
If it is from deletion, then I think all is working as expected and extra handling here for `chattr +i` is out of scope. An exclusion would be the solution here.

If this happens during scanning, then I need some more help reproducing it (like a debug log).

**Comment by ajdgsu** [comment]
> Okay so I'm not sure if your error comes from scan or deletion. If it is from deletion, then I think all is working as expected and extra handling here for `chattr +i` is out of scope. An exclusion would be the solution here.
> 
> If this happens during scanning, then I need some more help reproducing it (like a debug log).

Sorry for the late reply, the error comes from scan step and this error fully stoped the deduplicator so I even can't trying to delete them. By the way I updated the latest sdmaidSE(0.18.5-beta0), and the errors are same.
Logs Here:
[eu.darken.sdmse_logfile_1705773731035.zip](https://github.com/d4rken-org/sdmaid-se/files/13998790/eu.darken.sdmse_logfile_1705773731035.zip)

**Comment by d4rken** [comment]
`chmod 000 $file` reproduced it, thanks.
