### ISSUE TITLE
Barrierefreiheit

### ISSUE THREAD

**Issue by Renie44** [d4rken-org/sdmaid-se#918]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by Renie44** [comment]
My Mobile Phone is a Oppo Fx2

**Comment by d4rken** [comment]
Please record a debug log of this
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by Renie44** [comment]
It is much to complicated....I go back to the former version...

Am 15. Januar 2024 16:22:45 schrieb Matthias Urhahn ***@***.***>:
