### ISSUE TITLE
Include root service output in debug logs

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid-se#92]
The current debug log only includes the log output  from the main app process.
Root operations run in a different process and their log output is only available on ADB, when launched in debug mode.

While some of the root output is send back and logged, it could still make debugging some root related operations difficult.

Idea 1:
Write an extra log from the root process, set the permissions right and then include it in the final zip file.

Idea 2:
Two processes appending to the same logfile. This would probably cause corruption? :thinking:

**Comment by dragonGod97677** [comment]
I prefer just including the root log in the final zip file rather appending it
