### ISSUE TITLE
Error - IllegalStateException

### ISSUE THREAD

**Issue by konst5r** [d4rken-org/sdmaid-se#923]
This error appears on the screen after scanning system cash and pressing clean button:

![Screenshot_20240116-130730~2.png](https://github.com/d4rken-org/sdmaid-se/assets/23101459/117df9a1-4b33-4137-aca2-6c3e2b910cb1)

 - Device: Pixel 3a
 - OS: Android 12
 - Root status: not rooted
 - SD Maid 2/SE version: 0.18.3-beta0 (FOSS)

**Comment by d4rken** [comment]
Thanks, will be fixed by #920 

Update is currently building:

https://github.com/d4rken-org/sdmaid-se/actions/runs/7540249986

**Comment by konst5r** [comment]
Same case in the app version 0.18.4-beta0 has IllegalArgumentException error
![Screenshot_20240117-003233.png](https://github.com/d4rken-org/sdmaid-se/assets/23101459/5d35c1dd-bb47-4ab2-b09f-938dee8490b5)
