### ISSUE TITLE
The file cannot be deleted in the system cleaner

### ISSUE THREAD

**Issue by f1100** [d4rken-org/sdmaid-se#927]
system cleaner cannot delete file
![Error while deleting file 1](https://github.com/d4rken-org/sdmaid-se/assets/41730397/fb93c89c-0bb8-4445-9237-7fcb2fdb694d)
![Error while deleting file 2](https://github.com/d4rken-org/sdmaid-se/assets/41730397/4062f66e-61cf-49c5-8713-eb51a6cad0b7)
Not showing the select option in the Android default file manager to select the json file
![Not showing the select option in the Android default file manager to select the json file](https://github.com/d4rken-org/sdmaid-se/assets/41730397/9c058c3b-90f8-4731-b16b-77ad72dc719d)

**Smartphone (please complete the following information):**
 - Device: [e.g. galaxy tab a 2016]
 - OS: [e.g. Android 8.1]
 - Root status [No root]
 - SD Maid 2/SE version [e.g. v0.18.4]

**Comment by d4rken** [comment]
Should be fixed by #926 

I'm preparing a new update.
