### ISSUE TITLE
able to clean .nomedia!!!

### ISSUE THREAD

**Issue by Don1250** [d4rken-org/sdmaid-se#937]
it does not clean .nomedia inside .thumbnails Folder at movies, music & Pictures folder and sd maid 2 does not clean!!!

also other .file aswell!!!!

**Comment by d4rken** [comment]
It makes sense to me to not delete `.nomedia` from thumbnails folders, you don't want (literal) thumbnails pictures in your gallery.

If you still thing there is an issue here, please provide a more detailed description.

https://github.com/d4rken-org/sdmaid-se/wiki/Bugs
