### ISSUE TITLE
Add long click to Changelog Button to copy the version info

### ISSUE THREAD

**Issue by rorar** [d4rken-org/sdmaid-se#939]
**Is your feature request related to a problem? Please describe.**
If I want to post a Bug, I have to manually type in the version number. Takes some time to switch for and back. 

**Describe the solution you'd like**
Add a Copy Button or a Long Click to copy solution to the Changelog settings entry. 

> I would like it if SD Maid could make me coffee in the morning.

**Describe alternatives you've considered**

**Describe why this would be in the interest of all users**
You, as maintainer, would get the whole version info. You could add it in the Bug description to go to Settings > Long Click / Button Click by/on Changelog. 
Users would be able to extract the info's faster. 

**Additional context**
Also I want that SD Made cleans up my room and brews me coffee in the morning. Would be nice to have this feature in the next release 😄

**Comment by d4rken** [comment]
Not a bad idea, I like the changelog longpress.

Could also include the device fingerprint to have some ROM infos, maybe also the update history of SD Maid.

**Comment by d4rken** [comment]
Reminder: Edit the [bug report wiki](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs) to include a note about this hidden feature.
