### ISSUE TITLE
Scheduler? AppCleaner? ACS?

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#943]
The scheduler does not work on Redmi note 10 pro, it only opens google chrome settings and still does not clean everything, then I clean the phone manually on redmi note 8 pro there is no such problem

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
Please provide more details and a debug log.

The scheduler itself is just starting the other tools, which ones are not working and do they work without the scheduler?

**Comment by Panas1989** [comment]
In manual mode everything works fine, only the scheduler does not start scanning and cleaning files, e.g. in Redmi note 8 pro this problem does not exist because it did not exist in SD Maid 1.

**Comment by Panas1989** [comment]
[eu.darken.sdmse_logfile_1706061815662.zip](https://github.com/d4rken-org/sdmaid-se/files/14032866/eu.darken.sdmse_logfile_1706061815662.zip)

**Comment by Panas1989** [comment]
sd maid writes that some scheduled tasks are not executed or executed with errors. Try to run them manually
