### ISSUE TITLE
2 functions is slower than SDM1

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken-org/sdmaid-se#95]
**Describe the bug**
AppCleaner and SystemCleaner seem much slower here on SDM2 than SDM1

**To Reproduce**
Let run and see

**Expected behavior**
Atleast bit fast or really same speed like on SDM1

**Smartphone (please complete the following information):**
 - Device: Oppo A57 4G (2022) / OPPO CPH2387
 - OS: Android 12, ColorOS 12.1, Build CPH2387_11_A.30, with Security Patch Date March 5 2023
 - Root status: NOT ROOTED
 - SD Maid 2/SE version: v0.6.9-rc0

**Debug log**
Will Post one later.

**Screenshots/Video**

**Additional context**
I have a game that have many files and i have many files on my sd card (yes i still have sd card even I've just upgraded my phone from 16GB total internal storage to 128GB)
(Nice version name :3 too tho)

**Comment by dragonGod97677** [comment]
Uh how i gonna get logs in SDM2? is it same as SDM1?

**Comment by d4rken** [comment]
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log

**Comment by d4rken** [comment]
Probably Google's storage access framework... (will be able to tell from your log)
Currently looking at some logs and traced some IO operations. The SAF is just fucking slow. Currently it's very general purpose, SD Maid wants to look up a path and my framework figures out the rest. It treats every request equally, getting a full set of file infos. To speed that up maybe I can make the lookups "lazy" as we don't need all information for every query. :thinking: 

![Screenshot from 2023-04-04 07-55-52](https://user-images.githubusercontent.com/1439229/229700927-97716a37-ee22-40fa-aa0b-4927e78f7d63.png)
