### ISSUE TITLE
After updating the program, the purchased version of pro disappeared

### ISSUE THREAD

**Issue by Panas1989** [d4rken-org/sdmaid-se#959]
After updating the program, the purchased version of pro disappeared

**Comment by githubuser013** [comment]
I'm trying to activate the pro version too with no luck.

**Comment by GTVJR** [comment]
Bij mij het zelfde probleem, betaalt voor pro versie

**Comment by aamadorj** [comment]
Same here! SD Maid SE updated today to version  0.19 on my Pixel 6, which uses has just one Google Account, and the PRO status is lost. I tried to "restore the purchase" but no success at all.

**Comment by Miratoe** [comment]
I've tried the clear cache, reinstall and clear cache for playstore and rebooted it's been well over 6 hours now and it still has not updated back to pro and took my license away for pro.

**Comment by d4rken** [comment]
It's a bug, sorry guys. Fix coming soon.

**Comment by Miratoe** [comment]
Thank you for the great work! And speedy updates.



Sent from my Galaxy



-------- Original message --------
From: Matthias Urhahn ***@***.***>
Date: 2024-01-27 12:53 (GMT-05:00)
To: d4rken-org/sdmaid-se ***@***.***>
Cc: Miratoe ***@***.***>, Comment ***@***.***>
Subject: Re: [d4rken-org/sdmaid-se] After updating the program, the purchased version of pro disappeared (Issue #959)


It's a bug, sorry guys. Fix coming soon.

**Comment by GTVJR** [comment]
Nog steeds niet opgelost.?

**Comment by NMBlanco** [comment]
I updated but the bug seems to be still there.

**Comment by GTVJR** [comment]
Bij mij geen update? Hoe zit dat

**Comment by Eric0661962** [comment]
Bij mij het zelfde verhaal. Moet het programma weer kopen om de betaalde opties te laten werken.

**Comment by d4rken** [comment]
Will be fixed in v0.19.1
It's currently waiting for review in Google Play

**Comment by Eric0661962** [comment]
Thanks for the up-date  I hope the problemen Will be gene soon.

**Comment by mgndnr1** [comment]
> It's a bug, sorry guys. Fix coming soon.

Very many thanks for urgent reply and update

**Comment by ankit988bit** [comment]
Do something developer. It's a must use app. I already purchased but pro version just lost

**Comment by rucanebas** [comment]
Same here. Purchased the pro version back on October but not available anymore

**Comment by d4rken** [comment]
> Will be fixed in v0.19.1
> It's currently waiting for review in Google Play
