### ISSUE TITLE
Feature Request: Save Directory Structure 

### ISSUE THREAD

**Issue by dragonGod97677** [d4rken-org/sdmaid-se#96]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A feature like on SDM1

**Describe alternatives you've considered**
none yet

**Describe why this would be in the interest of all users**
I think this is for those users just want a structure of their directory(s) like me :3

**Additional context**
:3

![Screenshot_2023-04-04-05-06-52-25_62f0e9ef2a35bdc7c62d39832d484c48](https://user-images.githubusercontent.com/38875906/229628150-f8619780-3950-4661-b733-84149db89294.jpg)

**Comment by d4rken** [comment]
Considering this out of scope, feature is too niche.
