### ISSUE TITLE
Won't work after purchased upgrade

### ISSUE THREAD

**Issue by yaoguaiborn** [d4rken-org/sdmaid-se#964]
Purchased the life time upgrade back in September last year and it's been working fine until today. It takes me to the upgrade purchase page whenever I try to use it. The purchase button is greyed out and there's no way for me to recover purchase.

**Comment by Miratoe** [comment]
He already fixed it. It hasn't updated in playstore might take awhile.   I downloaded from the github and it is version 19.1.0 from git a d playstore is still on 19.0.0.   Can confirm its fixed with github version

**Comment by telrod11** [comment]
Thanks for this.   Same issue, so I guess I'll wait for the pain to play store.

**Comment by cerberus6666** [comment]
got the same...telling me to buy again lol on 19.0

**Comment by garstem** [comment]
same issue here

**Comment by mgndnr1** [comment]
> He already fixed it. It hasn't updated in playstore might take awhile. I downloaded from the github and it is version 19.1.0 from git a d playstore is still on 19.0.0. Can confirm its fixed with github version

Thanks for your assistance. I got the same issue and downloaded the GitHub version and :)

**Comment by d4rken** [comment]
#959
