### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by Olusolaope** [d4rken-org/sdmaid-se#966]
I lost full purchase after upgrading SD Maid 2/SE pro.

Kindly resolve and restore my purchase.

Thank you.

**Comment by mgndnr1** [comment]
Hi
I got the same problem and solved it downloading the last GitHub version. Google Play hasn't updated yet.

**Comment by d4rken** [comment]
#959

**Comment by Olusolaope** [comment]
Thank you.

How can I download the latest GitHub version?


> Hi I got the same problem and solved it downloading the last GitHub version. Google Play hasn't updated yet.

**Comment by mgndnr1** [comment]
https://github.com/d4rken-org/sdmaid-se/releases/download/v0.19.1-beta0/eu.darken.sdmse-v0.19.1-beta0-1901000-FOSS-BETA-571ed824.apk
