### ISSUE TITLE
ProVersion wird nicht erkannt/ freigeschaltet 

### ISSUE THREAD

**Issue by Chirstie225** [d4rken-org/sdmaid-se#970]
Der Kauf der ProVersion SDMaid 2/SE wird nicht erkannt bzw. aktiviert. 
Wartezeit nach Kauf 8 Stunden, alle Caches geleert, Phone neu gestartet, playstore aktiviert und wieder aktiviert, App gelöscht und neu geladen

SDMaid Pro wird ebenfalls nicht mehr erkannt.

![Screenshot_20240128_081057_SD Maid SE](https://github.com/d4rken-org/sdmaid-se/assets/157946060/5d3a632e-226a-429d-9851-0280addbdb65)

**Comment by d4rken** [comment]
Ist mit #959 behoben in v0.19.1

Update wartet gerade auf Review von Google.
