### ISSUE TITLE
SD MAID SE

### ISSUE THREAD

**Issue by wow2angel2** [d4rken-org/sdmaid-se#979]
Android Galaxy A54 5G I  had SD Maid Se, but it is  not working right, so I purchased and downloaded SD Maid SE/PRO but I am now getting an error message that says client business not completed though my bank shows it was completely paid for. I can't get neither SD Maid SE to work, nor SD Maid SE/PRO TO work. Can you help me?

**Comment by wow2angel2** [comment]
M

**Comment by d4rken** [comment]
See #959, fix is coming.
