### ISSUE TITLE
No funcions

### ISSUE THREAD

**Issue by eugenioben** [d4rken-org/sdmaid-se#980]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 9]
 - OS: [e.g. Android 17]
 - Root status [e.g. Rooted - Magisk v25.2]
 - SD Maid 2/SE version [e.g. v0.6.6-rc6]

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
See #959

**Comment by eugenioben** [comment]
Al escanear el dispositivo, e intentar borrar, no lo hace  aparec un mesaje
largo para actualizar y hacer una compra unica por 4.50€. Despues de pagar
a traves de google play esta cantidad, sigue igual y no peudo limpiar nada.
Esto ocurre en mi telefono samsung galaxy s 22 ultra.

**Comment by d4rken** [comment]
It's a bug. Wait for the update (0.19.1)

**Comment by eugenioben** [comment]
En la configuración, me pide actualizar el programa, y cuando intento
actualizar, me lle va a la misma pantalla, que es como una propaganda de
las virtudes del programa y al final dice que compre por 1 año a 1.80 o
bien una compra única de 4.50€.
