### ISSUE TITLE
Purchase of Pro Gone

### ISSUE THREAD

**Issue by jonsternberg04** [d4rken-org/sdmaid-se#986]
**Describe the bug**
My purchase of the Pro version is missing. I tried to restore the purchase, but it did not work.

**To Reproduce**
1. Go to star icon in bottom right hand corner 
2. Tap restore purchase
3. Follow the instructions (does not fix the issue for me)

**Expected behavior**
My Pro purchase should be restored.

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Root status: Not rooted
 - SD Maid 2/SE version: 0.19.0-beta0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
If applicable, add screenshots or a video if it helps to explain your problem.

**Additional context**

**Comment by d4rken** [comment]
See #959

**Comment by BakaVacaa** [comment]
https://discord.com/channels/548521543039189022/1047079350157193236/1201238857425883266

If you want to solve the issue this instant
