### ISSUE TITLE
No Pro function after upgrade  

### ISSUE THREAD

**Issue by Helix80** [d4rken-org/sdmaid-se#988]
Hello everyone, 
I got this about 4 months ago. Bought the annual pro version for SD Maid2. 
Now the information there is a problem with the Pro version !
I have now also bought the full version for €5.89. The problem is still there.  
Whats the problem ?

**Comment by BakaVacaa** [comment]
https://discord.com/channels/548521543039189022/1144545886358224966/1201310188330827896

Bug will be updated in the GPS soon but it is updated and uploaded just awaiting review

**Comment by CaffeineOnIce** [comment]
It's fixed in the latest update.

**Comment by noagenda-og** [comment]
Bug is indeed fixed in 19.1. Thanks d4rken!

**Comment by d4rken** [comment]
See #959
