### ISSUE TITLE
Body finder not working 

### ISSUE THREAD

**Issue by Gazzela22** [d4rken-org/sdmaid-se#990]
**Describe the bug**
This error appears when running the body finder:
ReadException

No se puede acceder a

SAFPath(treeRoot=content://

com.android.externalstorage

.documents/tree/227F-16F6,

segments=[Android, data,

com.google.android.youtube]).

Error - IOException:

readable=false

**To Reproduce**
1. Open SD maid
2. Click on Body Finder
3. Get Error - IOException: readable=false

**Expected behavior**
Let it run haha

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A3
 - OS: Android 11 - ROM Lineage OS 18.1 - Kernel 911
 - Root status : No rooted
 - SD Maid 2/SE version: 0.19.1- beta 0

**Debug log**
If you can reproduce the bug, record the event in [a debug log](https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log).

**Screenshots/Video**
![Screenshot_20240129-091656_SD_Maid_SE](https://github.com/d4rken-org/sdmaid-se/assets/158062472/b9432c90-fa69-4c49-b0d3-714830118502)

https://github.com/d4rken-org/sdmaid-se/assets/158062472/d0f55e96-fe8f-4681-9589-4fa570c40b68

**Additional context**

**Comment by d4rken** [comment]
Please provide a debuglog
https://github.com/d4rken-org/sdmaid-se/wiki/Bugs#debug-log
