### ISSUE TITLE
App data always eats a lot of time to load apps in AppControl

### ISSUE THREAD

**Issue by norwaytiewon** [d4rken-org/sdmaid-se#994]
**Is your feature request related to a problem? Please describe.**

> App data always consumes a lot of time while loading apps in AppControl.

**Describe the solution you'd like**

> I would like if we could have an option to toggle this feature of AppControl on/off from settings so that if we don't use App Data feature it doesn't cost our time.

**Describe alternatives you've considered**

> None yet, using App control right now.

**Describe why this would be in the interest of all users**

> Well, App Data takes almost 7 seconds of time and loading app takes only 1, I use AppControl feature to launch apps but it takes 7 seconds extra seconds, it'd help others to launch apps quickly.

**Device Information**

> Xaga on UFS 3.0, MIUI 14 (🙁)

**Comment by d4rken** [comment]
Most of the time is consumed by determining active apps and checking sizes.

I will add a settings menu where both can be toggled off.
